// P10-15: first real ESLint setup in this repo - `pnpm lint` previously
// reported "0 successful, 0 total" since no package defined a `lint`
// script for `turbo run lint` to invoke. Deliberately NOT type-aware
// (no `parserOptions.project`) for this first pass: type-checked linting
// across a monorepo this size is real additional setup/perf cost, and
// the recommended non-type-checked rule set already catches the bulk of
// real issues (unused vars, obvious bugs, React hook mistakes). Worth
// revisiting once this baseline is clean and proven.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";
import { FlatCompat } from "@eslint/eslintrc";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const compat = new FlatCompat({ baseDirectory: __dirname });

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/.expo/**",
      "apps/mobile/android/**",
      "apps/mobile/ios/**",
      "**/.turbo/**",
      "**/coverage/**",
      "packages/db/prisma/migrations/**",
      "apps/web/next-env.d.ts", // auto-generated by Next.js, never hand-edited
      "**/*.config.js",
      "**/*.config.mjs",
      "**/*.config.cjs",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      globals: { ...globals.node, ...globals.es2022 },
    },
    rules: {
      // Prefixing an intentionally-unused arg/var with `_` is this
      // codebase's existing convention (see reverseEngineer.ts's
      // normalizeToolUseInput destructuring) - don't flag those.
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      // Every catch-and-rethrow/error-shape helper in this codebase
      // narrows `unknown` via `e instanceof Error` - `any` shows up
      // mainly at real external-boundary seams (Prisma JSON fields,
      // webhook payloads); flag it, but as a warning to triage, not a
      // hard failure that would block this first pass from landing.
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
  // apps/web: layer Next.js's own rules (React hooks, image/link usage,
  // core web vitals) on top of the shared TS baseline above.
  ...compat.extends("next/core-web-vitals", "next/typescript").map((c) => ({
    ...c,
    files: ["apps/web/**/*.{ts,tsx}"],
  })),
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
    rules: {
      // 32 real instances found on this first lint run, all pre-existing,
      // all purely cosmetic (an un-escaped ' or " inside JSX text renders
      // completely correctly in every browser - this rule is a style
      // preference, not a bug). Downgraded from eslint-config-next's
      // default "error" to "warn" so `pnpm lint`/CI passes clean today
      // rather than immediately going red on day one for findings nobody
      // has triaged yet - still visible, not silenced. Re-promote to
      // "error" once a pass through them lands (mechanical: swap ' -> &apos;
      // and " -> &quot; in JSX text, not attributes).
      "react/no-unescaped-entities": "warn",
    },
  },
  {
    files: ["apps/mobile/**/*.{ts,tsx}"],
    languageOptions: { globals: { ...globals.browser } },
  },
);
