import { readFileSync } from "node:fs";
import vm from "node:vm";
import ts from "typescript";
import React from "react";
import { expect,it } from "vitest";
const source=readFileSync(new URL("../app/projects/[projectId]/test-cases/review/page.tsx",import.meta.url),"utf8"),ast=ts.createSourceFile("page.tsx",source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),declarations=ast.statements.filter(node=>ts.isFunctionDeclaration(node)).map(node=>ts.createPrinter().printNode(ts.EmitHint.Unspecified,node,ast).replace(/export\s+default\s+|export\s+/g,""));
const code=ts.transpileModule(`${declarations.join("\n")}\nthis.page=ReviewQueueSession;`,{compilerOptions:{target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React,module:ts.ModuleKind.None}}).outputText;
function nodes(node:React.ReactNode):React.ReactElement<any>[]{return !React.isValidElement<any>(node)?[]:[node,...React.Children.toArray(node.props.children).flatMap(nodes)];}
function harness(){const hooks:unknown[]=[],effects:Array<()=>void>=[];let cursor=0,dirty=false,result:React.ReactNode;
  const queue={freshAccess:{canRecover:true},fresh:{matching:15,totalPending:15,offset:0,nextOffset:null,items:Array.from({length:15},(_,index)=>({id:`case${index}`,displayId:`TC-${index}`,title:`Case ${index}`,confidence:null,sourceFilePath:null}))},filter:{search:"",sort:"confidence"},notice:"",error:null,refresh:()=>{},setSearch:()=>{},setSort:()=>{},first:()=>{},previous:()=>{},next:()=>{},canOpen:(id:string)=>queue.freshAccess!==null&&queue.fresh.items.some(row=>row.id===id)};
  const decision=(props:unknown)=>React.createElement("div",props as any);
  const context=vm.createContext({React,CaseReviewDecision:decision,useCaseReviewQueue:()=>queue,trpcReact:{useUtils:()=>({testCases:{list:{invalidate:async()=>{}}},caseReview:{count:{invalidate:async()=>{}}}})},useState:(initial:unknown)=>{const at=cursor++;if(!Object.hasOwn(hooks,at))hooks[at]=initial;return[hooks[at],(value:unknown)=>{const next=typeof value==="function"?value(hooks[at]):value;if(!Object.is(next,hooks[at])){hooks[at]=next;dirty=true;}}];},useRef:(initial:unknown)=>{const at=cursor++;if(!Object.hasOwn(hooks,at))hooks[at]={current:initial};return hooks[at];},useLayoutEffect:(effect:()=>void,deps:unknown[])=>{const at=cursor++,prior=hooks[at] as unknown[]|undefined;if(!prior||deps.some((v,n)=>!Object.is(v,prior[n]))){hooks[at]=deps;effects.push(effect);}}});vm.runInContext(code,context);const page=(context as any).page;
  function render(){for(let n=0;n<30;n++){cursor=0;dirty=false;result=page({projectId:"p"});effects.splice(0).forEach(effect=>effect());if(!dirty)return result;}throw Error("Page did not settle");}render();
  const editors=()=>nodes(result).filter(node=>node.type===decision);function open(index:number){const button=nodes(result).filter(node=>node.type==="button"&&node.props.children==="Open supported review snapshot")[index]!;button.props.onClick();render();}
  return{render,editors,open,get result(){return result;}};
}
it("actual queue page retains ten closed editors until explicit child release acknowledgement, then case11 opens without reload",()=>{const h=harness();for(let n=0;n<10;n++)h.open(n);expect(h.editors()).toHaveLength(10);h.open(10);expect(h.editors()).toHaveLength(10);expect(nodes(h.result).some(node=>node.type==="p"&&String(node.props.children).includes("Ten retained"))).toBe(true);const released=h.editors()[9]!;expect(released.props.active).toBe(true);released.props.onRelease();h.render();expect(h.editors()).toHaveLength(9);h.open(10);expect(h.editors()).toHaveLength(10);expect(h.editors().some(node=>node.props.caseId==="case10"&&node.props.active)).toBe(true);expect(h.editors().some(node=>node.props.caseId==="case0")).toBe(true);});
it("Close view only inactivates and retains all editors; native inert ref avoids React boolean-attribute warnings",()=>{const h=harness();h.open(0);h.open(1);const wrappers=()=>nodes(h.result).filter(node=>node.type==="div"&&typeof(node as any).ref==="function");for(const wrapper of wrappers()){const element={inert:false};(wrapper as any).ref(element);expect(element.inert).toBe(wrapper.props.hidden);expect(wrapper.props).not.toHaveProperty("inert");}const close=nodes(h.result).find(node=>node.type==="button"&&node.props.children==="Close review view (retain decision)")!;close.props.onClick();h.render();expect(h.editors()).toHaveLength(2);expect(h.editors().every(node=>node.props.active===false)).toBe(true);for(const wrapper of wrappers()){const element={inert:false};(wrapper as any).ref(element);expect(element.inert).toBe(true);expect(wrapper.props.hidden).toBe(true);}h.render();expect(h.editors()).toHaveLength(2);expect(h.editors().every(node=>typeof node.props.onRelease==="function")).toBe(true);});
