import { readFileSync } from "node:fs";
import vm from "node:vm";
import ts from "typescript";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe,expect,it } from "vitest";
const source=readFileSync(new URL("../components/CaseReviewDecision.tsx",import.meta.url),"utf8"),ast=ts.createSourceFile("review.tsx",source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),declaration=ast.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==="CaseReviewDecision")!;
const code=ts.transpileModule(`${ts.createPrinter().printNode(ts.EmitHint.Unspecified,declaration,ast).replace(/\bexport\s+/,"")}\nthis.control=CaseReviewDecision;`,{compilerOptions:{target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React,module:ts.ModuleKind.None}}).outputText;
function nodes(node:React.ReactNode):React.ReactElement<any>[]{return !React.isValidElement<any>(node)?[]:[node,...React.Children.toArray(node.props.children).flatMap(nodes)];}
function harness(){const counts={save:0,release:0,body:0},editor:any={reads:{fresh:null,projectAccess:{readScope:{actorId:"original"},canRecover:true},error:"sdk-private-query-body"},draft:{decision:"REJECTED",note:{operation:"SET",value:"private-note"},snapshot:{case:{title:"private-case-title"}}},pending:{input:{requestId:"retained-uuid",body:"private-request-body"}},settled:false,busy:false,readable:false,projectReadable:true,canSave:true,canRelease:false,notice:"",change:()=>{},reviewCurrent:()=>{},save:async()=>{counts.save++;},release:()=>false};
  const context=vm.createContext({React,trpcReact:{caseReview:{decide:{useMutation:()=>({})}}},useCaseReviewController:()=>editor,CaseReviewSnapshotContent:()=>{counts.body++;return React.createElement("p",null,"private-rendered-snapshot");}});vm.runInContext(code,context);const control=(context as any).control;
  function render(){return control({projectId:"original-project",caseId:"original-case",onSaved:()=>{},onRelease:()=>{counts.release++;}});}return{editor,counts,render};
}
describe("actual review component project-only recovery markup/handlers, synthetic controller",()=>{
  it("only immutable-request metadata/recovery action are visible, no historical note/body/choice/sdk error or fabricated preview",()=>{const h=harness(),tree=h.render(),html=renderToStaticMarkup(tree);expect(html).toContain("retained-uuid");expect(html).toContain("Recover exact review request");expect(html).toContain("Historical snapshot and note contents are withheld");for(const privateText of["private-note","private-case-title","private-request-body","private-rendered-snapshot","sdk-private-query-body","Reject reviewed snapshot"])expect(html).not.toContain(privateText);expect(html).not.toContain("<textarea");expect(html).not.toContain("<fieldset");expect(h.counts.body).toBe(0);const save=nodes(tree).find(node=>node.type==="button"&&node.props.children==="Recover exact review request")!;expect(save.props.disabled).toBe(false);save.props.onClick();expect(h.counts.save).toBe(1);});
  it("revoked project reader withholds retained UUID and disables save/release, while keeping internal draft for original owner",()=>{const h=harness();h.editor.projectReadable=false;h.editor.canSave=false;const original=h.editor.draft,tree=h.render(),html=renderToStaticMarkup(tree);expect(html).not.toContain("retained-uuid");expect(html).not.toContain("private-note");expect(html).not.toContain("sdk-private-query-body");expect(nodes(tree).find(node=>node.type==="button"&&node.props.children==="Recover exact review request")!.props.disabled).toBe(true);expect(h.editor.draft).toBe(original);expect(h.counts.body).toBe(0);});
  it("known-settled project-only release calls parent only after synchronous child acknowledgement",()=>{const h=harness();h.editor.pending=null;h.editor.settled=true;h.editor.canSave=false;h.editor.canRelease=true;let approved=false;h.editor.release=()=>approved;const button=()=>nodes(h.render()).find(node=>node.type==="button"&&node.props.children==="Close and release unused / acknowledged editor")!;button().props.onClick();expect(h.counts.release).toBe(0);approved=true;button().props.onClick();expect(h.counts.release).toBe(1);expect(h.counts.body).toBe(0);});
});
