import { readFileSync } from "node:fs";
import vm from "node:vm";
import ts from "typescript";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { expect,it } from "vitest";
import { technicalBehaviorLabel } from "./case-authoring-fields";
function functions(path:string){const source=readFileSync(new URL(path,import.meta.url),"utf8"),ast=ts.createSourceFile("component.tsx",source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);return ast.statements.filter(node=>ts.isFunctionDeclaration(node)).map(node=>ts.createPrinter().printNode(ts.EmitHint.Unspecified,node,ast).replace(/\bexport\s+/,"")).join("\n");}
const code=ts.transpileModule(`${functions("../components/CaseProcedureColumns.tsx")}\n${functions("../components/CaseReviewDecision.tsx")}\nthis.renderer=CaseReviewSnapshotContent;`,{compilerOptions:{target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React,module:ts.ModuleKind.None}}).outputText;
function renderer(){const context=vm.createContext({React,technicalBehaviorLabel});vm.runInContext(code,context);return(context as unknown as {renderer:(props:any)=>React.ReactNode}).renderer;}
it("actual renderer SSR shows readable authored/technical/result/response/stable IDs and full raw bound context, not prose-only approval",()=>{const snapshot={kind:"CaseReviewSnapshot/v1",case:{displayId:"TC-42",title:" Exact\n title ",background:"",given:[" Given ",""],when:["Click"],then:["Shows"],priority:"HIGH",testType:"FUNCTIONAL",validationDomain:"SOFTWARE",tags:[" exact,tag "],customFields:{risk:false,retained:null,zero:0}},authoredSteps:[],effectiveSteps:[{action:"Click this button",expectedActionOrData:"onClick GET /apiURL",expectedResult:"View updates",expectedResponse:"HTTP 200\nbody"}],sharedProcedure:null,prerequisites:[{id:"internal",displayId:"TC-12",title:"Login",status:"APPROVED",archived:false}],context:{fieldSchema:{fields:[{key:"risk",label:"Business requirement"}]},unknown:{retained:[null,false,0,""]}},source:{filePath:"tests/flow.spec",framework:"playwright",importSnapshot:{title:"Original source"}},aiBaseline:{value:{given:["AI baseline"]},sqlNull:false},state:{status:"PENDING_REVIEW",origin:"AI_APP_SCAN",note:"",confidence:null,reviewedById:null,reviewedAt:null}};
  const html=renderToStaticMarkup(React.createElement(renderer(),{snapshot}));for(const text of["TC-42","Priority: HIGH","Type: FUNCTIONAL","Origin: AI_APP_SCAN","Technical behavior / data","Click this button","onClick GET /apiURL","HTTP 200\nbody","Separate prerequisites","TC-12","Business requirement","tests/flow.spec","AI baseline","Original source","unknown","sqlNull","NULL","Empty text"])expect(html).toContain(text);expect(html).toContain("white-space:pre-wrap");expect(html).toContain("<details>");expect(html).not.toContain("<details open");expect(html).not.toContain("<script");});
it("retained prose is React-escaped and JSON raw snapshot never executes tags or drops unknown nonobject roots",()=>{const snapshot={kind:"CaseReviewSnapshot/v1",case:{title:"<script>alert(1)</script>",customFields:null},authoredSteps:[],effectiveSteps:[],sharedProcedure:null,prerequisites:[],context:{future:[false,0,""]},source:null,aiBaseline:null,state:{status:"PENDING_REVIEW",origin:"AI_REVERSE_ENGINEERED",note:" \n ",confidence:null,reviewedAt:null,reviewedById:null}};const html=renderToStaticMarkup(React.createElement(renderer(),{snapshot}));expect(html).toContain("&lt;script&gt;");expect(html).toContain("&quot;customFields&quot;: null");expect(html).toContain("&quot;future&quot;");expect(html).not.toContain("<script>");});
it("V2 actual renderer uses bound custom organization step labels, distinct global types and all parent material without live fallback",()=>{const snapshot={kind:"CaseReviewSnapshot/v2",case:{title:"Case",customFields:{}},authoredSteps:[],effectiveSteps:[{action:" Click ",expectedActionOrData:" API ",expectedResult:"",expectedResponse:null}],sharedProcedure:null,prerequisites:[],context:{linkedContext:{kind:"CaseReviewPlanContext/v1",organizationLabels:{organizationId:"original-org",raw:{action:"Tester gesture",future:[null,false,0,""]},sqlNull:false,resolved:{action:"Tester gesture",expectedActionOrData:"Engine event",expectedResult:"Rendered state",expectedResponse:"Network response"}},references:{caseTypeId:"case-type",planTypeId:"parent-type"},types:[{id:"case-type",name:"Case reference role",key:"case-key",description:" Exact\n description ",category:"SOFTWARE",fieldSchema:{unknown:null},fieldSchemaSqlNull:false,isBuiltIn:true,createdAt:"now"},{id:"parent-type",name:"Plan reference role",fieldSchema:null,fieldSchemaSqlNull:true}],plan:{id:"parent",name:" Exact\n parent ",description:"",projectId:"p",testPlanTypeId:"parent-type",status:"APPROVED",releaseId:null,strategyId:null,customFields:{retained:[null,false,0,""]},customFieldsSqlNull:false,executionTemplate:{},executionTemplateSqlNull:false,createdById:null,updatedById:"u",createdAt:"now",updatedAt:"later",latestVersion:{id:"version",versionNumber:4},criteria:[{id:"criterion-one",testPlanId:"parent",requirementId:null,description:" First\n criterion ",status:"AT_RISK",createdAt:"now"},{id:"criterion-two",testPlanId:"parent",requirementId:null,description:"Second criterion",status:"MET",createdAt:"now"}]}}},source:null,aiBaseline:null,state:{status:"PENDING_REVIEW",origin:"IMPORTED",note:null,confidence:null,reviewedAt:null,reviewedById:null}};
  const html=renderToStaticMarkup(React.createElement(renderer(),{snapshot}));for(const text of["Tester gesture","Engine event","Rendered state","Network response","original-org","Case-declared type","Linked-plan assigned type","Case reference role","Plan reference role","global reference definitions","Exact\n parent","First\n criterion","criterion-two","AT_RISK","reopen it through the owned plan workflow","versionNumber","fieldSchemaSqlNull","unknown","future","configured execution templates remain unsupported"])expect(html).toContain(text);expect(html).not.toContain("<details open");expect(html).not.toContain("historical V1 projection");});
