import { createHash,randomUUID } from "node:crypto";
import { describe,expect,it } from "vitest";
import { assertReviewAck,freezeReviewInput,reviewDecisionHash,type ReviewDraft } from "./case-review-decision-draft";
import { reviewDecisionInput,reviewRequestHash } from "../../api/src/services/caseReviewSchema";
const origin={projectId:"p",caseId:"c",organizationId:"o",clerkActorId:"cl",nativeActorId:"n"},scope={projectId:"p",organizationId:"o",actorClerkUserId:"cl",actorId:"n"};
function draft():ReviewDraft{return{identity:"draft",origin,decision:"APPROVED",note:{operation:"SET",value:" \n exact "},contentHash:"a".repeat(64),reviewStateHash:"b".repeat(64),snapshot:{} as never};}
describe("immutable exact scoped review requests",()=>{
  it("freezes exact request key order/body, browser hash equals canonical ordered new request",async()=>{const original=draft(),input=freezeReviewInput(original,randomUUID());expect(Object.keys(input)).toEqual(["projectId","caseId","originalOrganizationId","expectedClerkActorId","expectedNativeActorId","expectedContentHash","expectedReviewStateHash","decision","note","requestId","confirmed"]);expect(await reviewDecisionHash(input)).toBe(createHash("sha256").update(JSON.stringify(input)).digest("hex"));(original.note as {value:string}).value="modified";expect(input.note).toEqual({operation:"SET",value:" \n exact "});expect(Object.isFrozen(input)).toBe(true);expect(Object.isFrozen(input.note)).toBe(true);});
  it("only exact original native ACK settles; hash/status/case/UUID/native differences remain uncertain",async()=>{const d=draft(),input=freezeReviewInput(d,randomUUID()),held={input,draft:d,requestHash:await reviewDecisionHash(input),everAmbiguous:false},ack={projectId:"p",caseId:"c",requestId:input.requestId,requestHash:held.requestHash,decision:"APPROVED" as const,replayed:false,readScope:scope};expect(()=>assertReviewAck(ack,held)).not.toThrow();for(const patch of[{caseId:"other"},{requestId:randomUUID()},{requestHash:"c".repeat(64)},{decision:"REJECTED" as const},{readScope:{...scope,actorId:"other"}}])expect(()=>assertReviewAck({...ack,...patch},held)).toThrow();});
  it("reversed valid SET input order equals actual backend-parsed request hash; KEEP/CLEAR infer no value",async()=>{const d={...draft(),note:{value:" \n exact ",operation:"SET" as const}},input=freezeReviewInput(d,randomUUID());expect(Object.keys(input.note)).toEqual(["operation","value"]);expect(await reviewDecisionHash(input)).toBe(reviewRequestHash(reviewDecisionInput.parse(input)));expect(input.note).toEqual({operation:"SET",value:" \n exact "});for(const operation of["KEEP","CLEAR"] as const){const held=freezeReviewInput({...draft(),note:{operation}},randomUUID());expect(Object.keys(held.note)).toEqual(["operation"]);expect(await reviewDecisionHash(held)).toBe(reviewRequestHash(reviewDecisionInput.parse(held)));}});
});
