// Actual component functions + installed SSR + real isolated controller.
// Auth/native RPC/read completion are synthetic; not browser/native acceptance.
import { readFileSync } from "node:fs";
import { createHash, webcrypto } from "node:crypto";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import ts from "typescript";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { ManualRetestReviewedController } from "./manual-retest-reviewed-controller";
import { admitRetestRead, inspectRetestWire, retestReviewedBrowserKey, type RetestProjection, type RetestReviewedInput, type RetestReviewedSnapshot } from "./manual-retest-reviewed-read";
import { currentSessionScope } from "./auth-query-cache";
import { sameManualRetestScope } from "./manual-retest-scope-ack";
const source=readFileSync(new URL("../components/ManualRetestWizard.tsx",import.meta.url),"utf8");
const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React}}).outputText;
const scope={projectId:"p",organizationId:"o",clerkActorId:"cl"},hash="a".repeat(64);
let counter=0;
function native(projection:RetestProjection="ACCESS",sid="A",ids:string[]=[],nextCursor:string|null=null):RetestReviewedSnapshot{
 const input:RetestReviewedInput={request:{projectId:"p",sourceRunId:"run",testCaseId:"case",expectedScope:scope},readRequestId:`6ee2ec04-4d34-40bf-b0e9-${String(++counter).padStart(12,"0")}`,expectedNativeActorId:"n"},s={...scope,actorId:"n"};
 const readContext={requestId:input.readRequestId,requested:retestReviewedBrowserKey(input),projection,scope:s},requested=JSON.stringify(JSON.parse(readContext.requested).request);
 let wire:unknown={readContext,basis:"CURRENT_PROJECT_MEMBER_ONLY",sourceRelationshipVerified:false};
 if(projection==="LINKS")wire={readContext,links:{scope:s,requested,original:null,retests:ids.map(testRunId=>({testRunId,startedAt:"2026-10-06T12:00:00.123Z",status:"RUNNING"})),nextCursor}};
 if(projection==="PREVIEW")wire={readContext,basis:"LEGACY_BOUNDED_PREPARATION_V1",preview:{scope:s,requested,projectId:"p",sourceRunId:"run",testCaseId:"case",displayId:"TC-1",reviewHash:hash,sourceOutcome:"FAIL",stepFieldLabels:{action:"Tester action",expectedActionOrData:"Technical behavior",expectedResponse:"API response"},configuration:{configuration:"",platform:"",build:"",environment:" Original\n environment ",hardwareRevision:"",firmwareVersion:"",rig:"",batchOrLot:"",calibrationReference:"",protocolReference:""},caseDefinitions:[{testCaseId:"case",title:"PRIVATE Exact\n title ",validationDomain:"SOFTWARE",reviewStatus:"APPROVED",background:null,given:["", " Given "],when:[" When "],then:[" Then "],verificationProfile:{setup:"",safety:"",instruments:"",acceptanceCriteria:""},steps:[{order:0,action:" Click\n button ",expectedActionOrData:" GET /synthetic ",expectedResult:"",expectedResponse:null,mediaAttachmentIds:["ref"]}]}],sourceResults:[{id:"result",testCaseId:"case",status:"FAIL",note:null,errorMessage:"",observations:{specimen:"",hardwareRevision:"",firmwareVersion:"",environment:"",measurements:[{name:"Reading",unit:"V",value:0,instrument:"Meter"}]}}],prerequisiteCount:0,credits:0,sourceDatasetExecution:{batchId:`dataset_${"b".repeat(64)}`,datasetId:"dataset",datasetHash:"c".repeat(64),rowIndex:0,rowName:" Raw row ",values:{empty:"",multiline:" One\n two "}}}};
 const admitted=admitRetestRead(wire,input,projection,"cl",null);if(!admitted)throw Error("Invalid complete synthetic read");
 return Object.freeze({origin:admitted.origin,observedSessionId:sid,projection,epoch:counter,revision:counter,receivedAt:"2026-10-06T12:00:00.000Z",data:admitted.data});
}
type Element=React.ReactElement<Record<string,unknown>>;
function elements(value:unknown,all:Element[]=[]):Element[]{if(React.isValidElement(value)){const e=value as Element;all.push(e);elements(e.props.children,all);}else if(Array.isArray(value))value.forEach(v=>elements(v,all));return all;}
function label(value:unknown):string{return typeof value==="string"||typeof value==="number"?String(value):React.isValidElement(value)?label((value as Element).props.children):Array.isArray(value)?value.map(label).join(""):"";}
type Props={projectId:string;sourceRunId:string;testCaseId:string;open:boolean;onClose:()=>void;active?:boolean;expectedScope?:typeof scope|null;retainedLegacyAttempt?:{projectId:string;sourceRunId:string;testCaseId:string;expectedReviewHash:string;idempotencyKey:string;expectedScope?:typeof scope}|null;onRetainedRequestChange?:(retained:boolean)=>void};
function harness(projection:RetestProjection="ACCESS",actions=false,legacyOwner=false){
 type Slot={value?:unknown;deps?:readonly unknown[];cleanup?:(()=>void)|undefined;memo?:unknown};
 const slots:Slot[]=[],layouts:Array<()=>void>=[],effects:Array<()=>void>=[];let cursor=0,dirty=true,tree:React.ReactNode=null,life=true;
 let view:RetestReviewedSnapshot|null=native(projection),generation=0;
 const sdk={loaded:true,session:{id:"A",user:{id:"cl"}},location:0};
 const reads:Array<{projection:RetestProjection;before?:string}>=[],sent:Array<Parameters<ManualRetestReviewedController["submit"]>[1] extends (x:infer X)=>unknown?X:never>=[],navigate:string[]=[],retention:boolean[]=[],props:Props={projectId:"p",sourceRunId:"run",testCaseId:"case",open:true,onClose:()=>{props.open=false;dirty=true;},expectedScope:scope,onRetainedRequestChange:v=>retention.push(v)};
 let send:(input:typeof sent[number])=>Promise<unknown>=async input=>({testRunId:`retest_${createHash("sha256").update(JSON.stringify([input.request.projectId,input.expectedNativeActorId,input.request.idempotencyKey])).digest("hex")}`,recovered:false,scope:{...scope,actorId:input.expectedNativeActorId,sourceRunId:"run",testCaseId:"case",idempotencyKey:input.request.idempotencyKey,reviewHash:input.request.expectedReviewHash}});
 const same=(a:readonly unknown[]|undefined,b:readonly unknown[]|undefined)=>!!a&&!!b&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i]));
 function effect(fn:()=>unknown,deps:readonly unknown[]|undefined,layout:boolean){const id=cursor++,slot=slots[id]??={};if(!same(slot.deps,deps)){(layout?layouts:effects).push(()=>{slot.cleanup?.();slot.deps=deps;const cleanup=fn();slot.cleanup=typeof cleanup==="function"?cleanup as ()=>void:undefined;});}}
 const hooks={...React,useState:(init:unknown)=>{const id=cursor++;if(!slots[id])slots[id]={value:typeof init==="function"?(init as ()=>unknown)():init};return [slots[id]!.value,(next:unknown)=>{const slot=slots[id]!,value=typeof next==="function"?(next as (v:unknown)=>unknown)(slot.value):next;if(!Object.is(value,slot.value)){slot.value=value;dirty=true;}}];},useRef:(init:unknown)=>{const id=cursor++;slots[id]??={value:{current:init}};return slots[id]!.value;},useMemo:(fn:()=>unknown,deps:readonly unknown[])=>{const id=cursor++,slot=slots[id]??={};if(!same(slot.deps,deps)){slot.memo=fn();slot.deps=deps;}return slot.memo;},useCallback:(fn:unknown,deps:readonly unknown[])=>{const id=cursor++,slot=slots[id]??={};if(!same(slot.deps,deps)){slot.memo=fn;slot.deps=deps;}return slot.memo;},useLayoutEffect:(fn:()=>unknown,deps:readonly unknown[])=>effect(fn,deps,true),useEffect:(fn:()=>unknown,deps:readonly unknown[])=>effect(fn,deps,false)};
 const query=(data:unknown)=>({data,error:null,isFetching:false,isPaused:false,refetch:async()=>query(data)});
 const api={useUtils:()=>({}),project:{byId:{useQuery:()=>query({id:"p",organizationId:"o"})}},organization:{mine:{useQuery:()=>query([{id:"o",role:"EDITOR",seatType:"FULL"}])}},manualRetest:{start:{useMutation:()=>({mutateAsync:()=>{throw Error("INERT legacy handle must never dispatch");}})},startReviewed:{useMutation:()=>({mutateAsync:(input:typeof sent[number])=>{sent.push(input);return send(input);}})}}};
 const reader=()=>{const captured=view,stamp=generation;const current=()=>life&&stamp===generation&&view===captured&&captured?.observedSessionId===sdk.session.id&&captured.origin.clerkActorId===sdk.session.user.id?captured:null;
 return {origin:captured?.origin??null,snapshot:captured,current,refresh:()=>{reads.push({projection:"ACCESS"});view=null;generation++;dirty=true;return true;},read:(p:RetestProjection,before?:string)=>{if(!current())return false;reads.push({projection:p,...(before===undefined?{}:{before})});view=null;generation++;dirty=true;return true;},loading:false,error:null};};
 const modules:Record<string,unknown>={react:hooks,"@clerk/nextjs":{useAuth:()=>({isLoaded:true,isSignedIn:true,userId:"cl",sessionId:"A"})},"./Modal":{Modal:(p:{open:boolean;children:React.ReactNode})=>p.open?React.createElement("div",{"data-modal":"true"},p.children):null},"@/lib/trpcReact":{trpcReact:api},"@/lib/manual-retest-scope-ack":{sameManualRetestScope},"@/lib/use-manual-retest-reviewed-access":{useManualRetestReviewedAccess:reader},"@/lib/manual-retest-reviewed-controller":{ManualRetestReviewedController},"@/lib/auth-query-cache":{currentSessionScope},"@/lib/manual-retest-reviewed-read":{inspectRetestWire}};
 const exports:Record<string,(p:Props)=>React.ReactNode>={};new Function("require","exports","React",compiled)((name:string)=>{if(!(name in modules))throw Error(`Unexpected actual component import ${name}`);return modules[name];},exports,React);
 vi.stubGlobal("window",{Clerk:sdk,location:{assign:(path:string)=>navigate.push(path)}});
 function render(commit=true){cursor=0;layouts.length=0;effects.length=0;dirty=false;const component=exports[actions?"ManualRetestActions":legacyOwner?"ManualRetestWizard":"ReviewedRetestWizard"];if(!component)throw Error("Actual component missing");tree=component(props);if(commit){layouts.splice(0).forEach(fn=>fn());effects.splice(0).forEach(fn=>fn());}return tree;}
 function settle(){for(let i=0;i<30;i++){render();if(!dirty)return;}throw Error("Actual consumer render/layout loop");}
 function button(text:string){const result=elements(tree).find(e=>e.type==="button"&&label(e.props.children).includes(text));if(!result)throw Error(`Missing button ${text}; ${label(tree)}`);return result;}
 async function flush(){for(let i=0;i<5;i++){await new Promise(resolve=>setTimeout(resolve,1));settle();}}
 settle();return {props,sdk,reads,sent,navigate,retention,render,settle,flush,button,get tree(){return tree;},get snapshot(){return view;},get legacyBody(){return slots[7]?.value;},seedLegacy:(body:unknown,receipt:unknown=null)=>{if(!legacyOwner)throw Error("Original owner fixture required");if(!slots[7]||!slots[8])throw Error("Original attempt/receipt slots absent");slots[7].value=body;slots[8].value=receipt;dirty=true;settle();},html:()=>renderToStaticMarkup(tree),complete:(p:RetestProjection,sid=sdk.session.id,ids:string[]=[],next:string|null=null)=>{view=native(p,sid,ids,next);generation++;dirty=true;settle();},revoke:()=>{view=null;generation++;dirty=true;},setSend:(fn:typeof send)=>{send=fn;},click:(text:string)=>{const b=button(text);expect(b.props.disabled).not.toBe(true);(b.props.onClick as ()=>void)();},approve:()=>{const box=elements(tree).find(e=>e.type==="input"&&e.props.type==="checkbox");if(!box)throw Error("No actual approval field");(box.props.onChange as (e:{target:{checked:boolean}})=>void)({target:{checked:true}});},unmount:()=>{life=false;for(const s of slots)s.cleanup?.();}};
}
beforeEach(()=>{counter=0;vi.stubGlobal("crypto",{subtle:webcrypto.subtle,randomUUID:()=>`88c47b3b-d1f7-43b5-bd88-${String(++counter).padStart(12,"0")}`});});
afterEach(()=>vi.unstubAllGlobals());
it("ACCESS consumer exposes explicit evidence action but never creates/approves or silently fetches private preview",()=>{const h=harness();expect(h.reads).toEqual([]);expect(h.sent).toEqual([]);expect(h.html()).not.toContain("PRIVATE");h.click("Review original retest evidence");expect(h.reads).toEqual([{projection:"PREVIEW"}]);expect(h.html()).not.toContain("PRIVATE");});
it("actual full preview renderer retains aligned prose/null/empty/zero/media references without file actions",()=>{const h=harness("PREVIEW"),html=h.html();expect(html).toContain("PRIVATE Exact\n title ");expect(html).toContain("Technical behavior");expect(html).toContain("API response");expect(html).toContain("GET /synthetic");expect(html).toContain("Not supplied");expect(html).toContain("Empty string");expect(html).toContain('&quot;value&quot;: 0');expect(html).toContain("One\n two");expect(html).toContain("Media references are not fetched or verified");expect(h.sent).toEqual([]);});
it("explicit checkbox hashes one immutable request; supported start uses reviewed outer N only and waits for explicit LINKS",async()=>{const h=harness("PREVIEW");h.approve();await h.flush();expect(h.sent).toEqual([]);h.click("Create reviewed retest run");await h.flush();expect(h.sent).toHaveLength(1);expect(h.sent[0]).toMatchObject({expectedNativeActorId:"n",request:{projectId:"p",sourceRunId:"run",testCaseId:"case",expectedScope:scope,expectedReviewHash:hash}});expect(Object.isFrozen(h.sent[0]?.request)).toBe(true);expect(h.navigate).toEqual([]);expect(h.reads).toEqual([]);expect(h.html()).toContain("verified receipt");expect(h.html()).not.toContain("retest_");
 h.click("Read current links for confirmed retest");expect(h.reads).toEqual([{projection:"LINKS"}]);const input=h.sent[0];if(!input)throw Error("Missing exact sent request");const target=`retest_${createHash("sha256").update(JSON.stringify(["p","n",input.request.idempotencyKey])).digest("hex")}`;h.complete("LINKS","A",[target]);h.click("Open verified retest run");expect(h.navigate).toEqual([`/projects/p/test-runs/manual/${target}`]);expect(h.retention.at(-1)).toBe(false);expect(h.sent).toHaveLength(1);
});
it("UNKNOWN closes/reopens and fresh FULL review retries identical body/UUID despite changed current nonce",async()=>{const h=harness("PREVIEW");h.setSend(async()=>{throw Error("PRIVATE PROVIDER TOKEN");});h.approve();await h.flush();h.click("Create reviewed retest run");await h.flush();const held=h.sent[0];expect(h.html()).toContain("UNKNOWN");expect(h.html()).not.toContain("PROVIDER TOKEN");h.props.open=false;h.settle();expect(h.html()).toBe("");h.props.open=true;h.settle();h.click("Read current FULL original evidence");h.complete("PREVIEW");h.click("Retry identical retest request");await h.flush();expect(h.sent).toHaveLength(2);expect(h.sent[1]).toBe(held);expect(h.navigate).toEqual([]);});
it("SDK loss before React commit blocks captured start handler without replacing held reviewed request",async()=>{const h=harness("PREVIEW");h.approve();await h.flush();const button=h.button("Create reviewed retest run");h.sdk.session.id="B";(button.props.onClick as ()=>void)();await h.flush();expect(h.sent).toEqual([]);expect(h.html()).not.toContain("PRIVATE Exact");h.sdk.session.id="A";h.revoke();h.settle();expect(h.html()).not.toContain("PRIVATE Exact");});
it("late matching ACK after close settles privately and fresh exact B LINKS can publish without replay",async()=>{const h=harness("PREVIEW");let resolve!:(v:unknown)=>void;h.setSend(input=>new Promise(r=>{resolve=v=>r(v);expect(input.expectedNativeActorId).toBe("n");}));h.approve();await h.flush();h.click("Create reviewed retest run");h.props.open=false;h.revoke();h.settle();const input=h.sent[0];if(!input)throw Error("No sent request");const target=`retest_${createHash("sha256").update(JSON.stringify(["p","n",input.request.idempotencyKey])).digest("hex")}`;resolve({testRunId:target,recovered:false,scope:{...scope,actorId:"n",sourceRunId:"run",testCaseId:"case",idempotencyKey:input.request.idempotencyKey,reviewHash:hash}});await h.flush();expect(h.navigate).toEqual([]);expect(h.html()).toBe("");h.props.open=true;h.sdk.session.id="B";h.complete("ACCESS","B");expect(h.html()).toContain("verified receipt");expect(h.html()).not.toContain(target);h.click("Read current links for confirmed retest");h.complete("LINKS","B",[target]);h.click("Open verified retest run");expect(h.sent).toHaveLength(1);expect(h.navigate).toHaveLength(1);});
it("explicit legacy handoff remains byte-for-byte opaque and blocks replacement even with current native FULL preview",()=>{const h=harness("PREVIEW"),bare={projectId:"p",sourceRunId:"run",testCaseId:"case",expectedReviewHash:hash,idempotencyKey:"88c47b3b-d1f7-43b5-bd88-b49ddf14b8c0"},body=JSON.stringify(bare);h.props.retainedLegacyAttempt=bare;h.settle();expect(h.html()).toContain("earlier retest request remains held unchanged");expect(h.html()).not.toContain("PRIVATE Exact");expect(h.html()).not.toContain(bare.idempotencyKey);expect(h.sent).toEqual([]);expect(h.reads).toEqual([]);expect(JSON.stringify(bare)).toBe(body);expect(Object.hasOwn(bare,"expectedScope")).toBe(false);});
it.each([false,true])("legacy owner %s explicit handoff stays held when caller removes or changes it; current N never migrates",legacyOwner=>{const h=harness("PREVIEW",false,legacyOwner),body={projectId:"p",sourceRunId:"run",testCaseId:"case",expectedReviewHash:hash,idempotencyKey:"88c47b3b-d1f7-43b5-bd88-b49ddf14b8c0",expectedScope:{...scope}};h.props.retainedLegacyAttempt=body;h.settle();expect(h.html()).toContain("earlier retest request");body.expectedScope.organizationId="foreign";h.props.retainedLegacyAttempt=null;h.settle();expect(h.html()).toContain("earlier retest request");expect(h.sent).toEqual([]);expect(h.reads).toEqual([]);h.props.open=false;h.settle();expect(h.html()).toBe("");h.props.open=true;h.settle();expect(h.html()).toContain("stored body stays withheld");});
it("actual legacy shell preserves original ordered hook/state prefix and never publishes empty false over child's ownership",()=>{
 const ast=ts.createSourceFile("ManualRetestWizard.tsx",source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),owner=ast.statements.find((s):s is ts.FunctionDeclaration=>ts.isFunctionDeclaration(s)&&s.name?.text==="ManualRetestWizard");if(!owner?.body)throw Error("Actual legacy owner absent");
 const names=owner.body.statements.filter(ts.isVariableStatement).flatMap(s=>[...s.declarationList.declarations]).filter(d=>d.initializer&&ts.isCallExpression(d.initializer)&&["trpcReact.useUtils","trpcReact.manualRetest.start.useMutation","useRetestAccess","useState","useRef"].includes(d.initializer.expression.getText(ast))).map(d=>ts.isArrayBindingPattern(d.name)?d.name.elements[0]?.getText(ast):d.name.getText(ast));
 expect(names.slice(0,16)).toEqual(["utils","mutation","access","accessNow","preview","attempt","receipt","busy","approved","error","ambiguous","rejected","refreshNotice","accessRejected","unknown","openNow"]);
 const h=harness("ACCESS",false,true);expect(h.retention).not.toContain(false);
});
it.each([false,true])("pre-existing legacy owner slots retain exact scoped/bare UNKNOWN and known=%s receipt without current-N inference",known=>{
 const h=harness("PREVIEW",false,true),body={idempotencyKey:"88c47b3b-d1f7-43b5-bd88-b49ddf14b8c0",expectedReviewHash:hash,testCaseId:"case",sourceRunId:"run",projectId:"p"},before=JSON.stringify(body);
 h.seedLegacy(body,known?{testRunId:"old-private-target",recovered:true,scope:{...scope,actorId:"M"}}:null);expect(h.legacyBody).toBe(body);expect(JSON.stringify(h.legacyBody)).toBe(before);expect(h.html()).toContain("earlier retest request");expect(h.html()).not.toContain("old-private-target");expect(h.sent).toEqual([]);expect(h.reads).toEqual([]);h.props.open=false;h.settle();h.props.open=true;h.settle();expect(h.legacyBody).toBe(body);expect(h.retention.at(-1)).toBe(true);expect(Object.hasOwn(body,"expectedScope")).toBe(false);
});
it("pre-layout parent close and reentrant SDK loss during retention callback block old creation before UUID/hash/send",async()=>{
 const h=harness("PREVIEW"),count=counter;h.props.onRetainedRequestChange=v=>{if(v)h.sdk.session.id="B";};h.settle();h.approve();await h.flush();expect(h.sent).toEqual([]);expect(counter).toBe(count);h.sdk.session.id="A";h.props.onRetainedRequestChange=()=>{};h.complete("PREVIEW");h.approve();await h.flush();const old=h.button("Create reviewed retest run");h.props.open=false;h.render(false);(old.props.onClick as ()=>void)();await h.flush();expect(h.sent).toEqual([]);expect(h.html()).toBe("");
});
it("current page lacking exact known target never offers navigation or claims global absence",async()=>{const h=harness("PREVIEW");h.approve();await h.flush();h.click("Create reviewed retest run");await h.flush();h.click("Read current links for confirmed retest");h.complete("LINKS","A",["another"]);expect(h.html()).toContain("have not verified the retained target");expect(h.html()).not.toContain("Open verified retest run");expect(h.retention.at(-1)).toBe(true);expect(h.navigate).toEqual([]);});
it("actual Actions does not silently query links; page navigation is explicit, scoped and stale callbacks cannot page",()=>{const h=harness("ACCESS",true);expect(h.reads).toEqual([]);h.click("Read current retest relationships");h.complete("LINKS","A",["one"],"one");const old=h.button("Next relationships");h.click("Next relationships");expect(h.reads.at(-1)).toEqual({projection:"LINKS",before:"one"});h.complete("LINKS","A",["two"]);h.click("Previous relationships");expect(h.reads.at(-1)).toEqual({projection:"LINKS"});h.complete("LINKS","A",["one"],"one");const count=h.reads.length;h.revoke();(old.props.onClick as ()=>void)();expect(h.reads).toHaveLength(count);h.settle();expect(h.html()).not.toContain("one</a>");});
it("actual consumer preserves metadata mount fix and has no legacy dispatch/private query or automatic cache invalidation",()=>{expect(source).toContain("refetchOnMount: false");expect(source).toContain("useRetestAccess(projectId,active,false,undefined,true)");expect(source).toContain("manualRetest.startReviewed.useMutation");for(const old of ["mutation.mutateAsync(request)","manualRetest.preview.fetch","manualRetest.links.useQuery","manualRetest.links.invalidate","caseExecutionHistory.list.invalidate","retainLegacySubmitted("])expect(source).not.toContain(old);});
