import type { qualityRiskAggregateCsvPlan } from "./quality-risk-aggregate-csv";
type AggregatePlan = ReturnType<typeof qualityRiskAggregateCsvPlan>;
const entities: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
};
const escape = (value: string | number) => {
  const text = String(value);
  if (
    /[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(text) ||
    /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/.test(
      text,
    )
  )
    throw Error(
      "Unsupported control or Unicode content prevents this portable aggregate export.",
    );
  return text.replace(/[&<>"']/g, (c) => entities[c]!);
};
const caption = (value: string | number) =>
  String(value)
    .replace(/_/g, " ")
    .toLowerCase()
    .replace(/^./, (c) => c.toUpperCase());
/** Offline, text-only read-time counts. No scripts, external assets or recipient grant. */
export function renderQualityRiskAggregateHtml(plan: AggregatePlan) {
  // The caller first validates complete category/count/scope consistency using
  // qualityRiskAggregateCsvPlan. No runtime module/DB imports are needed here.
  if (
    !plan ||
    plan.headers.length !== 4 ||
    plan.rows.length > 1000 ||
    plan.rows.some(
      (row) =>
        row.length !== 4 ||
        row.some(
          (cell) =>
            typeof cell !== "string" &&
            (typeof cell !== "number" ||
              !Number.isSafeInteger(cell) ||
              cell < 0),
        ),
    )
  )
    throw Error("Unsupported portable risk aggregate plan.");
  const populations = ["Full project population", "Filtered cohort"].map(
    (cohort) => {
      const rows = plan.rows.filter(
        (row) =>
          row[0] === cohort && row[1] === "Population" && row[2] === "Entries",
      );
      if (
        rows.length !== 1 ||
        typeof rows[0]![3] !== "number" ||
        rows[0]![3] > 1000
      )
        throw Error("Incomplete portable risk aggregate population.");
      return rows[0]![3];
    },
  );
  const observations = plan.rows.filter(
    (row) => row[0] === "Scope" && row[1] === "Observed UTC",
  );
  const observedAt = observations[0]?.[3];
  if (
    observations.length !== 1 ||
    typeof observedAt !== "string" ||
    !Number.isFinite(Date.parse(observedAt)) ||
    new Date(observedAt).toISOString() !== observedAt
  )
    throw Error("Incomplete portable risk aggregate observation.");
  const table = (rows: typeof plan.rows) =>
    `<div class="scroll"><table><thead><tr><th scope="col">Recorded dimension</th><th scope="col">Category or meaning</th><th scope="col">Value</th></tr></thead><tbody>${rows.map((row) => `<tr><th scope="row">${escape(caption(row[1]!))}</th><td>${escape(caption(row[2]!))}</td><td>${escape(row[3]!)}</td></tr>`).join("")}</tbody></table></div>`;
  const cohorts = ["Full project population", "Filtered cohort"];
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Human quality-risk overview | Vaettir</title><style>body{font:16px/1.5 system-ui;color:#182225;background:white;max-width:1000px;margin:36px auto;padding:0 20px}h1{line-height:1.15}p,li,td,th{overflow-wrap:anywhere}small{color:#52625c}.summary{display:flex;flex-wrap:wrap;gap:24px}.summary strong{font-size:28px;display:block}.boundary{padding:16px;border-left:4px solid #70957e;background:#edf3ee}.scroll{overflow:auto}table{border-collapse:collapse;width:100%}th,td{text-align:left;vertical-align:top;padding:9px;border-bottom:1px solid #c7d0ce}td:last-child{font-variant-numeric:tabular-nums}thead{display:table-header-group}tr{break-inside:avoid}section{margin-top:28px}@media print{body{margin:0;padding:0;max-width:none}.scroll{overflow:visible}th,td{padding:6px}}</style></head><body><header><small>VAETTIR · Read-time human risk aggregates · Format v1</small><h1>Human quality-risk overview</h1><p>Observed UTC: ${escape(observedAt)}. Current counts, not an approved frozen report.</p><div class="summary"><p><strong>${escape(populations[0]!)}</strong>Full project entries</p><p><strong>${escape(populations[1]!)}</strong>Filtered entries</p></div><p>Manual qualitative categories and ordinary recorded decisions. An empty register is not a finding of no risk.</p></header><section class="boundary"><h2>Review and sharing boundaries</h2><ul>${plan.rows
    .filter((row) => row[0] === "Evidence boundary")
    .map((row) => `<li>${escape(row[3]!)}</li>`)
    .join(
      "",
    )}</ul><p>Review recipient suitability before sharing this local file. It grants no access to Vaettir. Use your browser's Print command to prepare a PDF; no PDF or delivery has been generated by Vaettir.</p></section><section><h2>Applied scope</h2>${table(plan.rows.filter((row) => row[0] === "Scope"))}</section>${cohorts.map((cohort) => `<section><h2>${escape(cohort)}</h2>${table(plan.rows.filter((row) => row[0] === cohort))}</section>`).join("")}</body></html>`;
  if (new TextEncoder().encode(html).byteLength > 1024 * 1024)
    throw Error(
      "The complete portable aggregate report exceeds 1 MiB. Nothing was prepared.",
    );
  return html;
}
