import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { stepResourceRequestKey } from "@vaettir/api/src/services/manualStepExecutionResources";
import { StepResourceReader, decodeStepResource, retainedStepEvidence, stepResourceClientRequestKey, type StepResourceKind, type StepResourceInput, type StepResourceData, type StepResourceView } from "./step-execution-resource-reader";
import type { StepReviewOrigin } from "./step-execution-review-draft";
import type { StepReviewSession } from "./step-execution-review-completion";
const origin: StepReviewOrigin = { projectId: "p", testRunId: "r", testCaseId: "c", stepIndex: 0, organizationId: "o", clerkActorId: "cl", nativeActorId: "n" };
const scope = { projectId: "p", organizationId: "o", actorId: "n", actorClerkUserId: "cl" };
export function resourceInput(kind: StepResourceKind): StepResourceInput { return { projectId: "p", testRunId: "r", testCaseId: "c", stepIndex: 0, originalOrganizationId: "o", expectedClerkActorId: "cl", expectedNativeActorId: "n", readRequestId: randomUUID(), cursor: null, limit: 10, ...(kind === "EVIDENCE" ? { search: " literal " } : {}) }; }
export async function resourceResponse(kind: StepResourceKind, input: Readonly<StepResourceInput>): Promise<StepResourceData> {
  const base = { projectId: input.projectId, testRunId: input.testRunId, testCaseId: input.testCaseId, stepIndex: input.stepIndex, readRequestId: input.readRequestId, requestKey: await stepResourceClientRequestKey(kind, input), scope,
    procedureHash: "a".repeat(64), populationHash: "b".repeat(64), nextCursor: "next", provenance: "CURRENT_READER_AUTHORITY_HISTORICAL_ORIGINAL_TENANCY_UNRECORDED" as const,
    frozenStep: { order: input.stepIndex, action: " frozen action ", expectedActionOrData: " GET /synthetic ", expectedResult: "", expectedResponse: null, unknown: [0, false, null] } };
  return kind === "HISTORY" ? { ...base, totalRevisions: 2, revisions: [{ id: "revision", revisionNumber: 2, status: "PASS", note: null, observations: { unknown: [null, "", 0, false] }, evidenceAttachmentIds: ["file"], evidenceAttachments: [{ id: "file", fileName: " exact label ", verification: { versionId: "v1", unknown: "raw" } }], actorId: "historical-author", actorName: " Stored name ", recordedAt: "2026-10-05T20:00:00.123Z", correctionReason: "", previousRevisionId: null, versionProvenance: "STORED_REVISION_METADATA_NOT_FILE_IMMUTABILITY_PROOF" }] }
    : { ...base, totalCandidates: 2, search: "search" in input ? input.search : "", attachments: [{ id: "file", testCaseId: "c", fileName: " exact label ", contentType: "text/plain", sizeBytes: 10, uploadCompletedAt: "2026-10-05T20:00:00.123Z", uploadVerification: { etag: "etag", versionId: null, verifiedAt: "2026-10-05T20:00:00Z" }, versionId: null, versionProvenance: "UNVERSIONED_NOT_IMMUTABLE", selectable: true }] };
}
function harness(kind: StepResourceKind = "HISTORY", hash?: typeof stepResourceClientRequestKey) {
  let session: StepReviewSession = { userId: "cl", sessionId: "A" }, view: StepResourceView;
  const frame = { origin: origin as StepReviewOrigin | null, active: true, hookSession: session, expectedProcedureHash: "a".repeat(64) as string | null };
  const reader = new StepResourceReader(kind, next => { view = next; }, () => session, hash); reader.attach(); reader.bindFrame(frame);
  const sent: Readonly<StepResourceInput>[] = [];
  const read = async (input: Readonly<StepResourceInput>) => { sent.push(input); return resourceResponse(kind, input); };
  return { reader, frame, sent, read, get view() { return view; }, setSession(value: StepReviewSession, emit = true) { session = value; if (emit) reader.observeSession(value); }, bind() { reader.bindFrame(frame); return view; } };
}
describe("step resource browser-pure readers, synthetic wire only", () => {
  it.each(["HISTORY", "EVIDENCE"] as const)("%s request fingerprint equals native canonical contract without server runtime in production browser", async kind => { const input = resourceInput(kind); expect(await stepResourceClientRequestKey(kind, input)).toBe(stepResourceRequestKey(kind, input)); });
  it.each(["HISTORY", "EVIDENCE"] as const)("%s preserves exact raw metadata/NULL and frozen columns, not media bytes or historical tenancy", async kind => { const input = resourceInput(kind), raw = await resourceResponse(kind, input), data = decodeStepResource(kind, raw, input, raw.requestKey, raw.procedureHash, null); expect(data).toEqual(raw); expect(Object.isFrozen(data)).toBe(true); expect(Object.isFrozen(data.frozenStep)).toBe(true); expect(data.provenance).toContain("HISTORICAL_ORIGINAL_TENANCY_UNRECORDED"); if ("revisions" in data) expect(data.revisions[0]?.note).toBeNull(); else expect(data.attachments[0]?.versionProvenance).toBe("UNVERSIONED_NOT_IMMUTABLE"); });
  it.each(["nonce", "request", "procedure", "population", "native", "org", "Clerk", "coordinate"])("%s mismatch refuses complete resource view", async wrong => { const input = resourceInput("HISTORY"), raw = await resourceResponse("HISTORY", input); const patch = wrong === "nonce" ? { readRequestId: randomUUID() } : wrong === "request" ? { requestKey: "f".repeat(64) } : wrong === "procedure" ? { procedureHash: "f".repeat(64) } : wrong === "population" ? { populationHash: "f".repeat(64) } : wrong === "coordinate" ? { stepIndex: 1 } : { scope: { ...scope, ...(wrong === "native" ? { actorId: "other" } : wrong === "org" ? { organizationId: "other" } : { actorClerkUserId: "other" }) } }; expect(() => decodeStepResource("HISTORY", { ...raw, ...patch }, input, raw.requestKey, raw.procedureHash, raw.populationHash)).toThrow(); });
  it("strict wire timestamps/unsafe raw numbers/limit mismatch refuse, never default a date or truncate a page", async () => { const input = resourceInput("HISTORY"), raw = await resourceResponse("HISTORY", input); if (!("revisions" in raw)) throw Error("fixture kind"); for (const patch of [{ recordedAt: new Date("2026-10-05T20:00:00.123Z") }, { recordedAt: "2026-10-05T20:00:00.123456Z" }, { observations: { value: 9007199254740992 } }]) expect(() => decodeStepResource("HISTORY", { ...raw, revisions: [{ ...raw.revisions[0], ...patch }] }, input, raw.requestKey, raw.procedureHash, null)).toThrow(); const single = { ...input, limit: 1 }, key = await stepResourceClientRequestKey("HISTORY", single); expect(() => decodeStepResource("HISTORY", { ...raw, requestKey: key, revisions: [raw.revisions[0], { ...raw.revisions[0], id: "second", revisionNumber: 1 }] }, single, key, raw.procedureHash, null)).toThrow(); });
  it("missing current frozen procedure authority may ask the server but commits no private body", async () => { const h = harness(); h.frame.expectedProcedureHash = null; h.bind(); await h.reader.read(h.read); expect(h.sent).toHaveLength(1); expect(h.view.data).toBeNull(); expect(h.view.error).toContain("procedure authority"); h.frame.expectedProcedureHash = "a".repeat(64); h.bind(); await h.reader.read(h.read); expect(h.view.data).not.toBeNull(); expect(h.sent[1]?.readRequestId).not.toBe(h.sent[0]?.readRequestId); });
  it.each(["close", "SDK-A-B-A", "unmount", "native-frame"])("late private success after %s cannot republish a resource body", async loss => { const h = harness(); await h.reader.read(async input => { h.sent.push(input); if (loss === "close") { h.frame.active = false; h.bind(); } if (loss === "SDK-A-B-A") { h.setSession({ userId: "cl", sessionId: "B" }); h.setSession({ userId: "cl", sessionId: "A" }); } if (loss === "unmount") h.reader.detach(); if (loss === "native-frame") { h.frame.origin = { ...origin, nativeActorId: "other" }; h.bind(); } return resourceResponse("HISTORY", input); }); expect(h.reader.snapshot().data).toBeNull(); expect(h.reader.snapshot().error).toBe(""); });
  it("SDK loss during hash prevents dispatch and stale errors stay private across restored SDK", async () => { let release: ((value: string) => void) | undefined; const h = harness("HISTORY", () => new Promise(resolve => { release = resolve; })); const task = h.reader.read(h.read); h.setSession({ userId: "cl", sessionId: "B" }); h.setSession({ userId: "cl", sessionId: "A" }); release!("a".repeat(64)); await task; expect(h.sent).toHaveLength(0); expect(h.reader.snapshot().data).toBeNull(); const late = harness(); await late.reader.read(async () => { late.setSession({ userId: "cl", sessionId: "B" }); late.setSession({ userId: "cl", sessionId: "A" }); throw Error("private error"); }); expect(late.reader.snapshot().error).toBe(""); });
  it("Next requires the exact fresh population/procedure; mismatch hides previous body without fallback", async () => { const h = harness(); await h.reader.read(h.read); expect(h.view.data).not.toBeNull(); const epoch = h.view.epoch; await h.reader.next(epoch, async input => ({ ...(await resourceResponse("HISTORY", input)), populationHash: "c".repeat(64) })); expect(h.view.data).toBeNull(); expect(h.view.error).not.toBe(""); await h.reader.refresh(h.view.epoch, h.read); expect(h.view.data).not.toBeNull(); expect(h.sent.at(-1)?.cursor).toBeNull(); });
  it("error/over-limit views remain filterable; same-tick stale filter handlers cannot overwrite a newer intent", async () => { const h = harness("EVIDENCE"); await h.reader.read(async () => { throw Error("native candidate bound"); }); const epoch = h.view.epoch; const filtering = h.reader.setSearch(" literal spaces ", epoch, h.read); const stale = h.reader.setLimit(1, epoch, h.read); await Promise.all([filtering, stale]); expect(h.view.intent).toMatchObject({ search: " literal spaces ", limit: 25 }); expect(h.sent.at(-1)).toMatchObject({ search: " literal spaces ", limit: 25 }); expect(h.view.data).not.toBeNull(); });
  it("Refresh while a Next read is busy cannot relabel its frozen cursor or clear population binding", async () => { const h = harness(); await h.reader.read(h.read); let finish: ((value: unknown) => void) | undefined, entered: (() => void) | undefined; const dispatched = new Promise<void>(resolve => { entered = resolve; }); let pending: Readonly<StepResourceInput> | undefined; const next = h.reader.next(h.view.epoch, input => new Promise(resolve => { pending = input; finish = resolve; entered!(); })); await dispatched; expect(h.view.intent?.cursor).toBe("next"); await h.reader.refresh(h.view.epoch, h.read); expect(h.view.intent?.cursor).toBe("next"); finish!(await resourceResponse("HISTORY", pending!)); await next; expect(h.view.data).not.toBeNull(); expect(h.sent).toHaveLength(1); expect(h.view.intent?.cursor).toBe("next"); });
  it("collapse/restoration and step changes create fresh reads without rebinding original native actor or editor data", async () => { const h = harness(); await h.reader.read(h.read); const editor = { note: null, selected: ["file", "unavailable"] }, retained = structuredClone(editor); h.frame.active = false; h.bind(); expect(h.view.data).toBeNull(); expect(h.view.intent).toBeNull(); h.frame.active = true; h.bind(); expect(h.view.data).toBeNull(); await h.reader.read(h.read); h.frame.origin = { ...origin, stepIndex: 1 }; h.bind(); expect(h.view.data).toBeNull(); await h.reader.read(h.read); expect(h.sent.at(-1)).toMatchObject({ stepIndex: 1, expectedNativeActorId: "n", expectedClerkActorId: "cl", originalOrganizationId: "o", cursor: null }); expect(editor).toEqual(retained); h.frame.origin = { ...origin, nativeActorId: "other" }; h.bind(); await h.reader.read(h.read); expect(h.sent).toHaveLength(3); });
  it("render-intent revocation blocks old handlers before effect commit; stale frame checks cannot revoke a newer view", async () => { const h = harness(); h.reader.renderView(h.frame); h.bind(); await h.reader.read(h.read); const old = h.view.epoch, oldFrame = { ...h.frame }; const next = { ...h.frame, origin: { ...origin, stepIndex: 1 } }; expect(h.reader.renderView(next).data).toBeNull(); await h.reader.refresh(old, h.read); expect(h.sent).toHaveLength(1); h.frame.origin = next.origin; h.bind(); await h.reader.read(h.read); expect(h.reader.matchesFrame(oldFrame)).toBe(false); expect(h.reader.snapshot().data?.stepIndex).toBe(1); });
  it("unavailable or duplicate selected evidence IDs are not removed by current-page metadata", async () => { const input = resourceInput("EVIDENCE"), fresh = await resourceResponse("EVIDENCE", input); if (!("attachments" in fresh)) throw Error("fixture kind"); const selected = ["missing", "file", "file"], retained = retainedStepEvidence(selected, fresh); expect(retained.map(item => item.id)).toEqual(selected); expect(retained[0]).toMatchObject({ availableInPage: false, file: null }); expect(retained[1]?.label).toBe(" exact label "); expect(retainedStepEvidence(selected, null).map(item => item.id)).toEqual(selected); });
  it("current-data actions recheck SDK/frame/epoch and exact DTO identity before invoking the parent", async () => { const h = harness(); await h.reader.read(h.read); const { epoch, data } = h.view; let calls = 0; const action = () => { calls++; return true; }; expect(h.reader.currentData(epoch, data, action)).toBe(true); expect(h.reader.currentData(epoch, data ? structuredClone(data) : null, action)).toBe(false); h.setSession({ userId: "cl", sessionId: "B" }, false); expect(h.reader.currentData(epoch, data, action)).toBe(false); h.setSession({ userId: "cl", sessionId: "A" }); expect(h.reader.currentData(epoch, data, action)).toBe(false); h.bind(); await h.reader.read(h.read); expect(h.reader.currentData(h.view.epoch, h.view.data, action)).toBe(true); expect(calls).toBe(2); });
});
