import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { reviewedStepWriteKey } from "@vaettir/api/src/services/manualStepExecutionReviewSchema";
import { assertStepReviewAck, decodeStepReviewWire, freezeStepReviewInput, makeStepReviewDraft, parseStepReviewDecimal, stepReviewMeasurements, stepReviewRequestHash, type StepReviewBuffer } from "./step-execution-review-draft";
const scope = { projectId: "p", organizationId: "o", actorId: "n", actorClerkUserId: "cl" };
const origin = { projectId: "p", testRunId: "r", testCaseId: "c", stepIndex: 0, organizationId: "o", nativeActorId: "n", clerkActorId: "cl" };
function wire() { return { projectId: "p", testRunId: "r", testCaseId: "c", stepIndex: 0, readRequestId: randomUUID(), scope, canRecover: true, canRecord: true, supported: true, blockedReason: null, frozenDefinition: { testCaseId: "c", title: "Original", steps: [{ order: 0, action: " Click ", expectedActionOrData: " GET /synthetic ", expectedResult: "", expectedResponse: null, mediaAttachmentIds: [] }] }, current: null, rawCurrent: null, procedureHash: "a".repeat(64), currentFingerprint: "b".repeat(64), provenance: "CURRENT_AUTHORITY_LEGACY_ORIGINAL_TENANCY_UNRECORDED" as const }; }
function buffer(): StepReviewBuffer { return { status: "PASS", note: " \n exact ", context: { specimen: " sample ", hardwareRevision: "", firmwareVersion: "", environment: " retained " }, readings: [{ name: " Voltage ", value: "0", unit: " V ", lowerLimit: "0", upperLimit: "2", instrument: " CAL-1 " }], evidenceAttachmentIds: [], correctionReason: null }; }
describe("step review lossless wire/draft helpers, pure source proof only", () => {
  it("accepts actual JSON timestamp string without parsing the server Date schema", () => { const value = wire(); const current = { id: "old", status: "PASS", note: null, observations: { ...buffer().context, measurements: [] }, evidenceAttachments: [], actorName: "Synthetic", recordedAt: new Date("2026-10-05T20:00:00.123Z"), correctionReason: null, previousRevisionId: null, revisionNumber: 1 }; const json = JSON.parse(JSON.stringify({ ...value, current, rawCurrent: current })); expect(decodeStepReviewWire(json).current?.recordedAt).toBe("2026-10-05T20:00:00.123Z"); expect(() => decodeStepReviewWire({ ...value, current, rawCurrent: current })).toThrow(/wire value/); });
  it.each(["2026-10-05T20:00:00Z", "2026-10-05T20:00:00.123456Z", "2026-10-05T13:00:00.123-07:00", "invalid"])("refuses unsupported timestamp %s without defaulting", recordedAt => { const current = { id: "old", status: "PASS", note: null, observations: { ...buffer().context, measurements: [] }, evidenceAttachments: [], actorName: "Synthetic", recordedAt, correctionReason: null, previousRevisionId: null, revisionNumber: 1 }; expect(() => decodeStepReviewWire({ ...wire(), current, rawCurrent: current })).toThrow(); });
  it("unsupported current authority cannot expose retained body or invent canRecord", () => { expect(() => decodeStepReviewWire({ ...wire(), supported: false })).toThrow(/consistently/); const value = decodeStepReviewWire({ ...wire(), supported: false, canRecord: false, frozenDefinition: null, procedureHash: null, currentFingerprint: null }); expect(value.canRecover).toBe(true); expect(value.frozenDefinition).toBeNull(); });
  it.each(["0", "0.10", "1e3", ".5", "+2", " 75.00 "])("admits an exactly representable conventional decimal %s", text => expect(parseStepReviewDecimal(text)).toBe(Number(text)));
  it.each(["0x10", "Infinity", "NaN", "", "9007199254740993", "0.10000000000000001", "1e-999", "-0"])("refuses unsupported decimal %s and leaves text outside the parser unchanged", text => expect(() => parseStepReviewDecimal(text)).toThrow());
  it("preserves measured prose, optional limit absence, null/empty distinction and raw buffers", () => { const entered = buffer(), value = wire(), draft = makeStepReviewDraft(origin, decodeStepReviewWire(value), "A", entered, randomUUID()); entered.note = "changed"; entered.readings[0]!.value = "99"; const input = freezeStepReviewInput(draft, randomUUID()); expect(input.note).toBe(" \n exact "); expect(input.observations.specimen).toBe(" sample "); expect(input.observations.measurements[0]).toMatchObject({ name: " Voltage ", value: 0, unit: " V ", instrument: " CAL-1 " }); expect(draft.buffer.readings[0]!.value).toBe("0"); expect(Object.isFrozen(draft.buffer.readings)).toBe(true); for (const note of [null, ""]) expect(freezeStepReviewInput(makeStepReviewDraft(origin, decodeStepReviewWire(value), "A", { ...buffer(), note }, randomUUID()), randomUUID()).note).toBe(note); expect(stepReviewMeasurements([{ ...buffer().readings[0]!, lowerLimit: "", upperLimit: "" }], "PASS")[0]).not.toHaveProperty("lowerLimit"); });
  it("hashes the exact same full serialization as native outer receipt and validates all coordinates", async () => { const draft = makeStepReviewDraft(origin, decodeStepReviewWire(wire()), "A", buffer(), randomUUID()), input = freezeStepReviewInput(draft, randomUUID()), requestHash = await stepReviewRequestHash(input); const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(reviewedStepWriteKey(input))); expect(requestHash).toBe(Array.from(new Uint8Array(digest), b => b.toString(16).padStart(2, "0")).join("")); const pending = { input, requestHash, draft, everAmbiguous: false }; const ack = { projectId: "p", testRunId: "r", testCaseId: "c", stepIndex: 0, scope, idempotencyKey: input.idempotencyKey, requestHash, revisionId: "new", caseStatus: null, recovered: false, provenance: "REVIEWED_REQUEST_BOUND_AT_WRITE" }; expect(assertStepReviewAck(ack, pending).revisionId).toBe("new"); for (const change of [{ testRunId: "other" }, { testCaseId: "other" }, { stepIndex: 1 }, { requestHash: "f".repeat(64) }, { idempotencyKey: randomUUID() }, { scope: { ...scope, actorId: "other" } }]) expect(() => assertStepReviewAck({ ...ack, ...change }, pending)).toThrow(); });
});
