import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { StepReviewCompletionController, type StepReviewCompletionView, type StepReviewSession } from "./step-execution-review-completion";
import { decodeStepReviewWire, stepReviewRequestHash, type StepReviewBuffer } from "./step-execution-review-draft";
import type { ReviewedStepWriteInput } from "@vaettir/api/src/services/manualStepExecutionReviewSchema";
const scope = { projectId: "p", organizationId: "o", actorId: "n", actorClerkUserId: "cl" };
const buffer = (): StepReviewBuffer => ({ status: "PASS", note: " exact ", context: { specimen: "", hardwareRevision: "", firmwareVersion: "", environment: "" }, readings: [{ name: "Voltage", value: "0", unit: "V", lowerLimit: "", upperLimit: "", instrument: "" }], evidenceAttachmentIds: [], correctionReason: null });
function harness(hash?: (input: Readonly<ReviewedStepWriteInput>) => Promise<string>) {
  let session: StepReviewSession = { userId: "cl", sessionId: "A" }, view: StepReviewCompletionView;
  let publishEffect: ((view: StepReviewCompletionView) => void) | undefined;
  const initial = { projectId: "p", testRunId: "r", testCaseId: "c", stepIndex: 0, readRequestId: randomUUID(), scope, canRecover: true, canRecord: true, supported: true, blockedReason: null, frozenDefinition: { testCaseId: "c", steps: [{ order: 0, action: "Original" }, { order: 1, action: "Next" }] }, current: null, rawCurrent: null, procedureHash: "a".repeat(64), currentFingerprint: "b".repeat(64), provenance: "CURRENT_AUTHORITY_LEGACY_ORIGINAL_TENANCY_UNRECORDED" };
  let fresh = decodeStepReviewWire(initial), visible = true, readOnly = false;
  const controller = new StepReviewCompletionController({ projectId: "p", testRunId: "r", testCaseId: "c" }, next => { view = next; publishEffect?.(next); }, () => session, hash);
  controller.attach();
  function bind() { controller.bindFrame({ visible, readOnly, activation: fresh.readRequestId, observedSessionId: session?.sessionId ?? null, observedSdkGeneration: controller.sessionGeneration(), fresh }); return view; }
  bind();
  function prepare() { controller.change(buffer(), view.epoch, view.draft?.identity ?? null); controller.reviewCurrent(view.epoch, view.draft!.identity); }
  const sent: Readonly<ReviewedStepWriteInput>[] = [], counts = { callbacks: 0, pending: [] as boolean[] };
  async function record(input: Readonly<ReviewedStepWriteInput>) { sent.push(input); return { projectId: input.projectId, testRunId: input.testRunId, testCaseId: input.testCaseId, stepIndex: input.stepIndex, scope, idempotencyKey: input.idempotencyKey, requestHash: await stepReviewRequestHash(input), revisionId: "new", caseStatus: null, recovered: false, provenance: "REVIEWED_REQUEST_BOUND_AT_WRITE" }; }
  const submit = (sender = record) => controller.submit(view.epoch, sender, () => { counts.callbacks++; }, value => counts.pending.push(value));
  return { controller, prepare, record, sent, counts, submit, bind, onPublish(effect: (view: StepReviewCompletionView) => void) { publishEffect = effect; }, get view() { return view; }, get fresh() { return fresh; }, setFresh(value: Record<string, unknown>) { fresh = decodeStepReviewWire(value); }, setSession(value: StepReviewSession, emit = false) { session = value; if (emit) controller.observeSession(value); }, setVisible(value: boolean) { visible = value; bind(); }, setReadOnly(value: boolean) { readOnly = value; bind(); } };
}
describe("actual step completion class synthetic workflow, not native/browser proof", () => {
  it("parent callback loss revokes authority synchronously and A-B-A requires a fresh own/native activation, never a replaced draft", () => {
    const h = harness(); let current = true;
    const frame = { visible: true, readOnly: false, activation: h.fresh.readRequestId, observedSessionId: "A", observedSdkGeneration: h.controller.sessionGeneration(), fresh: h.fresh, parentCurrent: () => current, parentActivation: "parentA" };
    h.controller.bindFrame(frame); h.prepare(); const original = h.view.draft, epoch = h.view.epoch;
    current = false; expect(h.controller.renderView(frame).draft).toBeNull(); expect(h.controller.reviewCurrent(epoch, original!.identity)).toBe(false);
    current = true; h.controller.bindFrame(frame); expect(h.view.readable).toBe(false);
    const fresh = decodeStepReviewWire({ ...h.fresh, readRequestId: randomUUID() }); h.controller.bindFrame({ ...frame, activation: fresh.readRequestId, fresh, parentActivation: "parentB" });
    expect(h.view.draft).toBe(original); expect(h.view.readable).toBe(true);
  });
  it("parent loss during request hash dispatches nothing, keeping exact entered buffers and UUIDs private", async () => {
    let release!: (value: string) => void, current = true; const h = harness(() => new Promise(resolve => { release = resolve; }));
    const frame = { visible: true, readOnly: false, activation: h.fresh.readRequestId, observedSessionId: "A", observedSdkGeneration: h.controller.sessionGeneration(), fresh: h.fresh, parentCurrent: () => current, parentActivation: "parentA" };
    h.controller.bindFrame(frame); h.prepare(); const draft = h.view.draft!; const pending = h.submit(); current = false; release("a".repeat(64)); await pending;
    expect(h.sent).toHaveLength(0); expect(h.view.hasPending).toBe(false); expect(h.view.draft).toBeNull();
    current = true; const fresh = decodeStepReviewWire({ ...h.fresh, readRequestId: randomUUID() }); h.controller.bindFrame({ ...frame, activation: fresh.readRequestId, fresh, parentActivation: "parentB" });
    expect(h.view.draft?.buffer).toEqual(draft.buffer);
  });
  it.each([null, () => false, () => { throw Error("PRIVATE_PARENT_MARKER"); }])("explicit unavailable parent cannot render/edit while native preview alone succeeds", parentCurrent => {
    const h = harness(); h.controller.bindFrame({ visible: true, readOnly: false, activation: h.fresh.readRequestId, observedSessionId: "A", observedSdkGeneration: h.controller.sessionGeneration(), fresh: h.fresh, parentCurrent, parentActivation: "parentA" });
    expect(h.view.readable).toBe(false); expect(h.view.canEdit).toBe(false); expect(h.view.canSave).toBe(false); expect(h.view.notice).not.toContain("PRIVATE_PARENT_MARKER");
  });
  it("a posted fresh frame cannot commit after SDK A-B-A between render and layout", () => {
    const h = harness(); h.prepare(); const retained = h.view.draft;
    const posted = { visible: true, readOnly: false, activation: randomUUID(), observedSessionId: "A", observedSdkGeneration: h.controller.sessionGeneration(), fresh: h.fresh };
    const fresh = decodeStepReviewWire({ ...posted.fresh, readRequestId: posted.activation });
    h.setSession({ userId: "cl", sessionId: "B" }, true); h.setSession({ userId: "cl", sessionId: "A" }, true);
    h.controller.bindFrame({ ...posted, fresh });
    expect(h.view.readable).toBe(false); expect(h.view.draft).toBeNull(); expect(h.view.canSave).toBe(false);
    h.setFresh({ ...fresh, readRequestId: randomUUID() }); h.bind(); expect(h.view.draft).toBe(retained);
  });
  it("known-receipt synchronization rechecks SDK after publishing busy, before any parent callback", async () => {
    const h = harness(); h.prepare(); await h.submit();
    const ack = h.view.acknowledgement; let armed = true;
    h.onPublish(view => { if (armed && view.busy) { armed = false; h.setSession({ userId: "cl", sessionId: "B" }); } });
    await h.controller.synchronizeAcknowledged(h.view.epoch, () => { h.counts.callbacks++; });
    expect(h.counts.callbacks).toBe(1); expect(h.sent).toHaveLength(1); expect(h.view.acknowledgement).toBeNull();
    h.setSession({ userId: "cl", sessionId: "A" }); h.setFresh({ ...h.fresh, readRequestId: randomUUID() }); h.bind();
    expect(h.view.acknowledgement).toBe(ack); expect(h.view.hasPending).toBe(false);
  });
  it("requires explicit review, synchronously owns busy and sends one immutable request despite same-tick submits", async () => { const h = harness(); h.controller.change(buffer(), h.view.epoch, null); expect(h.view.canSave).toBe(false); h.controller.reviewCurrent(h.view.epoch, h.view.draft!.identity); await Promise.all([h.submit(), h.submit()]); expect(h.sent).toHaveLength(1); expect(Object.isFrozen(h.sent[0])).toBe(true); expect(Object.isFrozen(h.sent[0]!.observations.measurements)).toBe(true); expect(h.counts).toEqual({ callbacks: 1, pending: [true, false] }); expect(h.view.acknowledgement?.revisionId).toBe("new"); await h.submit(); expect(h.sent).toHaveLength(1); });
  it.each(["close", "readOnly", "SDK", "listener-A-B-A", "unmount"])("matching late ACK after %s settles only privately, not old visible callbacks", async loss => { const h = harness(); h.prepare(); const original = h.view.draft; await h.submit(async input => { if (loss === "close") h.setVisible(false); if (loss === "readOnly") h.setReadOnly(true); if (loss === "SDK") h.setSession({ userId: "cl", sessionId: "B" }); if (loss === "listener-A-B-A") { h.setSession({ userId: "cl", sessionId: "B" }, true); h.setSession({ userId: "cl", sessionId: "A" }, true); } if (loss === "unmount") h.controller.detach(); return h.record(input); }); expect(h.counts.callbacks).toBe(0); expect(h.view.hasPending).toBe(false); expect(h.controller.snapshot().canSave).toBe(false); if (loss === "readOnly") { expect(h.view.draft).toBe(original); expect(h.view.canEdit).toBe(false); } else expect(h.view.draft).toBeNull(); });
  it("all response kinds latch SDK loss before React commit; returning SDK A cannot revive old native read", async () => { for (const kind of ["ACK", "rejected", "malformed"]) { const h = harness(); h.prepare(); await h.submit(async input => { h.setSession({ userId: "cl", sessionId: "B" }); if (kind === "rejected") throw { data: { code: "FORBIDDEN" } }; const ack = await h.record(input); return kind === "malformed" ? { ...ack, requestHash: "f".repeat(64) } : ack; }); h.setSession({ userId: "cl", sessionId: "A" }); h.bind(); expect(h.view.authorityReadable).toBe(false); expect(h.view.canSave).toBe(false); expect(h.view.notice).toBe(""); expect(h.counts.callbacks).toBe(0); if (kind !== "ACK") expect(h.view.hasPending).toBe(true); } });
  it("unknown request preserves UUID/body through unsupported later preview and authoritative refusal", async () => { const h = harness(); h.prepare(); const sent: Readonly<ReviewedStepWriteInput>[] = []; await h.submit(async input => { sent.push(input); throw Error("unknown"); }); const key = h.view.pendingKey; h.setFresh({ ...h.fresh, readRequestId: randomUUID(), supported: false, canRecord: false, frozenDefinition: null, current: null, rawCurrent: null, procedureHash: null, currentFingerprint: null }); h.bind(); expect(h.view.draft).toBeNull(); expect(h.view.canSave).toBe(true); await h.submit(async input => { sent.push(input); throw { data: { code: "CONFLICT" } }; }); expect(h.view.pendingKey).toBe(key); expect(sent[1]).toBe(sent[0]); await h.submit(async input => { sent.push(input); return h.record(input); }); expect(sent[2]).toBe(sent[0]); expect(h.view.hasPending).toBe(false); expect(h.counts.callbacks).toBe(0); });
  it("first proven rejection allows explicit current rereview; malformed ACK does not", async () => { const h = harness(); h.prepare(); await h.submit(async () => { throw { data: { code: "BAD_REQUEST" } }; }); expect(h.view.hasPending).toBe(false); expect(h.view.canEdit).toBe(true); const m = harness(); m.prepare(); await m.submit(async input => ({ ...(await m.record(input)), revisionId: "", requestHash: "f".repeat(64) })); expect(m.view.hasPending).toBe(true); expect(m.view.canEdit).toBe(false); });
  it("stale draft/epoch handlers cannot overwrite same-tick choice or discard current draft", () => { const h = harness(), old = h.view; h.controller.change(buffer(), old.epoch, null); const current = h.view.draft; expect(h.controller.change({ ...buffer(), note: "lost" }, old.epoch, null)).toBe(false); expect(h.view.draft).toBe(current); h.setReadOnly(true); h.setReadOnly(false); expect(h.controller.discardUnsaved(old.epoch, current!.identity)).toBe(false); expect(h.view.draft).toBe(current); });
  it("native baseline change never silently replaces raw entered buffer; explicit review binds current hashes", () => { const h = harness(); h.prepare(); const original = h.view.draft!; h.setFresh({ ...h.fresh, readRequestId: randomUUID(), currentFingerprint: "c".repeat(64) }); h.bind(); expect(h.view.baselineChanged).toBe(true); expect(h.view.canSave).toBe(false); expect(h.view.draft?.buffer.note).toBe(" exact "); h.controller.change({ ...buffer(), note: " retained amended " }, h.view.epoch, original.identity); expect(h.view.draft?.currentFingerprint).toBe(original.currentFingerprint); h.controller.reviewCurrent(h.view.epoch, h.view.draft!.identity); expect(h.view.draft?.currentFingerprint).toBe("c".repeat(64)); expect(h.view.draft?.buffer.note).toBe(" retained amended "); });
  it("hash await cannot dispatch after SDK loss or let callbacks replace request body", async () => { let release: ((value: string) => void) | undefined; const h = harness(() => new Promise(resolve => { release = resolve; })); h.prepare(); const held = h.view.draft!; const sending = h.submit(); expect(h.view.busy).toBe(true); expect(h.controller.change({ ...buffer(), note: "wrong" }, h.view.epoch, held.identity)).toBe(false); h.setSession({ userId: "cl", sessionId: "B" }, true); release!("a".repeat(64)); await sending; expect(h.sent).toEqual([]); h.setSession({ userId: "cl", sessionId: "A" }); h.bind(); expect(h.view.readable).toBe(false); expect(h.view.hasPending).toBe(false); });
  it("genuine new native activation restores same original scope for explicit receipt synchronization only", async () => { const h = harness(); h.prepare(); await h.submit(async input => { h.setSession({ userId: "cl", sessionId: "B" }, true); return h.record(input); }); h.setSession({ userId: "cl", sessionId: "A" }); h.setFresh({ ...h.fresh, readRequestId: randomUUID() }); h.bind(); expect(h.view.acknowledgement?.revisionId).toBe("new"); expect(h.view.canSave).toBe(false); await h.controller.synchronizeAcknowledged(h.view.epoch, () => { h.counts.callbacks++; }); expect(h.counts.callbacks).toBe(1); expect(h.sent).toHaveLength(1); });
  it("renewed same-native session requires explicit fresh review for an unsent buffer", async () => { const h = harness(); h.prepare(); const retained = h.view.draft!; h.setSession({ userId: "cl", sessionId: "B" }, true); h.setFresh({ ...h.fresh, readRequestId: randomUUID() }); h.bind(); expect(h.view.draft).toBe(retained); expect(h.view.reviewed).toBe(false); expect(h.view.canSave).toBe(false); await h.submit(); expect(h.sent).toHaveLength(0); h.controller.reviewCurrent(h.view.epoch, retained.identity); expect(h.view.reviewed).toBe(true); expect(h.view.draft?.reviewedSessionId).toBe("B"); expect(h.view.draft?.origin).toEqual(retained.origin); expect(h.view.draft?.buffer).toEqual(retained.buffer); await h.submit(); expect(h.sent).toHaveLength(1); });
  it("renewed same-native session retries submitted unknown body unchanged, without rewriting its review session", async () => { const h = harness(); h.prepare(); await h.submit(async input => { h.sent.push(input); throw Error("unknown"); }); const retained = h.view.draft!, input = h.sent[0]; h.setSession({ userId: "cl", sessionId: "B" }, true); h.setFresh({ ...h.fresh, readRequestId: randomUUID() }); h.bind(); expect(h.view.canSave).toBe(true); expect(h.view.canReview).toBe(false); expect(h.view.draft).toBe(retained); expect(h.view.draft?.reviewedSessionId).toBe("A"); await h.submit(); expect(h.sent[1]).toBe(input); expect(h.counts.callbacks).toBe(1); });
  it("session loss in the pre-dispatch callback does not strand an unsent request as unknown", async () => { const h = harness(); h.prepare(); await h.controller.submit(h.view.epoch, h.record, undefined, () => { h.setSession({ userId: "cl", sessionId: "B" }, true); }); expect(h.sent).toHaveLength(0); expect(h.view.hasPending).toBe(false); h.setFresh({ ...h.fresh, readRequestId: randomUUID() }); h.bind(); expect(h.view.canReview).toBe(true); expect(h.view.canSave).toBe(false); expect(h.view.draft?.buffer.note).toBe(" exact "); });
  it("other native actor or another step cannot reveal original retained receipt or draft", async () => { const h = harness(); h.prepare(); await h.submit(async () => { throw Error("unknown"); }); h.setFresh({ ...h.fresh, readRequestId: randomUUID(), stepIndex: 1 }); h.bind(); expect(h.view.draft).toBeNull(); expect(h.view.pendingKey).toBeNull(); expect(h.view.canSave).toBe(false); h.setFresh({ ...h.fresh, readRequestId: randomUUID(), scope: { ...scope, actorId: "replacement" } }); h.bind(); expect(h.view.authorityReadable).toBe(false); expect(h.view.hasPending).toBe(true); });
});
