import { readFileSync } from "node:fs";
import vm from "node:vm";
import ts from "typescript";
import React, { type ReactNode, isValidElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { currentSessionScope } from "./auth-query-cache";
import { StepResourceReader, retainedStepEvidence, stepResourceClientRequestKey, type StepResourceInput } from "./step-execution-resource-reader";
import type { StepObservationResourcesProps } from "../components/StepObservationResources";

const code = ["./use-step-execution-resources.ts", "../components/StepObservationResources.tsx"].map(name => {
  const source = readFileSync(new URL(name, import.meta.url), "utf8"), ast = ts.createSourceFile(name, source, ts.ScriptTarget.Latest, true, name.endsWith("tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS);
  return ast.statements.filter(node => ts.isFunctionDeclaration(node) || ts.isClassDeclaration(node) || ts.isVariableStatement(node) && node.declarationList.declarations.some(declaration => ts.isIdentifier(declaration.name) && declaration.name.text === "text")).map(node => ts.createPrinter().printNode(ts.EmitHint.Unspecified, node, ast).replace(/\bexport\s+/, "")).join("\n");
}).join("\n");
const executable = ts.transpileModule(code + "\nthis.component=StepObservationResources;", { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.None, jsx: ts.JsxEmit.React } }).outputText;
function expanded(node: ReactNode): ReactNode[] {
  if (Array.isArray(node)) return node.flatMap(expanded);
  if (!isValidElement<Record<string, unknown>>(node)) return [node];
  if (typeof node.type === "function") { const pure = node.type as (props: Record<string, unknown>) => ReactNode; return expanded(pure(node.props)); }
  return [node, ...expanded(node.props.children as ReactNode)];
}
function find(tree: ReactNode, type: string, words: string) {
  const node = expanded(tree).find(entry => isValidElement<Record<string, unknown>>(entry) && entry.type === type && renderToStaticMarkup(entry).includes(words));
  if (!isValidElement<Record<string, unknown>>(node)) throw Error(`Missing rendered ${type}: ${words}`); return node;
}
function click(tree: ReactNode, words: string) { const node = find(tree, "button", words), handler = node.props.onClick; if (typeof handler !== "function") throw Error("Missing actual handler"); handler(); }
function change(tree: ReactNode, type: string, words: string, value: string | boolean) { const node = find(tree, type, words), handler = node.props.onChange; if (typeof handler !== "function") throw Error("Missing actual change handler"); handler({ target: typeof value === "boolean" ? { checked: value } : { value } }); }

function harness() {
  const hooks: unknown[] = [], effects: Array<() => void> = [], cleanups = new Map<number, () => void>(), listeners = new Set<() => void>();
  const auth = { isLoaded: true, isSignedIn: true, userId: "cl", sessionId: "A" }, sdk = { loaded: true, session: { id: "A", user: { id: "cl" } } as null | { id: string; user: { id: string } }, addListener: (callback: () => void) => { listeners.add(callback); callback(); return () => { listeners.delete(callback); }; } };
  const calls = { history: [] as Readonly<StepResourceInput>[], evidence: [] as Readonly<StepResourceInput>[], toggles: [] as Array<[string, boolean]>, open: [] as unknown[] };
  const props: StepObservationResourcesProps = { origin: { projectId: "p", testRunId: "r", testCaseId: "c", stepIndex: 0, organizationId: "o", clerkActorId: "cl", nativeActorId: "n" }, expectedProcedureHash: "a".repeat(64), active: true, selectedEvidenceIds: ["missing", "file"], selectedEvidenceNames: { missing: " Original unavailable name ", file: " exact label " }, editingEnabled: true, onEvidenceToggle: (id, selected) => { calls.toggles.push([id, selected]); return true; } };
  let cursor = 0, dirty = false, tree: ReactNode, beforeCommit: (() => void) | null = null, respond: (input: Readonly<StepResourceInput>) => Promise<unknown>;
  async function response(input: Readonly<StepResourceInput>) {
    const kind = "search" in input ? "EVIDENCE" : "HISTORY", base = { projectId: input.projectId, testRunId: input.testRunId, testCaseId: input.testCaseId, stepIndex: input.stepIndex, readRequestId: input.readRequestId, requestKey: await stepResourceClientRequestKey(kind, input), scope: { projectId: "p", organizationId: "o", actorId: "n", actorClerkUserId: "cl" }, procedureHash: "a".repeat(64), populationHash: "b".repeat(64), nextCursor: null, provenance: "CURRENT_READER_AUTHORITY_HISTORICAL_ORIGINAL_TENANCY_UNRECORDED", frozenStep: { order: input.stepIndex, action: " Click frozen button ", expectedActionOrData: " Onclick triggers API GET ", expectedResult: "", expectedResponse: null, mediaAttachmentIds: ["missing"], unknown: false } };
    return kind === "HISTORY" ? { ...base, totalRevisions: 2, revisions: [{ id: "rev2", revisionNumber: 2, status: "PASS", note: null, observations: { specimen: " sample ", hardwareRevision: "", firmwareVersion: null, environment: " line1\nline2 ", measurements: [{ name: " Voltage ", value: 0, unit: " V ", upperLimit: null, instrument: " CAL-1 ", unknown: false }], unknown: [false, 0, "raw"] }, evidenceAttachmentIds: ["file"], evidenceAttachments: [{ id: "file", fileName: " Stored historical label ", verification: { versionId: "historical-version", unknown: "keep" } }], actorId: "historical", actorName: " Historical author ", recordedAt: "2026-10-05T20:00:00.123Z", correctionReason: "", previousRevisionId: null, versionProvenance: "STORED_REVISION_METADATA_NOT_FILE_IMMUTABILITY_PROOF" }, { id: "rev1", revisionNumber: 1, status: "FAIL", note: " <script>synthetic</script>\n raw note ", observations: { measurements: [] }, evidenceAttachmentIds: [], evidenceAttachments: [], actorId: "historical", actorName: " Historical author ", recordedAt: "2026-10-05T19:00:00.123Z", correctionReason: null, previousRevisionId: null, versionProvenance: "STORED_REVISION_METADATA_NOT_FILE_IMMUTABILITY_PROOF" }] }
      : { ...base, totalCandidates: 2, search: "search" in input ? input.search : "", attachments: [{ id: "file", testCaseId: "c", fileName: " exact label ", contentType: "text/plain", sizeBytes: 10, uploadCompletedAt: "2026-10-05T20:00:00.123Z", uploadVerification: { etag: "e", versionId: null, verifiedAt: "2026-10-05T20:00:00Z" }, versionId: null, versionProvenance: "UNVERSIONED_NOT_IMMUTABLE", selectable: true }, { id: "unsupported", testCaseId: "c", fileName: " unsupported file ", contentType: "text/plain", sizeBytes: 10, uploadCompletedAt: "2026-10-05T20:00:00.123Z", uploadVerification: { versionId: 42, raw: "keep" }, versionProvenance: "UNSUPPORTED_VERIFICATION_RETAINED_READ_ONLY", selectable: false }] };
  }
  respond = response;
  const fetch = async (input: Readonly<StepResourceInput>) => { ("search" in input ? calls.evidence : calls.history).push(input); return respond(input); };
  const context = vm.createContext({ React, Object, JSON, StepResourceReader, retainedStepEvidence, currentStepReviewSession: () => currentSessionScope(sdk.loaded ? sdk.session : null), window: { Clerk: sdk }, useAuth: () => auth,
    useId: () => { const index = cursor++; if (!Object.hasOwn(hooks, index)) hooks[index] = `synthetic-${index}`; return hooks[index]; },
    useState: (initial: unknown) => { const index = cursor++; if (!Object.hasOwn(hooks, index)) hooks[index] = typeof initial === "function" ? initial() : initial; return [hooks[index], (value: unknown) => { const next = typeof value === "function" ? value(hooks[index]) : value; if (!Object.is(next, hooks[index])) { hooks[index] = next; dirty = true; } }]; },
    useRef: (initial: unknown) => { const index = cursor++; if (!Object.hasOwn(hooks, index)) hooks[index] = { current: initial }; return hooks[index]; },
    useMemo: (fn: () => unknown, deps: unknown[]) => { const index = cursor++, previous = hooks[index] as { deps: unknown[]; value: unknown } | undefined; if (!previous || deps.some((value, n) => !Object.is(value, previous.deps[n]))) hooks[index] = { deps, value: fn() }; return (hooks[index] as { value: unknown }).value; },
    useLayoutEffect: (fn: () => void | (() => void), deps: unknown[]) => { const index = cursor++, previous = hooks[index] as unknown[] | undefined; if (!previous || deps.some((value, n) => !Object.is(value, previous[n]))) { hooks[index] = deps; effects.push(() => { cleanups.get(index)?.(); const cleanup = fn(); if (cleanup) cleanups.set(index, cleanup); }); } },
    trpcReact: { useUtils: () => ({ manualStepExecutionResources: { history: { fetch }, evidence: { fetch } } }) },
  });
  vm.runInContext(executable, context); const component = (context as { component: (props: StepObservationResourcesProps) => ReactNode }).component;
  function render(commit = true) { for (let n = 0; n < 40; n++) { cursor = 0; dirty = false; tree = component(props); if (!commit) return tree; beforeCommit?.(); beforeCommit = null; effects.splice(0).forEach(fn => fn()); if (!dirty) return tree; } throw Error("Actual component did not settle."); }
  async function settle() { for (let n = 0; n < 40; n++) { await new Promise<void>(resolve => setImmediate(resolve)); render(); if (!renderToStaticMarkup(tree).includes("Reading exact")) return tree; } throw Error("Synthetic native-shaped reads did not settle."); }
  render(); return { props, auth, sdk, calls, render, settle, response, get tree() { return tree; }, get html() { return renderToStaticMarkup(tree); }, setResponder: (fn: typeof respond) => { respond = fn; }, beforeCommit: (fn: () => void) => { beforeCommit = fn; }, emit: (session: typeof sdk.session) => { sdk.session = session; Array.from(listeners).forEach(fn => fn()); } };
}

describe("actual StepObservationResources markup/hooks, synthetic auth/RPC only", () => {
  it("closed controls do not fetch history/files and readable frozen procedure/raw metadata appear only after native-shaped reads", async () => { const h = harness(); expect(h.calls.history).toHaveLength(0); expect(h.calls.evidence).toHaveLength(0); click(h.tree, "View step history"); h.render(); await h.settle(); expect(h.html).toContain("Click frozen button"); expect(h.html).toContain("Onclick triggers API GET"); expect(h.html).toContain("Expected response"); expect(h.html).toContain("NULL (retained)"); expect(h.html).toContain("Empty text (retained)"); expect(h.html).toContain("Absent (retained)"); expect(h.html).toContain("Voltage"); expect(h.html).toContain("&lt;script&gt;synthetic&lt;/script&gt;"); expect(h.html).not.toContain("<script>"); expect(h.html).toContain("historical-version"); expect(h.html).not.toContain("<details open"); expect(h.calls.history[0]).toMatchObject({ projectId: "p", expectedNativeActorId: "n", expectedClerkActorId: "cl", originalOrganizationId: "o", limit: 10 }); });
  it("confirmed picker keeps unavailable references/raw names/version states and blocks unsupported additions", async () => { const h = harness(), original = [...h.props.selectedEvidenceIds]; click(h.tree, "Link confirmed stored files"); h.render(); await h.settle(); expect(h.html).toContain("Original unavailable name"); expect(h.html).toContain("unavailable in current page; reference retained"); expect(h.html).toContain("Unversioned stored object"); expect(h.html).toContain("Unsupported verification metadata is retained read-only"); expect(find(h.tree, "input", 'type="checkbox" checked').props.checked).toBe(true); const unsupported = expanded(h.tree).find(node => isValidElement<Record<string, unknown>>(node) && node.type === "input" && node.props.type === "checkbox" && node.props.checked === false); expect(isValidElement<Record<string, unknown>>(unsupported) && unsupported.props.disabled).toBe(true); click(h.tree, "Remove reference"); expect(h.calls.toggles).toEqual([["missing", false]]); expect(h.props.selectedEvidenceIds).toEqual(original); });
  it("literal search typing is retained locally and explicitly applied once without trimming or editing selected IDs", async () => { const h = harness(), selected = [...h.props.selectedEvidenceIds]; click(h.tree, "Link confirmed stored files"); h.render(); await h.settle(); const count = h.calls.evidence.length; expect(find(h.tree, "input", "-search").props.maxLength).toBe(200); change(h.tree, "input", "-search", " raw %_ text "); h.render(); expect(h.calls.evidence).toHaveLength(count); click(h.tree, "Apply literal search"); h.render(); await h.settle(); expect(h.calls.evidence.at(-1)).toMatchObject({ search: " raw %_ text ", cursor: null, limit: 25 }); expect(h.html).toContain("Applied search"); expect(h.props.selectedEvidenceIds).toEqual(selected); });
  it("SDK-only loss and A-B-A prevent old checkbox/open intent callbacks before a React commit", async () => { const h = harness(); h.props.onOpenRecordedEvidence = intent => { h.calls.open.push(intent); return true; }; h.render(); click(h.tree, "View step history"); click(h.tree, "Link confirmed stored files"); h.render(); await h.settle(); const old = h.tree; h.sdk.session = { id: "B", user: { id: "cl" } }; change(old, "input", 'type="checkbox" checked', false); click(old, "Request recorded file"); expect(h.calls.toggles).toEqual([]); expect(h.calls.open).toEqual([]); h.emit({ id: "A", user: { id: "cl" } }); change(old, "input", 'type="checkbox" checked', false); expect(h.calls.toggles).toEqual([]); h.render(); await h.settle(); click(h.tree, "Request recorded file"); expect(h.calls.open).toHaveLength(1); expect(h.calls.open[0]).toMatchObject({ revisionId: "rev2", attachmentId: "file", origin: { nativeActorId: "n", organizationId: "o" } }); });
  it("readonly render disables apparent changes and revokes old callbacks before layout without erasing references", async () => { const h = harness(); click(h.tree, "Link confirmed stored files"); h.render(); await h.settle(); const old = h.tree, selected = [...h.props.selectedEvidenceIds]; h.props.editingEnabled = false; h.render(false); change(old, "input", 'type="checkbox" checked', false); expect(h.calls.toggles).toEqual([]); expect(find(h.tree, "button", "Remove reference").props.disabled).toBe(true); expect(h.html).toContain("Evidence references are read-only"); expect(h.props.selectedEvidenceIds).toEqual(selected); h.render(); });
  it("inactive render hides every private body before layout and returns with new resource nonce, not a draft reset", async () => { const h = harness(); click(h.tree, "Link confirmed stored files"); h.render(); await h.settle(); const old = h.tree, nonce = h.calls.evidence.at(-1)?.readRequestId, selected = [...h.props.selectedEvidenceIds]; h.props.active = false; h.render(false); expect(h.html).toBe(""); change(old, "input", 'type="checkbox" checked', false); expect(h.calls.toggles).toEqual([]); h.render(); h.props.active = true; h.render(); await h.settle(); expect(h.calls.evidence.at(-1)?.readRequestId).not.toBe(nonce); expect(h.props.selectedEvidenceIds).toEqual(selected); expect(h.html).toContain("Original unavailable name"); });
  it("refused/unsupported native-shaped view offers explicit current read controls and never stale stored notes", async () => { const h = harness(); click(h.tree, "View step history"); h.render(); await h.settle(); h.setResponder(async () => { throw Error("private native cause"); }); click(h.tree, "Refresh / first page"); h.render(); await h.settle(); expect(h.html).not.toContain("Click frozen button"); expect(h.html).not.toContain("Historical author"); expect(h.html).not.toContain("private native cause"); expect(find(h.tree, "button", "Refresh / first page").props.disabled).toBe(false); h.props.expectedProcedureHash = null; h.setResponder(h.response); h.render(); await h.settle(); expect(h.html).not.toContain("Click frozen button"); expect(h.html).toContain("procedure authority"); });
});
