// Actual hook/reader; synthetic installed SDK, TanStack/RPC only, no native/API.
import { readFileSync } from "node:fs";
import vm from "node:vm";
import ts from "typescript";
import { expect, it } from "vitest";
import { currentSessionScope, sameAuthScope } from "./auth-query-cache";
import { admitRetestRead, inspectRetestWire, retestIdentity, sameRetestOrigin, RetestReadRenderGuard, retestReviewedBrowserKey, type RetestReviewedInput, type RetestProjection } from "./manual-retest-reviewed-read";
import type { useManualRetestReviewedAccess } from "./use-manual-retest-reviewed-access";
import type { ManualRunCurrentOrigin } from "./manual-run-current-reader";
const source = readFileSync(new URL("./use-manual-retest-reviewed-access.ts", import.meta.url), "utf8"), ast = ts.createSourceFile("hook.ts", source, ts.ScriptTarget.Latest, true), code = ts.transpileModule(ast.statements.filter(ts.isFunctionDeclaration).map(n => ts.createPrinter().printNode(ts.EmitHint.Unspecified, n, ast).replace(/\bexport\s+/, "")).join("\n") + "\nthis.hook=useManualRetestReviewedAccess;", { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.None } }).outputText;
type Reader = ReturnType<typeof useManualRetestReviewedAccess>;
const parent = (): ManualRunCurrentOrigin => ({ projectId: "p", testRunId: "run", organizationId: "o", clerkActorId: "cl", nativeActorId: "n" });
function harness(mode: "ok" | "missing" | "void" | "throw" = "ok", pin: ManualRunCurrentOrigin | null | undefined = undefined, waiting = false) {
  const auth = { isLoaded: true, isSignedIn: true, userId: "cl", sessionId: "A" }, params: { projectId: string; sourceRunId: string; caseId: string; active: boolean; organizationId: string | null | undefined; parentRunScope?: ManualRunCurrentOrigin | null; parentCurrent?: (() => boolean) | null; parentActivation?: string } = { projectId: "p", sourceRunId: "run", caseId: "case", active: true, organizationId: "o", parentRunScope: pin };
  const listeners = new Set<() => void>(), cacheListeners = new Set<() => void>(), cleanup = { work: () => {} }, state = { error: null as unknown, fetching: waiting, paused: false, fetched: !waiting, wrong: "", revision: 1 }, rows = new Map<string, unknown>(), entries = new Map<string, { projection: RetestProjection; input: RetestReviewedInput }>();
  const sdk: { loaded: boolean; session: { id: string; user: { id: string } } | null; addListener?: (cb: () => void) => unknown } = { loaded: true, session: { id: "A", user: { id: "cl" } }, addListener: cb => { listeners.add(cb); cb(); return () => { listeners.delete(cb); cleanup.work(); }; } };
  const normalListener = sdk.addListener!; if (mode === "missing") delete sdk.addListener; if (mode === "void") sdk.addListener = () => undefined; if (mode === "throw") sdk.addListener = () => { throw Error("PRIVATE_SDK"); };
  const requests: Array<{ projection: RetestProjection; input: RetestReviewedInput; enabled: boolean }> = [], slots: Array<{ value?: unknown; setter?: (v: unknown) => void; deps?: unknown[]; cleanup?: () => void }> = [], effects = new Map<number, () => void>();
  let dirty = false, cursor = 0, uuid = 0, reader: Reader, dead = false, beforeCommit: (() => void) | null = null;
  function dto(projection: RetestProjection, input: RetestReviewedInput) {
    const key = JSON.stringify([projection, retestReviewedBrowserKey(input), state.wrong]), previous = rows.get(key); if (previous !== undefined) return previous;
    const scope = { projectId: input.request.projectId, organizationId: state.wrong === "org" ? "foreign" : "o", clerkActorId: state.wrong === "Clerk" ? "other" : "cl", actorId: state.wrong === "native" ? "M" : "n" }, readContext = { requestId: state.wrong === "nonce" ? "6ee2ec04-4d34-40bf-b0e9-000000999999" : input.readRequestId, requested: state.wrong === "key" ? "stale" : retestReviewedBrowserKey(input), projection, scope };
    const requested = JSON.stringify(JSON.parse(retestReviewedBrowserKey(input)).request);
    let raw: unknown = { readContext, basis: "CURRENT_PROJECT_MEMBER_ONLY", sourceRelationshipVerified: false };
    if (projection === "LINKS") raw = { readContext, links: { scope, requested, original: null, retests: [], nextCursor: null } };
    if (projection === "PREVIEW") raw = { readContext, basis: "LEGACY_BOUNDED_PREPARATION_V1", preview: { scope, requested, stepFieldLabels: { action: " Tester action " }, projectId: input.request.projectId, sourceRunId: input.request.sourceRunId, testCaseId: input.request.testCaseId, displayId: "TC-1", reviewHash: "a".repeat(64), sourceOutcome: "FAIL", configuration: { configuration: "", environment: " Raw\n environment ", platform: "", build: "", hardwareRevision: "", firmwareVersion: "", rig: "", batchOrLot: "", calibrationReference: "", protocolReference: "" }, caseDefinitions: [{ testCaseId: input.request.testCaseId, title: " Raw\n title ", validationDomain: "SOFTWARE", reviewStatus: "APPROVED", background: null, given: [], when: [], then: [], verificationProfile: { setup: "", safety: "", instruments: "", acceptanceCriteria: "" }, steps: [{ order: 0, action: " Click\n button ", expectedActionOrData: "", expectedResult: null, expectedResponse: " Raw response ", mediaAttachmentIds: [] }] }], sourceResults: [{ id: "result", testCaseId: input.request.testCaseId, status: "FAIL", note: null, errorMessage: "", observations: { specimen: "", hardwareRevision: "", firmwareVersion: "", environment: "", measurements: [{ name: " Reading ", unit: " V ", value: 0, instrument: "" }] } }], prerequisiteCount: 0, credits: 0, sourceDatasetExecution: null } };
    if (state.wrong === "NULL") raw = null; rows.set(key, raw); return raw;
  }
  const cache = { subscribe: (cb: () => void) => { cacheListeners.add(cb); return () => cacheListeners.delete(cb); } };
  let activeCache = cache;
  const client = { getQueryCache: () => activeCache, getQueryState: (key: unknown) => { const e = entries.get(JSON.stringify(key)); return e ? { status: state.error ? "error" : "success", fetchStatus: state.paused ? "paused" : state.fetching ? "fetching" : "idle", data: dto(e.projection, e.input), dataUpdatedAt: state.revision } : undefined; } };
  function procedure(projection: RetestProjection) { return { projection, useQuery: (input: RetestReviewedInput, options: { enabled: boolean }) => { const wireInput = JSON.parse(JSON.stringify(input)) as RetestReviewedInput; requests.push({ projection, input: wireInput, enabled: options.enabled }); entries.set(JSON.stringify([projection, wireInput]), { projection, input: wireInput }); return { data: dto(projection, wireInput), dataUpdatedAt: state.revision, error: state.error, isFetching: state.fetching, isPaused: state.paused, isFetchedAfterMount: state.fetched }; } }; }
  // Cross VM realms are a harness artifact. Recreate only typed RPC inputs in
  // the reader's host realm, as JSON transport does; never repair output data.
  const context = vm.createContext({ window: { Clerk: sdk }, crypto: { randomUUID: () => `6ee2ec04-4d34-40bf-b0e9-${String(++uuid).padStart(12, "0")}` }, currentSessionScope, sameAuthScope, admitRetestRead: (raw: unknown, input: RetestReviewedInput, projection: RetestProjection, clerk: string, original: Parameters<typeof admitRetestRead>[4]) => admitRetestRead(raw, JSON.parse(JSON.stringify(input)) as RetestReviewedInput, projection, clerk, original), inspectRetestWire, retestIdentity, sameRetestOrigin, RetestReadRenderGuard,
    useAuth: () => auth, useQueryClient: () => client, getQueryKey: (p: { projection: RetestProjection }, input: RetestReviewedInput) => [p.projection, input],
    useState: (initial: unknown) => { const at = cursor++; slots[at] ??= { value: typeof initial === "function" ? initial() : initial }; slots[at]!.setter ??= (v: unknown) => { if (dead) throw Error("State after unmount"); const next = typeof v === "function" ? v(slots[at]!.value) : v; if (!Object.is(next, slots[at]!.value)) { slots[at]!.value = next; dirty = true; } }; return [slots[at]!.value, slots[at]!.setter]; },
    useRef: (v: unknown) => { const at = cursor++; slots[at] ??= { value: { current: v } }; return slots[at]!.value; },
    useMemo: (make: () => unknown, deps: unknown[]) => { const at = cursor++; if (!slots[at]?.deps || deps.length !== slots[at]!.deps!.length || deps.some((v, i) => !Object.is(v, slots[at]!.deps![i]))) slots[at] = { value: make(), deps }; return slots[at]!.value; },
    useLayoutEffect: (make: () => void | (() => void), deps: unknown[]) => { const at = cursor++; slots[at] ??= {}; if (!slots[at]!.deps || deps.some((v, i) => !Object.is(v, slots[at]!.deps![i]))) effects.set(at, () => { slots[at]!.cleanup?.(); slots[at]!.deps = deps; slots[at]!.cleanup = make() || undefined; }); },
    trpcReact: { manualRetest: { accessReviewed: procedure("ACCESS"), previewReviewed: procedure("PREVIEW"), linksReviewed: procedure("LINKS") } } });
  vm.runInContext(code, context); const hook = context.hook as typeof useManualRetestReviewedAccess;
  function render(commit = true) { for (let i = 0; i < 70; i++) { cursor = 0; dirty = false; effects.clear(); reader = hook(params.projectId, params.sourceRunId, params.caseId, params); if (!commit) return reader; if (dirty) continue; const before = beforeCommit; beforeCommit = null; before?.(); for (const effect of effects.values()) effect(); if (!dirty) return reader; } throw Error("Hook did not settle"); }
  render();
  return { auth, sdk, client, context, params, state, requests, cleanup, render, replaceCache: () => { const local = new Set<() => void>(); activeCache = { subscribe: cb => { local.add(cb); return () => local.delete(cb); } }; return () => { activeCache = cache; }; }, rejectInstallation: () => { sdk.addListener = cb => { const unsubscribe = normalListener(cb); context.window.Clerk = { loaded: true, session: sdk.session }; return unsubscribe; }; }, beforeLayout: () => render(false), beforeCommit: (f: () => void) => { beforeCommit = f; }, emit: () => { for (const cb of [...listeners]) cb(); }, emitCache: () => { for (const cb of [...cacheListeners]) cb(); }, restoreListener: () => { sdk.addListener = normalListener; }, unmount: () => { dead = true; for (const slot of slots) slot.cleanup?.(); }, get reader() { return reader; } };
}
it("first fresh native ACCESS pins N without automatic private queries, ACCESS never grants creation", () => {
  const h = harness(); expect(h.reader.current()).toBe(h.reader.snapshot); expect(h.reader.origin).toMatchObject({ nativeActorId: "n", clerkActorId: "cl", organizationId: "o" }); expect(h.reader.canCreate).toBe(false); expect(h.requests.filter(r => r.enabled).every(r => r.projection === "ACCESS")).toBe(true);
  expect(h.reader.read("PREVIEW")).toBe(true); h.render(); expect(h.reader.current()).toBe(h.reader.snapshot); expect(h.reader.snapshot!.projection).toBe("PREVIEW"); expect(h.requests.filter(r => r.enabled && r.projection === "PREVIEW").at(-1)!.input.expectedNativeActorId).toBe("n");
});
it("waiting first ACCESS cannot poison completed admission; pin capture never silently changes nonce/key mid-flight", () => {
  const h = harness("ok", undefined, true); expect(h.reader.current()).toBeNull(); const nonce = h.requests.filter(r => r.enabled).at(-1)!.input.readRequestId;
  h.state.fetching = false; h.state.fetched = true; h.render(); expect(h.reader.current()).toBe(h.reader.snapshot); expect(h.reader.snapshot!.data.readContext.requestId).toBe(nonce);
  const requests = h.requests.filter(r => r.enabled && r.input.readRequestId === nonce); expect(new Set(requests.map(r => retestReviewedBrowserKey(r.input))).size).toBe(1);
});
it.each(["missing", "void", "throw"] as const)("SDK %s registration cannot admit a read; explicit retry installs real cleanup before any native intent", mode => {
  const h = harness(mode); expect(h.reader.current()).toBeNull(); expect(h.requests.every(r => !r.enabled)).toBe(true); expect(h.reader.origin).toBeNull(); expect(h.reader.error ?? "").not.toContain("PRIVATE_SDK"); h.restoreListener(); expect(h.reader.refresh()).toBe(false); h.render(); expect(h.reader.current()).toBe(h.reader.snapshot);
});
it("explicit null parent withholds, valid N before first query refuses native M and never rebases", () => {
  const h = harness("ok", null); expect(h.requests.every(r => !r.enabled)).toBe(true); h.params.parentRunScope = parent(); h.state.wrong = "native"; h.render(); expect(h.requests.filter(r => r.enabled).every(r => r.input.expectedNativeActorId === "n")).toBe(true); expect(h.reader.origin).toBeNull(); h.state.wrong = ""; h.reader.refresh(); h.render(); expect(h.reader.current()).toBe(h.reader.snapshot); const original = h.reader.origin; h.params.parentRunScope = { ...parent(), nativeActorId: "M" }; h.render(); expect(h.reader.current()).toBeNull(); expect(h.reader.origin).toBe(original);
});
it.each(["org", "Clerk", "nonce", "key", "NULL"])("malformed %s whole echo never pins original owner or exposes private body", wrong => { const h = harness("ok", parent(), true); h.state.wrong = wrong; h.state.fetching = false; h.state.fetched = true; h.render(); expect(h.reader.origin).toBeNull(); expect(h.reader.current()).toBeNull(); });
it("same-owner B stays withheld until explicit fresh native refresh, preserving immutable N origin and no private auto-read", () => {
  const h = harness(), original = h.reader.origin, old = h.reader, nonce = old.snapshot!.data.readContext.requestId;
  h.sdk.session = { id: "B", user: { id: "cl" } }; h.emit(); expect(old.current()).toBeNull(); expect(old.refresh()).toBe(false); h.auth.sessionId = "B"; h.render(); expect(h.reader.current()).toBeNull(); expect(h.reader.refresh()).toBe(true); h.render(); expect(h.reader.current()).toBe(h.reader.snapshot); expect(h.reader.origin).toBe(original); expect(h.reader.observedSessionId).toBe("B"); expect(h.reader.snapshot!.data.readContext.requestId).not.toBe(nonce); expect(h.reader.snapshot!.projection).toBe("ACCESS"); expect(old.current()).toBeNull(); expect(old.refresh()).toBe(false);
});
it("SDK-only A-B-A without hook commit never revives old nonce or callback", () => { const h = harness(), old = h.reader; h.sdk.session = { id: "B", user: { id: "cl" } }; h.emit(); h.sdk.session = { id: "A", user: { id: "cl" } }; h.emit(); expect(old.current()).toBeNull(); h.render(); expect(h.reader.current()).toBeNull(); h.reader.refresh(); h.render(); expect(h.reader.current()).toBe(h.reader.snapshot); expect(old.read("PREVIEW")).toBe(false); });
it("action-time SDK change before hook/listener commit revokes all old reads", () => { const h = harness(), old = h.reader; h.sdk.session = { id: "B", user: { id: "cl" } }; expect(old.current()).toBeNull(); expect(old.read("PREVIEW")).toBe(false); expect(old.refresh()).toBe(false); });
it("cache failure A-B-A between render/layout cannot let posted layout rebind old snapshot; fresh nonce only", () => { const h = harness(), old = h.reader; h.beforeCommit(() => { h.state.fetching = true; h.emitCache(); h.state.fetching = false; h.emitCache(); }); h.render(); expect(old.current()).toBeNull(); expect(h.reader.current()).toBeNull(); h.reader.refresh(); h.render(); expect(h.reader.current()).toBe(h.reader.snapshot); });
it("private preview refusal hides complete body and raw error, without clearing original pins or inferring empty", () => { const h = harness(), original = h.reader.origin; h.reader.read("PREVIEW"); h.state.error = Error("PRIVATE_NATIVE_BODY"); h.render(); expect(h.reader.current()).toBeNull(); expect(h.reader.fresh).toBeNull(); expect(h.reader.origin).toBe(original); expect(h.reader.error).not.toContain("PRIVATE_NATIVE_BODY"); });
it("old handlers fail before layout and after another valid committed frame, including parent callback loss", () => { const h = harness(), old = h.reader; h.params.active = false; h.beforeLayout(); expect(old.current()).toBeNull(); expect(old.refresh()).toBe(false); h.render(); h.params.active = true; h.render(); h.reader.refresh(); h.render(); expect(h.reader.current()).toBe(h.reader.snapshot); expect(old.current()).toBeNull(); expect(old.refresh()).toBe(false); let current = true; h.params.parentCurrent = () => current; h.params.parentActivation = "parentA"; h.render(); h.reader.refresh(); h.render(); const captured = h.reader; current = false; expect(captured.current()).toBeNull(); expect(captured.read("LINKS")).toBe(false); });
it("same-session SDK resource replacement/restoration requires a new installed monitor and explicit native nonce", () => { const h = harness(), old = h.reader, sdk = h.sdk; h.context.window.Clerk = { ...sdk }; expect(old.current()).toBeNull(); h.render(); expect(h.reader.current()).toBeNull(); h.context.window.Clerk = sdk; h.render(); expect(h.reader.current()).toBeNull(); h.reader.refresh(); h.render(); expect(h.reader.current()).toBe(h.reader.snapshot); });
it("throwing unsubscribe invokes captured callbacks only after SDK/cache/frame authority is revoked", () => { const h = harness(), old = h.reader; h.cleanup.work = () => { expect(old.current()).toBeNull(); expect(old.refresh()).toBe(false); throw Error("PRIVATE_CLEANUP"); }; expect(() => h.unmount()).not.toThrow(); expect(old.current()).toBeNull(); expect(old.read("PREVIEW")).toBe(false); });
it("cache resource A-B-A cannot reauthorize its old completed object without explicit native refresh", () => { const h = harness(), old = h.reader, restore = h.replaceCache(); expect(old.current()).toBeNull(); h.render(); expect(h.reader.current()).toBeNull(); restore(); h.render(); expect(h.reader.current()).toBeNull(); expect(h.reader.refresh()).toBe(true); h.render(); expect(h.reader.current()).toBe(h.reader.snapshot); expect(h.reader.snapshot!.data.readContext.requestId).not.toBe(old.snapshot!.data.readContext.requestId); });
it("registration rejected after a real cleanup return still unsubscribes after revocation", () => { const h = harness(), old = h.reader; let cleanups = 0; h.cleanup.work = () => { cleanups++; expect(old.current()).toBeNull(); expect(old.refresh()).toBe(false); }; h.rejectInstallation(); h.context.window.Clerk = { ...h.sdk }; h.render(); expect(h.reader.current()).toBeNull(); expect(cleanups).toBeGreaterThanOrEqual(2); });
it("observed parent A-B-A remains latched; contradictory org discovery never starts an original-N query", () => { const h = harness("ok", parent()); let allowed = true; h.params.parentCurrent = () => allowed; h.params.parentActivation = "parentA"; h.render(); h.reader.refresh(); h.render(); const old = h.reader; allowed = false; expect(old.current()).toBeNull(); allowed = true; expect(old.current()).toBeNull(); h.render(); h.reader.refresh(); h.render(); expect(h.reader.current()).toBe(h.reader.snapshot); h.params.organizationId = "foreign"; h.render(); expect(h.reader.current()).toBeNull(); expect(h.reader.refresh()).toBe(false); });
it("empty links are genuine after explicit current read, never an inferred global count; no mutation transport exists", () => { const h = harness(); h.reader.read("LINKS"); h.render(); expect(h.reader.current()).toBe(h.reader.snapshot); expect(h.reader.snapshot!.projection).toBe("LINKS"); expect(h.requests.filter(r => r.enabled && r.projection === "LINKS")).not.toHaveLength(0); expect(source).not.toContain("useMutation"); expect(source).not.toContain("@vaettir/api"); });
