import { readFileSync } from "node:fs";
import vm from "node:vm";
import ts from "typescript";
import { describe,expect,it } from "vitest";
import type { useCaseReviewQueue } from "./use-case-review-queue";
import type { RouterInputs } from "./trpcReact";
type Queue = ReturnType<typeof useCaseReviewQueue>;
type AccessInput = RouterInputs["caseReview"]["access"];
type PageInput = RouterInputs["caseReview"]["page"];
type ReadOptions = { enabled: boolean };
type Request = { kind: "access"; input: AccessInput; options: ReadOptions } | { kind: "page"; input: PageInput; options: ReadOptions };
const source=readFileSync(new URL("./use-case-review-queue.ts",import.meta.url),"utf8"),ast=ts.createSourceFile("queue.ts",source,ts.ScriptTarget.Latest,true),declaration=ast.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==="useCaseReviewQueue")!;
const code=ts.transpileModule(`${ts.createPrinter().printNode(ts.EmitHint.Unspecified,declaration,ast).replace(/\bexport\s+/,"")}\nthis.queue=useCaseReviewQueue;`,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
function harness(){const hooks:unknown[]=[],effects:Array<()=>void>=[],cleanups=new Map<number,()=>void>(),auth={isLoaded:true,isSignedIn:true,userId:"cl",sessionId:"A"},state={accessError:null as unknown,pageError:null as unknown,pageFetching:false,pagePaused:false,wrong:null as string|null},requests:Request[]=[];let cursor=0,dirty=false,uuid=0,queue:Queue;
  const flags={isFetchedAfterMount:true,isFetching:false,isPaused:false,error:null},scope={projectId:"p",organizationId:"o",actorId:"n",actorClerkUserId:"cl"};
  const context=vm.createContext({crypto:{randomUUID:()=>`6ee2ec04-4d34-40bf-b0e9-${String(++uuid).padStart(12,"0")}`},useAuth:()=>auth,useState:(initial:unknown)=>{const at=cursor++;if(!Object.hasOwn(hooks,at))hooks[at]=initial;return[hooks[at],(value:unknown)=>{const next=typeof value==="function"?value(hooks[at]):value;if(!Object.is(next,hooks[at])){hooks[at]=next;dirty=true;}}];},useRef:(initial:unknown)=>{const at=cursor++;if(!Object.hasOwn(hooks,at))hooks[at]={current:initial};return hooks[at];},useLayoutEffect:(effect:()=>void|(()=>void),deps:unknown[])=>{const at=cursor++,prior=hooks[at] as unknown[]|undefined;if(!prior||deps.some((v,n)=>!Object.is(v,prior[n]))){hooks[at]=deps;effects.push(()=>{cleanups.get(at)?.();const cleanup=effect();if(cleanup)cleanups.set(at,cleanup);});}},trpcReact:{caseReview:{access:{useQuery:(input:AccessInput,options:ReadOptions)=>{requests.push({kind:"access",input,options});return{...flags,error:state.accessError,data:{projectId:"p",requestId:input.requestId,readScope:scope,canRecover:true}};}},page:{useQuery:(input:PageInput,options:ReadOptions)=>{requests.push({kind:"page",input,options});return{...flags,error:state.pageError,isFetching:state.pageFetching,isPaused:state.pagePaused,data:{projectId:"p",requestId:state.wrong==="nonce"?"old":input.requestId,readScope:state.wrong==="native"?{...scope,actorId:"other"}:scope,offset:input.offset,populationHash:"a".repeat(64),nextOffset:input.offset===0?25:null,totalPending:30,matching:30,items:[{id:input.offset===0?"first":"second",displayId:"TC-1",title:"Current",confidence:null,sourceFilePath:null}]}};}}}}});vm.runInContext(code,context);const fn=(context as unknown as { queue: (projectId: string) => Queue }).queue;
  function render(project="p"){for(let n=0;n<30;n++){cursor=0;dirty=false;queue=fn(project);effects.splice(0).forEach(effect=>effect());if(!dirty)return queue;}throw Error("Queue did not settle");}render();return{auth,state,requests,render,get queue(){return queue;}};
}
describe("actual pending queue current-reader/filter/page handlers synthetic only",()=>{
  it("native page/count metadata uses pinned scope and later pages freeze the population hash",()=>{const h=harness();expect(h.queue.canOpen("first")).toBe(true);expect(h.queue.canOpen("hidden")).toBe(false);h.queue.next();h.render();expect(h.requests.at(-1)!.input).toMatchObject({offset:25,populationHash:"a".repeat(64),originalOrganizationId:"o",expectedNativeActorId:"n"});expect(h.queue.canOpen("second")).toBe(true);h.queue.previous();h.render();expect(h.queue.filter.offset).toBe(0);});
  it("failed/paused/fetching candidate page hides cached rows but current access can narrow search/refuse oversized text",()=>{for(const key of["pageError","pagePaused","pageFetching"] as const){const h=harness();if(key==="pageError") h.state.pageError=Error("refused"); else h.state[key]=true;h.render();expect(h.queue.fresh).toBeNull();expect(h.queue.canOpen("first")).toBe(false);h.queue.setSearch("narrow");h.render();expect(h.queue.filter.search).toBe("narrow");h.queue.setSearch("x".repeat(201));h.render();expect(h.queue.filter.search).toBe("narrow");expect(h.queue.notice).toContain("200");}});
  it("stale handlers after authority A-B-A cannot replace filters/page or open cached rows",()=>{const h=harness(),old=h.queue;h.state.accessError=Error("revoked");h.render();h.state.accessError=null;h.render();old.setSearch("stale");old.next();expect(old.canOpen("first")).toBe(false);h.render();expect(h.queue.filter.search).toBe("");expect(h.queue.filter.offset).toBe(0);});
  it("wrong completed page nonce/native reader and account/project changes cannot display or select old private metadata",()=>{for(const wrong of["nonce","native"]){const h=harness();h.state.wrong=wrong;expect(h.render().fresh).toBeNull();}const h=harness();h.auth.userId="other";expect(h.render().fresh).toBeNull();expect(h.requests.at(-1)!.options.enabled).toBe(false);h.auth.userId="cl";expect(h.render("other").fresh).toBeNull();});
  it("Return to first page remains available after stale-population refusal; browsing never allocates a review",()=>{const h=harness();h.queue.next();h.render();h.state.pageError=Error("population changed");h.render();h.queue.first();h.render();expect(h.queue.filter.offset).toBe(0);expect(h.queue.filter.populationHash).toBeUndefined();expect(h.requests.every(request=>["access","page"].includes(request.kind))).toBe(true);});
});
