import { readFileSync } from "node:fs";
import vm from "node:vm";
import ts from "typescript";
import { describe,expect,it } from "vitest";
import { sameReviewReader } from "./case-review-decision-draft";
import { currentSessionScope,sameAuthScope } from "./auth-query-cache";
const source=readFileSync(new URL("./use-case-review-access.ts",import.meta.url),"utf8"),ast=ts.createSourceFile("access.ts",source,ts.ScriptTarget.Latest,true),declaration=ast.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==="useCaseReviewAccess")!;
const code=ts.transpileModule(`${ts.createPrinter().printNode(ts.EmitHint.Unspecified,declaration,ast).replace(/\bexport\s+/,"")}\nthis.access=useCaseReviewAccess;`,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
function harness(){const hooks:unknown[]=[],auth={isLoaded:true,isSignedIn:true,userId:"cl",sessionId:"A"},sdk={loaded:true,session:{id:"A",user:{id:"cl"}} as null|{id:string;user:{id:string}}},params={projectId:"p",caseId:"c",active:true},queryState={error:null as unknown,isFetching:false,isPaused:false,isFetchedAfterMount:true,wrong:null as string|null},projectState={...queryState,canRecover:true},requests:any[]=[];let cursor=0,dirty=false,uuid=0,reads:any;
  function data(input:any,state:typeof queryState){const row={projectId:input.projectId,requestId:input.requestId,readScope:{projectId:input.projectId,organizationId:"o",actorId:"n",actorClerkUserId:"cl"}};if(state.wrong==="nonce")row.requestId="stale";if(state.wrong==="native")row.readScope.actorId="replacement";if(state.wrong==="org")row.readScope.organizationId="foreign";if(state.wrong==="Clerk")row.readScope.actorClerkUserId="other";return row;}
  const context=vm.createContext({window:{Clerk:sdk},currentSessionScope,sameAuthScope,sameReviewReader,crypto:{randomUUID:()=>`6ee2ec04-4d34-40bf-b0e9-${String(++uuid).padStart(12,"0")}`},useAuth:()=>auth,useState:(initial:unknown)=>{const at=cursor++;if(!Object.hasOwn(hooks,at))hooks[at]=initial;return[hooks[at],(value:unknown)=>{const next=typeof value==="function"?value(hooks[at]):value;if(!Object.is(next,hooks[at])){hooks[at]=next;dirty=true;}}];},trpcReact:{caseReview:{access:{useQuery:(input:any,options:any)=>{requests.push({kind:"project",input,options});return{...projectState,data:{...data(input,projectState),canRecover:projectState.canRecover}};}},preview:{useQuery:(input:any,options:any)=>{requests.push({kind:"preview",input,options});return{...queryState,data:{...data(input,queryState),caseId:input.caseId,snapshot:{},supported:true,contentHash:"a".repeat(64),reviewStateHash:"b".repeat(64),canRecover:true,canDecide:true}};}}}}});vm.runInContext(code,context);const fn=(context as any).access;
  function render(){for(let n=0;n<30;n++){cursor=0;dirty=false;reads=fn(params.projectId,params.caseId,params.active);if(!dirty)return reads;}throw Error("Access did not settle");}render();return{auth,sdk,params,queryState,projectState,requests,render,get reads(){return reads;}};
}
describe("actual review access hook synthetic current nonce/native reader",()=>{
  it("completes original native discovery then pinned second read without custom-field schema",()=>{const h=harness();expect(h.reads.fresh).not.toBeNull();expect(h.requests.at(-1).input).toMatchObject({originalOrganizationId:"o",expectedClerkActorId:"cl",expectedNativeActorId:"n"});expect(h.reads.origin).toMatchObject({projectId:"p",caseId:"c",nativeActorId:"n"});});
  it.each(["nonce","native","org"])("%s echo mismatch withholds snapshot and never rebinds origin",wrong=>{const h=harness(),origin=h.reads.origin;h.queryState.wrong=wrong;expect(h.render().fresh).toBeNull();expect(h.reads.origin).toBe(origin);});
  it("error/fetch/paused/incomplete cached rows are not current private reads",()=>{for(const key of["error","isFetching","isPaused","isFetchedAfterMount"]){const h=harness();(h.queryState as any)[key]=key==="error"?Error("revoked"):key!=="isFetchedAfterMount";expect(h.render().fresh).toBeNull();}});
  it("session/activation A-B-A rotates request UUID and retains native scope; other account/project/case cannot adopt",()=>{const h=harness(),first=h.reads.activation,origin=h.reads.origin;h.auth.sessionId="B";const b=h.render().activation;h.auth.sessionId="A";expect(h.render().activation).not.toBe(first);expect(b).not.toBe(first);h.auth.userId="other";expect(h.render().fresh).toBeNull();expect(h.requests.at(-1).options.enabled).toBe(false);h.auth.userId="cl";h.params.projectId="other";expect(h.render().fresh).toBeNull();h.params.projectId="p";h.params.caseId="other";expect(h.render().fresh).toBeNull();expect(h.reads.origin).toBe(origin);});
  it("close/reopen and explicit refresh invalidate previous native activation, not origin",()=>{const h=harness(),first=h.reads.activation,origin=h.reads.origin;h.params.active=false;expect(h.render().fresh).toBeNull();h.params.active=true;expect(h.render().activation).not.toBe(first);const before=h.reads.activation;h.reads.refresh();expect(h.render().activation).not.toBe(before);expect(h.reads.origin).toBe(origin);});
  it.each(["deleted","reparented","foreign-link"])("unavailable %s preview retains genuine project access only, not fabricated preview/body",reason=>{const h=harness(),origin=h.reads.origin;h.queryState.error=Error(reason);h.render();expect(h.reads.fresh).toBeNull();expect(h.reads.projectAccess).toMatchObject({projectId:"p",canRecover:true,readScope:{actorId:"n",organizationId:"o"}});expect(h.reads.projectAccess).not.toHaveProperty("snapshot");expect(h.reads.projectAccess).not.toHaveProperty("canDecide");expect(h.reads.projectAccess).not.toHaveProperty("caseId");expect(h.reads.origin).toBe(origin);const project=h.requests.filter(request=>request.kind==="project").at(-1);expect(project.input).not.toHaveProperty("caseId");expect(project.input.requestId).not.toBe(h.requests.at(-1).input.requestId);});
  it.each(["nonce","native","org","Clerk"])("project %s mismatch denies both recovery reader and cached private preview",wrong=>{const h=harness(),origin=h.reads.origin;h.projectState.wrong=wrong;expect(h.render().projectAccess).toBeNull();expect(h.reads.fresh).toBeNull();expect(h.requests.at(-1).options.enabled).toBe(false);expect(h.reads.origin).toBe(origin);});
  it("project error/fetch/paused/incomplete revokes preview despite completed cached body, while READ_ONLY echo cannot recover",()=>{for(const key of["error","isFetching","isPaused","isFetchedAfterMount"]){const h=harness();(h.projectState as any)[key]=key==="error"?Error("revoked"):key!=="isFetchedAfterMount";h.render();expect(h.reads.projectAccess).toBeNull();expect(h.reads.fresh).toBeNull();}const h=harness();h.projectState.canRecover=false;expect(h.render().projectAccess.canRecover).toBe(false);});
  it("SDK differs before useAuth commit: no cached native reader/body or stale refresh; A-B-A requires a new read activation",()=>{const h=harness(),first=h.reads.activation,oldRefresh=h.reads.refresh;expect(h.reads.observedSessionId).toBe("A");h.sdk.session={id:"B",user:{id:"cl"}};oldRefresh();expect(h.auth.sessionId).toBe("A");h.render();expect(h.reads.projectAccess).toBeNull();expect(h.reads.fresh).toBeNull();expect(h.reads.observedSessionId).toBeNull();expect(h.requests.at(-1).options.enabled).toBe(false);h.sdk.session={id:"A",user:{id:"cl"}};h.render();expect(h.reads.activation).not.toBe(first);expect(h.reads.observedSessionId).toBe("A");});
  it("fresh native original-reader admission may observe renewed session without changing immutable origin",()=>{const h=harness(),origin=h.reads.origin,first=h.reads.activation;h.sdk.session={id:"renewed",user:{id:"cl"}};h.auth.sessionId="renewed";h.render();expect(h.reads.projectAccess).not.toBeNull();expect(h.reads.observedSessionId).toBe("renewed");expect(h.reads.activation).not.toBe(first);expect(h.reads.origin).toBe(origin);expect(h.reads.origin).not.toHaveProperty("sessionId");});
});
