import { readFileSync } from "node:fs";
import vm from "node:vm";
import ts from "typescript";
import { describe, expect, it } from "vitest";
import { currentSessionScope } from "./auth-query-cache";
import { StepResourceReader, stepResourceClientRequestKey, type StepResourceInput } from "./step-execution-resource-reader";
import type { StepExecutionResources } from "./use-step-execution-resources";
const source = readFileSync(new URL("./use-step-execution-resources.ts", import.meta.url), "utf8"), ast = ts.createSourceFile("resources.ts", source, ts.ScriptTarget.Latest, true);
const executable = ts.transpileModule(ast.statements.filter(ts.isFunctionDeclaration).map(node => ts.createPrinter().printNode(ts.EmitHint.Unspecified, node, ast).replace(/\bexport\s+/, "")).join("\n") + "\nthis.hook=useStepExecutionResources;", { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.None } }).outputText;

function harness(kind: "HISTORY" | "EVIDENCE" = "HISTORY") {
  const hooks: unknown[] = [], cleanups = new Map<number, () => void>(), effects: Array<() => void> = [], listeners = new Set<() => void>();
  const auth = { isLoaded: true, isSignedIn: true, userId: "cl", sessionId: "A" }, sdk = { loaded: true, session: { id: "A", user: { id: "cl" } } as null | { id: string; user: { id: string } }, addListener: (fn: () => void) => { listeners.add(fn); fn(); return () => { listeners.delete(fn); }; } };
  const params = { kind, active: true, origin: { projectId: "p", testRunId: "r", testCaseId: "c", stepIndex: 0, organizationId: "o", clerkActorId: "cl", nativeActorId: "n" }, hash: "a".repeat(64) as string | null };
  const sent: Readonly<StepResourceInput>[] = []; let cursor = 0, dirty = false, workflow: StepExecutionResources, beforeCommit: (() => void) | null = null, responder: (input: Readonly<StepResourceInput>) => Promise<unknown>;
  async function response(input: Readonly<StepResourceInput>) { const kind = "search" in input ? "EVIDENCE" : "HISTORY", base = { projectId: input.projectId, testRunId: input.testRunId, testCaseId: input.testCaseId, stepIndex: input.stepIndex, readRequestId: input.readRequestId, requestKey: await stepResourceClientRequestKey(kind, input), scope: { projectId: "p", organizationId: "o", actorId: "n", actorClerkUserId: "cl" }, procedureHash: params.hash ?? "a".repeat(64), populationHash: "b".repeat(64), nextCursor: null, provenance: "CURRENT_READER_AUTHORITY_HISTORICAL_ORIGINAL_TENANCY_UNRECORDED", frozenStep: { order: input.stepIndex, action: " private frozen action ", expectedActionOrData: " GET /synthetic ", expectedResult: "", expectedResponse: null } }; return kind === "HISTORY" ? { ...base, revisions: [], totalRevisions: 0 } : { ...base, attachments: [], totalCandidates: 0, search: "search" in input ? input.search : "" }; }
  responder = response;
  const transport = async (input: Readonly<StepResourceInput>) => { sent.push(input); return responder(input); };
  const context = vm.createContext({ window: { Clerk: sdk }, JSON, Object, StepResourceReader, currentStepReviewSession: () => currentSessionScope(sdk.loaded ? sdk.session : null), useAuth: () => auth,
    useState: (initial: unknown) => { const index = cursor++; if (!Object.hasOwn(hooks, index)) hooks[index] = typeof initial === "function" ? initial() : initial; return [hooks[index], (value: unknown) => { const next = typeof value === "function" ? value(hooks[index]) : value; if (!Object.is(next, hooks[index])) { hooks[index] = next; dirty = true; } }]; },
    useRef: (initial: unknown) => { const index = cursor++; if (!Object.hasOwn(hooks, index)) hooks[index] = { current: initial }; return hooks[index]; },
    useMemo: (fn: () => unknown, deps: unknown[]) => { const index = cursor++, previous = hooks[index] as { deps: unknown[]; value: unknown } | undefined; if (!previous || deps.some((value, n) => !Object.is(value, previous.deps[n]))) hooks[index] = { deps, value: fn() }; return (hooks[index] as { value: unknown }).value; },
    useLayoutEffect: (fn: () => void | (() => void), deps: unknown[]) => { const index = cursor++, previous = hooks[index] as unknown[] | undefined; if (!previous || deps.some((value, n) => !Object.is(value, previous[n]))) { hooks[index] = deps; effects.push(() => { cleanups.get(index)?.(); const cleanup = fn(); if (cleanup) cleanups.set(index, cleanup); }); } },
  });
  vm.runInContext(executable, context); const invoke = (context as { hook: (...args: unknown[]) => StepExecutionResources }).hook;
  function render(commit = true) { for (let n = 0; n < 40; n++) { cursor = 0; dirty = false; workflow = invoke(params.kind, params.origin, params.active, params.hash, transport); if (!commit) return workflow; beforeCommit?.(); beforeCommit = null; effects.splice(0).forEach(fn => fn()); if (!dirty) return workflow; } throw Error("Resource hook failed to settle."); }
  async function settle() { for (let n = 0; n < 40; n++) { await new Promise<void>(resolve => setImmediate(resolve)); render(); if (!workflow.view.busy && (workflow.view.data || workflow.view.error || !workflow.view.canRequest)) return workflow; } throw Error("Synthetic resource read did not settle."); }
  render(); return { params, auth, sdk, sent, render, settle, response, get workflow() { return workflow; }, setResponder: (fn: typeof responder) => { responder = fn; }, beforeCommit: (fn: () => void) => { beforeCommit = fn; }, emit: (session: typeof sdk.session) => { sdk.session = session; Array.from(listeners).forEach(fn => fn()); }, unmount: () => { Array.from(cleanups.values()).forEach(fn => fn()); cleanups.clear(); } };
}

describe("actual resource hook + real reader, only React/Clerk/RPC synthetic", () => {
  it("reads exact native-shaped scope/nonce and keeps resource body private until matching current procedure authority", async () => { const h = harness(); await h.settle(); expect(h.workflow.view.data?.scope.actorId).toBe("n"); expect(h.sent[0]).toMatchObject({ expectedNativeActorId: "n", expectedClerkActorId: "cl", originalOrganizationId: "o", limit: 10, cursor: null }); h.params.hash = null; h.render(); await h.settle(); expect(h.workflow.view.data).toBeNull(); expect(h.workflow.view.error).toContain("procedure authority"); h.params.hash = "a".repeat(64); h.render(); await h.settle(); expect(h.workflow.view.data).not.toBeNull(); });
  it("installed SDK A-B-A before React commit prevents late body publication and requires a fresh nonce", async () => { const h = harness(); await h.settle(); let release: ((value: unknown) => void) | undefined, entered: (() => void) | undefined; const dispatched = new Promise<void>(resolve => { entered = resolve; }); h.setResponder(input => new Promise(resolve => { release = resolve; entered!(); void input; })); const refreshing = h.workflow.refresh(); await dispatched; const input = h.sent.at(-1)!; h.emit({ id: "B", user: { id: "cl" } }); h.emit({ id: "A", user: { id: "cl" } }); release!(await h.response(input)); await refreshing; h.setResponder(h.response); expect(h.render(false).view.data).toBeNull(); h.render(); await h.settle(); expect(h.workflow.view.data).not.toBeNull(); expect(h.sent.at(-1)?.readRequestId).not.toBe(input.readRequestId); });
  it("SDK movement between render and layout commit cannot dispatch or commit private reads", async () => { const h = harness(); await h.settle(); const count = h.sent.length; h.params.active = false; h.render(); h.params.active = true; h.beforeCommit(() => { h.sdk.session = { id: "B", user: { id: "cl" } }; }); h.render(); await h.settle(); expect(h.sent).toHaveLength(count); expect(h.workflow.view.data).toBeNull(); expect(h.workflow.view.canRequest).toBe(false); });
  it("new render intent blocks old handlers before layout and stable-value origin echoes do not refetch forever", async () => { const h = harness(); await h.settle(); const old = h.workflow, count = h.sent.length; h.params.active = false; expect(h.render(false).view.data).toBeNull(); await old.refresh(); expect(h.sent).toHaveLength(count); h.render(); h.params.active = true; h.render(); await h.settle(); const currentCount = h.sent.length; h.params.origin = { ...h.params.origin }; h.render(); await h.settle(); expect(h.sent).toHaveLength(currentCount); h.params.origin = { ...h.params.origin, nativeActorId: "other" }; expect(h.render(false).view.intent).toBeNull(); h.render(); await h.settle(); expect(h.sent).toHaveLength(currentCount); });
  it("current denied/error resource views remain explicitly refreshable and filterable, without cached fallback", async () => { const h = harness(); await h.settle(); h.setResponder(async () => { throw Error("private server error"); }); await h.workflow.refresh(); h.render(); expect(h.workflow.view.data).toBeNull(); expect(h.workflow.view.error).not.toContain("private server"); h.setResponder(h.response); await h.workflow.setLimit(1); h.render(); expect(h.sent.at(-1)?.limit).toBe(1); expect(h.workflow.view.data).not.toBeNull(); });
  it("collapse retains external exact buffers/IDs while resource restoration uses another native nonce", async () => { const h = harness(); await h.settle(); const old = h.sent[0]!.readRequestId, editor = { note: null, readings: ["0.10000000000000001"], selectedEvidence: ["unavailable"] }, original = structuredClone(editor); h.params.active = false; h.render(); expect(h.workflow.view.data).toBeNull(); expect(h.workflow.view.intent).toBeNull(); h.params.active = true; h.render(); await h.settle(); expect(h.sent.at(-1)?.readRequestId).not.toBe(old); expect(editor).toEqual(original); h.unmount(); });
  it("evidence literal search and explicit limit survive refused pages without changing external selected IDs", async () => { const h = harness("EVIDENCE"); await h.settle(); const selected = ["unavailable", "same", "same"], original = [...selected]; h.setResponder(async () => { throw Error("candidate count bound"); }); await h.workflow.refresh(); h.render(); expect(h.workflow.view.data).toBeNull(); h.setResponder(h.response); await h.workflow.setSearch(" literal %_ search "); h.render(); expect(h.sent.at(-1)).toMatchObject({ search: " literal %_ search ", limit: 25, cursor: null }); await h.workflow.setLimit(1); h.render(); expect(h.sent.at(-1)).toMatchObject({ search: " literal %_ search ", limit: 1 }); expect(selected).toEqual(original); });
  it("actual currentData hook refuses stale parent actions before effect commit or SDK publication", async () => { const h = harness(); await h.settle(); const old = h.workflow; let calls = 0; const action = () => { calls++; return true; }; expect(old.currentData(action)).toBe(true); h.params.active = false; h.render(false); expect(old.currentData(action)).toBe(false); h.render(); h.params.active = true; h.render(); await h.settle(); const restored = h.workflow; h.sdk.session = { id: "B", user: { id: "cl" } }; expect(restored.currentData(action)).toBe(false); expect(calls).toBe(1); });
});
