import { readFileSync } from "node:fs";
import vm from "node:vm";
import ts from "typescript";
import { describe,expect,it } from "vitest";
import { assertReviewAck,freezeReviewInput,freezeReviewSnapshot,reviewDecisionHash,sameReviewReader } from "./case-review-decision-draft";
import { manualStartDefinitivelyRejected } from "./manual-run-start";
import { currentSessionScope,sameAuthScope } from "./auth-query-cache";
import type { ReviewController } from "./use-case-review-controller";
const source=readFileSync(new URL("./use-case-review-controller.ts",import.meta.url),"utf8"),ast=ts.createSourceFile("controller.ts",source,ts.ScriptTarget.Latest,true),declaration=ast.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==="useCaseReviewController")!;
const code=ts.transpileModule(`${ts.createPrinter().printNode(ts.EmitHint.Unspecified,declaration,ast).replace(/\bexport\s+/,"")}\nthis.controller=useCaseReviewController;`,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
const origin={projectId:"p",caseId:"c",organizationId:"o",clerkActorId:"cl",nativeActorId:"n"},scope={projectId:"p",organizationId:"o",actorClerkUserId:"cl",actorId:"n"};
function harness(){
  const hooks:unknown[]=[],effects:Array<()=>void>=[],cleanups=new Map<number,()=>void>();let cursor=0,dirty=false,uuid=0,editor:ReviewController;
  const listeners=new Set<()=>void>(),sdk={loaded:true,session:{id:"A",user:{id:"cl"}} as null|{id:string;user:{id:string}},addListener:(callback:()=>void)=>{listeners.add(callback);callback();return()=>{listeners.delete(callback);};}};
  const sent:any[]=[],counts={callbacks:0,refresh:0},reads={projectAccess:{projectId:"p",requestId:"project-read",readScope:scope,canRecover:true} as any,fresh:{projectId:"p",caseId:"c",requestId:"read",readScope:scope,contentHash:"a".repeat(64),reviewStateHash:"b".repeat(64),snapshot:{case:{title:"Original"},state:{note:""}},canDecide:true,canRecover:true,supported:true} as any,origin,observedSessionId:"A",activation:"A",previewActivation:"preview-A",error:null,refresh:()=>{counts.refresh++;}};
  const params={projectId:"p",caseId:"c",active:true,readOnly:false},state={failure:null as unknown,wrong:false,onHash:null as null|(()=>void),onSend:null as null|(()=>void),onCallback:null as null|(()=>void),beforeEffects:null as null|(()=>void),callbackFail:false,hashes:0};
  const mutation={isPending:false,mutateAsync:async(input:any)=>{sent.push(input);state.onSend?.();if(state.failure)throw state.failure;return{projectId:input.projectId,caseId:input.caseId,requestId:input.requestId,requestHash:state.wrong?"c".repeat(64):await reviewDecisionHash(input),decision:input.decision,replayed:sent.length>1,readScope:scope};}};
  const context=vm.createContext({window:{Clerk:sdk},currentSessionScope,sameAuthScope,Error,structuredClone,assertReviewAck,freezeReviewInput,freezeReviewSnapshot,sameReviewReader,manualStartDefinitivelyRejected,reviewDecisionHash:async(input:any)=>{state.hashes++;state.onHash?.();return reviewDecisionHash(input);},crypto:{randomUUID:()=>`6ee2ec04-4d34-40bf-b0e9-${String(++uuid).padStart(12,"0")}`},
    useCaseReviewAccess:(_p:string,_c:string,active:boolean)=>({...reads,projectAccess:active?reads.projectAccess:null,fresh:active?reads.fresh:null}),
    useState:(initial:unknown)=>{const at=cursor++;if(!Object.hasOwn(hooks,at))hooks[at]=typeof initial==="function"?initial():initial;return[hooks[at],(value:unknown)=>{const next=typeof value==="function"?value(hooks[at]):value;if(!Object.is(next,hooks[at])){hooks[at]=next;dirty=true;}}];},
    useRef:(initial:unknown)=>{const at=cursor++;if(!Object.hasOwn(hooks,at))hooks[at]={current:initial};return hooks[at];},
    useLayoutEffect:(effect:()=>void|(()=>void),deps:unknown[])=>{const at=cursor++,prior=hooks[at] as unknown[]|undefined;if(!prior||deps.some((value,n)=>!Object.is(value,prior[n]))){hooks[at]=deps;effects.push(()=>{cleanups.get(at)?.();const cleanup=effect();if(cleanup)cleanups.set(at,cleanup);});}},
  });vm.runInContext(code,context);const controller=(context as unknown as {controller:(...args:unknown[])=>ReviewController}).controller;
  function render(){for(let n=0;n<30;n++){cursor=0;dirty=false;editor=controller(params.projectId,params.caseId,params.active,params.readOnly,mutation,()=>{counts.callbacks++;state.onCallback?.();if(state.callbackFail)throw Error("refresh failed");});const before=state.beforeEffects;state.beforeEffects=null;before?.();effects.splice(0).forEach(effect=>effect());if(!dirty)return editor;}throw Error("Controller failed to settle");}
  render();function ready(){editor.change("APPROVED",{operation:"SET",value:" \n exact "});return render();}
  return{render,ready,reads,sdk,params,state,mutation,counts,sent,emitSdk:(session:typeof sdk.session)=>{sdk.session=session;Array.from(listeners).forEach(callback=>callback());},unmount:()=>cleanups.forEach(fn=>fn()),get allocations(){return uuid;},get editor(){return editor;}};
}
describe("actual single-case review controller synthetic hooks, NOT native/browser acceptance",()=>{
  it("explicit decision sends frozen exact note/state/content/native scope once; matching ACK cannot duplicate",async()=>{const h=harness();expect(h.ready().canSave).toBe(true);await h.editor.save();h.render();expect(h.sent).toHaveLength(1);expect(h.sent[0]).toMatchObject({decision:"APPROVED",note:{operation:"SET",value:" \n exact "},expectedContentHash:"a".repeat(64),expectedReviewStateHash:"b".repeat(64),expectedNativeActorId:"n"});expect(h.editor.settled).toBe(true);await h.editor.save();expect(h.sent).toHaveLength(1);expect(h.counts).toEqual({callbacks:1,refresh:1});});
  it.each(["unmount","inactive","session-A-B-A","readOnly-A-B-A","case-reuse"])("known exact ACK after %s settles only private receipt and never UI/cache/draft",async loss=>{const h=harness();h.ready();const draft=h.editor.draft,notice=h.editor.notice;h.state.onSend=()=>{if(loss==="unmount")h.unmount();else if(loss==="inactive"){h.params.active=false;h.render();}else if(loss==="session-A-B-A"){h.reads.activation="B";h.render();h.reads.activation="A-return";h.render();}else if(loss==="readOnly-A-B-A"){h.params.readOnly=true;h.render();h.params.readOnly=false;h.render();}else{h.params.caseId="other";h.reads.fresh=null;h.render();}};await h.editor.save();h.render();expect(h.editor.pending).toBeNull();expect(h.editor.settled).toBe(true);expect(h.editor.draft).toBe(draft);expect(h.editor.notice).toBe(notice);expect(h.counts).toEqual({callbacks:0,refresh:0});await h.editor.save();expect(h.sent).toHaveLength(1);});
  it("same-tick/stale draft changes cannot replace newer choices or allocate duplicate requests",async()=>{const h=harness(),old=h.editor;h.ready();old.change("REJECTED",{operation:"CLEAR"});h.render();expect(h.editor.draft?.decision).toBe("APPROVED");h.state.onHash=()=>h.editor.change("REJECTED",{operation:"CLEAR"});await Promise.all([h.editor.save(),h.editor.save()]);expect(h.sent).toHaveLength(1);expect(h.sent[0].decision).toBe("APPROVED");});
  it("unknown request retains exact UUID/body after later unsupported/reviewed content and typed refusal",async()=>{const h=harness();h.ready();h.state.failure=Error("unknown");await h.editor.save();h.render();const held=h.editor.pending!;h.reads.fresh={...h.reads.fresh,canDecide:false,contentHash:null,reviewStateHash:null,snapshot:null};h.render();h.editor.reviewCurrent();h.state.failure={data:{code:"CONFLICT"}};await h.editor.save();h.render();expect(h.editor.pending?.input).toBe(held.input);h.state.failure=null;await h.editor.save();expect(h.sent[1]).toBe(h.sent[0]);expect(h.sent[2]).toBe(h.sent[0]);});
  it("transient native access loss/recovery revokes older handlers and effects",async()=>{const h=harness();h.ready();const old=h.editor,draft=old.draft;h.reads.fresh=null;h.render();h.reads.fresh={projectId:"p",caseId:"c",readScope:scope,contentHash:"a".repeat(64),reviewStateHash:"b".repeat(64),snapshot:{},canDecide:true,canRecover:true};h.render();old.change("REJECTED",{operation:"CLEAR"});old.reviewCurrent();await old.save();expect(h.sent).toEqual([]);expect(h.editor.draft).toBe(draft);});
  it("first proven refusal allows edit, mismatched ACK remains unknown; READ_ONLY cannot save",async()=>{const h=harness();h.ready();h.state.failure={data:{code:"BAD_REQUEST"}};await h.editor.save();h.render();expect(h.editor.pending).toBeNull();const m=harness();m.ready();m.state.wrong=true;await m.editor.save();m.render();expect(m.editor.pending?.everAmbiguous).toBe(true);const r=harness();r.params.readOnly=true;r.render().change("APPROVED",{operation:"KEEP"});await r.editor.save();expect(r.sent).toEqual([]);});
  it("stale content requires explicit re-review; retained note/decision remain exact",async()=>{const h=harness();h.ready();h.reads.fresh={...h.reads.fresh,contentHash:"c".repeat(64)};h.render();await h.editor.save();expect(h.sent).toEqual([]);h.editor.reviewCurrent();h.render();await h.editor.save();expect(h.sent[0].expectedContentHash).toBe("c".repeat(64));expect(h.sent[0].note.value).toBe(" \n exact ");});
  it("frozen note/body does not change during async hashing even when source draft is mutated",async()=>{const h=harness();h.ready();h.state.onHash=()=>{h.reads.fresh.snapshot.case.title="mutated source";};await h.editor.save();expect(h.sent[0].note.value).toBe(" \n exact ");expect(h.editor.draft?.snapshot).toMatchObject({case:{title:"Original"}});});
  it("nested baseline/arrays are immutable and known ACK cannot reopen against old pending cached hashes",async()=>{const h=harness();h.reads.fresh.snapshot.context={retained:[null,false,0,""]};h.ready();const snapshot=h.editor.draft!.snapshot as any;expect(Object.isFrozen(snapshot.case)).toBe(true);expect(Object.isFrozen(snapshot.context.retained)).toBe(true);expect(()=>snapshot.context.retained.push("drop")).toThrow();await h.editor.save();h.render();h.editor.reviewCurrent();h.editor.change("REJECTED",{operation:"CLEAR"});await h.editor.save();h.render();expect(h.editor.settled).toBe(true);expect(h.sent).toHaveLength(1);h.reads.fresh={...h.reads.fresh,contentHash:"d".repeat(64),canDecide:true};h.render();h.editor.reviewCurrent();expect(h.editor.settled).toBe(true);h.editor.change("REJECTED",{operation:"KEEP"});h.render();expect(h.editor.settled).toBe(false);expect(h.editor.draft?.contentHash).toBe("d".repeat(64));});
  it("parent refresh failure after known ACK cannot turn success into unknown",async()=>{const h=harness();h.ready();h.state.callbackFail=true;await h.editor.save();h.render();expect(h.editor.pending).toBeNull();expect(h.editor.notice).toContain("Refresh reads only");await h.editor.save();expect(h.sent).toHaveLength(1);});
  it("unused current native-reader editor can explicitly release once, stale handlers then cannot write",async()=>{const h=harness(),old=h.editor;expect(old.canRelease).toBe(true);expect(old.release()).toBe(true);h.render();expect(h.editor.readable).toBe(false);expect(old.release()).toBe(false);old.change("APPROVED",{operation:"KEEP"});await old.save();expect(h.sent).toEqual([]);});
  it("READ_ONLY original reader may release unused local instance, never a pending decision",async()=>{const h=harness();h.params.readOnly=true;h.reads.fresh.canRecover=false;h.reads.fresh.canDecide=false;h.render();expect(h.editor.release()).toBe(true);const p=harness();p.ready();p.state.failure=Error("unknown");await p.editor.save();p.render();p.params.readOnly=true;p.reads.fresh.canRecover=false;p.render();expect(p.editor.release()).toBe(false);expect(p.editor.pending).not.toBeNull();});
  it("draft/unknown/hashing/send cannot be dropped despite stale enabled release controls",async()=>{const draft=harness(),unused=draft.editor;draft.ready();expect(unused.release()).toBe(false);expect(draft.editor.release()).toBe(false);const h=harness();h.ready();const released:boolean[]=[];h.state.onHash=()=>released.push(h.editor.release());h.state.onSend=()=>released.push(h.editor.release());h.state.failure=Error("unknown");await h.editor.save();h.render();expect(released).toEqual([false,false]);expect(h.editor.release()).toBe(false);expect(h.editor.pending).not.toBeNull();});
  it("known settled exact receipt may be explicitly disposed, authority loss/return revokes old release handler",async()=>{const h=harness();h.ready();await h.editor.save();h.render();expect(h.editor.canRelease).toBe(true);const old=h.editor;h.params.active=false;h.render();h.params.active=true;h.render();expect(old.release()).toBe(false);expect(h.editor.release()).toBe(true);h.render();expect(h.editor.draft).not.toBeNull();expect(h.editor.pending).toBeNull();expect(h.sent).toHaveLength(1);});
  it.each(["deleted","reparented","foreign-link","unsupported"])("%s preview can only recover exact existing pending under current original project FULL reader, no callbacks/private body",async reason=>{const h=harness();h.ready();h.state.failure=Error("unknown");await h.editor.save();h.render();const held=h.editor.pending!,allocations=h.allocations,hashes=h.state.hashes;h.reads.fresh=null;h.reads.error=reason as never;h.render();expect(h.editor.readable).toBe(false);expect(h.editor.projectReadable).toBe(true);expect(h.editor.canSave).toBe(true);h.editor.change("REJECTED",{operation:"CLEAR"});h.editor.reviewCurrent();h.state.failure=null;await h.editor.save();h.render();expect(h.sent[1]).toBe(h.sent[0]);expect(h.sent[1]).toBe(held.input);expect(h.allocations).toBe(allocations);expect(h.state.hashes).toBe(hashes);expect(h.editor.pending).toBeNull();expect(h.editor.settled).toBe(true);expect(h.editor.notice).toContain("Historical case details remain withheld");expect(h.counts).toEqual({callbacks:0,refresh:0});expect(h.editor.release()).toBe(true);});
  it("project-only access without pending never allocates UUID/hash or sends retained unsubmitted draft",async()=>{const h=harness();h.ready();const draft=h.editor.draft,allocations=h.allocations;h.reads.fresh=null;h.render();await h.editor.save();h.editor.reviewCurrent();h.editor.change("REJECTED",{operation:"CLEAR"});h.render();expect(h.sent).toEqual([]);expect(h.state.hashes).toBe(0);expect(h.allocations).toBe(allocations);expect(h.editor.draft).toBe(draft);expect(h.editor.release()).toBe(false);});
  it.each(["READ_ONLY","revoked","native","org","Clerk"])("current project %s denial blocks exact retry and cached body",async reason=>{const h=harness();h.ready();h.state.failure=Error("unknown");await h.editor.save();h.render();const held=h.editor.pending;if(reason==="READ_ONLY")h.reads.projectAccess.canRecover=false;else if(reason==="revoked")h.reads.projectAccess=null;else h.reads.projectAccess={...h.reads.projectAccess,readScope:{...scope,...(reason==="native"?{actorId:"replacement"}:reason==="org"?{organizationId:"other"}:{actorClerkUserId:"other"})}};h.reads.fresh=null;h.render();expect(h.editor.canSave).toBe(false);await h.editor.save();expect(h.sent).toHaveLength(1);expect(h.editor.pending).toBe(held);expect(h.editor.readable).toBe(false);});
  it("project access A-B-A and preview loss revoke old recovery handlers; matching late ACK only privately settles",async()=>{const h=harness();h.ready();h.state.failure=Error("unknown");await h.editor.save();h.render();h.reads.fresh=null;h.render();const old=h.editor;h.reads.projectAccess=null;h.render();h.reads.projectAccess={projectId:"p",requestId:"new",readScope:scope,canRecover:true};h.reads.activation="new-project";h.render();await old.save();expect(h.sent).toHaveLength(1);h.state.failure=null;h.state.onSend=()=>{h.params.active=false;h.render();h.params.active=true;h.reads.activation="return";h.render();};await h.editor.save();h.render();expect(h.editor.pending).toBeNull();expect(h.editor.settled).toBe(true);expect(h.counts).toEqual({callbacks:0,refresh:0});});
  it("unsupported actual preview hides historical snapshot/note and private SDK notices; recovery errors stay generic",async()=>{const h=harness();h.ready();h.state.failure=Error("private-sdk-body");await h.editor.save();h.render();expect(h.editor.notice).toBe("private-sdk-body");h.reads.fresh={...h.reads.fresh,supported:false,snapshot:null,contentHash:null,reviewStateHash:null,canDecide:false};h.render();expect(h.editor.readable).toBe(false);expect(h.editor.notice).toBe("");await h.editor.save();h.render();expect(h.editor.notice).not.toContain("private-sdk-body");expect(h.editor.notice).toContain("historical case details are withheld");expect(h.editor.pending).not.toBeNull();});
  it.each(["session","user","unloaded","missing"])("actual SDK %s loss before any React commit forbids edit/hash/save/release, and A-B-A cannot revive admitted reads",async loss=>{const h=harness();h.ready();const draft=h.editor.draft,old=h.editor,allocations=h.allocations;if(loss==="session")h.sdk.session={id:"B",user:{id:"cl"}};if(loss==="user")h.sdk.session={id:"A",user:{id:"other"}};if(loss==="unloaded")h.sdk.loaded=false;if(loss==="missing")h.sdk.session=null;old.change("REJECTED",{operation:"CLEAR"});old.reviewCurrent();await old.save();expect(old.release()).toBe(false);expect(h.sent).toEqual([]);expect(h.allocations).toBe(allocations);expect(h.state.hashes).toBe(0);h.sdk.loaded=true;h.sdk.session={id:"A",user:{id:"cl"}};h.render();expect(h.editor.readable).toBe(false);expect(h.editor.projectReadable).toBe(false);expect(h.editor.draft).toBe(draft);await h.editor.save();expect(h.sent).toEqual([]);h.reads.activation="new-native-reader-A";h.reads.previewActivation="new-private-A";h.render();expect(h.editor.readable).toBe(true);await old.save();expect(h.sent).toEqual([]);await h.editor.save();expect(h.sent).toHaveLength(1);});
  it("SDK loss during hash before hook commit sends nothing and keeps draft private until a fresh original native activation",async()=>{const h=harness();h.ready();const draft=h.editor.draft;h.state.onHash=()=>{h.sdk.session={id:"B",user:{id:"cl"}};};await h.editor.save();expect(h.sent).toEqual([]);h.sdk.session={id:"A",user:{id:"cl"}};h.render();expect(h.editor.readable).toBe(false);expect(h.editor.draft).toBe(draft);expect(h.editor.pending).toBeNull();expect(h.editor.notice).toBe("");});
  it.each(["exact-ACK","rejected","malformed"])("SDK changes before React commit on %s: every response/finally revokes publication; exact ACK settles privately only",async result=>{const h=harness();h.ready();const draft=h.editor.draft;h.state.onSend=()=>{h.sdk.session={id:"B",user:{id:"cl"}};};if(result==="rejected")h.state.failure=Error("private-sdk-rejection-body");if(result==="malformed")h.state.wrong=true;await h.editor.save();h.sdk.session={id:"A",user:{id:"cl"}};h.render();expect(h.editor.projectReadable).toBe(false);expect(h.editor.readable).toBe(false);expect(h.editor.canSave).toBe(false);expect(h.editor.canRelease).toBe(false);expect(h.editor.notice).toBe("");expect(h.editor.draft).toBe(draft);expect(h.counts).toEqual({callbacks:0,refresh:0});if(result==="exact-ACK"){expect(h.editor.pending).toBeNull();expect(h.editor.settled).toBe(true);}else{expect(h.editor.pending?.everAmbiguous).toBe(true);}await h.editor.save();expect(h.sent).toHaveLength(1);});
  it("exact pending may use renewed session only after genuine new native original-reader admission, not permanent origin rebinding",async()=>{const h=harness();h.ready();h.state.failure=Error("unknown");await h.editor.save();h.render();const held=h.editor.pending!,origin=h.reads.origin;h.sdk.session={id:"renewed",user:{id:"cl"}};await h.editor.save();h.render();expect(h.sent).toHaveLength(1);expect(h.editor.projectReadable).toBe(false);h.reads.observedSessionId="renewed";h.reads.activation="fresh-native-renewed";h.reads.previewActivation="fresh-private-renewed";h.state.failure=null;h.render();await h.editor.save();h.render();expect(h.sent[1]).toBe(held.input);expect(h.reads.origin).toBe(origin);expect(h.editor.pending).toBeNull();});
  it("SDK loss in parent callback prevents subsequent refresh and late finally cannot publish actionable old frame",async()=>{const h=harness();h.ready();h.state.onCallback=()=>{h.sdk.session={id:"B",user:{id:"cl"}};};await h.editor.save();h.sdk.session={id:"A",user:{id:"cl"}};h.render();expect(h.counts).toEqual({callbacks:1,refresh:0});expect(h.editor.pending).toBeNull();expect(h.editor.settled).toBe(true);expect(h.editor.projectReadable).toBe(false);expect(h.editor.notice).toBe("");});
  it("SDK resource listener revokes before hook context changes; listener A-B-A cannot restore old private DOM",()=>{const h=harness();h.ready();h.emitSdk({id:"B",user:{id:"cl"}});h.emitSdk({id:"A",user:{id:"cl"}});h.render();expect(h.editor.projectReadable).toBe(false);expect(h.editor.readable).toBe(false);expect(h.editor.draft).not.toBeNull();h.reads.activation="fresh-native-reader";h.reads.previewActivation="fresh-private-reader";h.render();expect(h.editor.readable).toBe(true);});
  it("SDK movement between render and layout commit is caught by immediate listener emission before private publication",()=>{const h=harness();h.ready();h.reads.activation="new-native";h.state.beforeEffects=()=>{h.sdk.session={id:"B",user:{id:"cl"}};};h.render();expect(h.editor.readable).toBe(false);h.sdk.session={id:"A",user:{id:"cl"}};h.render();expect(h.editor.readable).toBe(false);expect(h.editor.projectReadable).toBe(false);});
});
