import { readFileSync } from "node:fs";
import vm from "node:vm";
import ts from "typescript";
import { describe, expect, it } from "vitest";
import { currentSessionScope, sameAuthScope } from "./auth-query-cache";
import { decodeStepReviewWire, sameStepReviewReader } from "./step-execution-review-draft";
const source = readFileSync(new URL("./use-step-execution-review-access.ts", import.meta.url), "utf8"), ast = ts.createSourceFile("access.ts", source, ts.ScriptTarget.Latest, true);
const declarations = ast.statements.filter(node => ts.isFunctionDeclaration(node));
const code = ts.transpileModule(declarations.map(node => ts.createPrinter().printNode(ts.EmitHint.Unspecified, node, ast).replace(/\bexport\s+/, "")).join("\n") + "\nthis.access=useStepExecutionReviewAccess;", { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.None } }).outputText;
function harness() {
  const hooks: unknown[] = [], cleanups = new Map<number, () => void>(), effects: Array<() => void> = [], listeners = new Set<() => void>();
  const auth = { isLoaded: true, isSignedIn: true, userId: "cl", sessionId: "A" }, sdk = { loaded: true, session: { id: "A", user: { id: "cl" } } as null | { id: string; user: { id: string } }, addListener: (fn: () => void) => { listeners.add(fn); fn(); return () => { listeners.delete(fn); }; } };
  const params = { projectId: "p", testRunId: "r", testCaseId: "c", stepIndex: 0, visible: true }, query = { error: null as unknown, isFetching: false, isPaused: false, isFetchedAfterMount: true, wrong: "", supported: true };
  const requests: Array<{ input: Record<string, unknown>; options: { enabled: boolean } }> = []; let cursor = 0, dirty = false, counter = 0, reads: ReturnType<typeof import("./use-step-execution-review-access").useStepExecutionReviewAccess>, beforeCommit: (() => void) | null = null;
  const context = vm.createContext({ window: { Clerk: sdk }, Object, JSON, currentSessionScope, sameAuthScope, decodeStepReviewWire, sameStepReviewReader, crypto: { randomUUID: () => `6ee2ec04-4d34-40bf-b0e9-${String(++counter).padStart(12, "0")}` }, useAuth: () => auth,
    useState: (initial: unknown) => { const index = cursor++; if (!Object.hasOwn(hooks, index)) hooks[index] = typeof initial === "function" ? initial() : initial; return [hooks[index], (value: unknown) => { const next = typeof value === "function" ? value(hooks[index]) : value; if (!Object.is(next, hooks[index])) { hooks[index] = next; dirty = true; } }]; },
    useRef: (initial: unknown) => { const index = cursor++; if (!Object.hasOwn(hooks, index)) hooks[index] = { current: initial }; return hooks[index]; },
    useMemo: (fn: () => unknown, deps: unknown[]) => { const index = cursor++, previous = hooks[index] as { deps: unknown[]; value: unknown } | undefined; if (!previous || deps.some((value, n) => !Object.is(value, previous.deps[n]))) hooks[index] = { deps, value: fn() }; return (hooks[index] as { value: unknown }).value; },
    useLayoutEffect: (fn: () => void | (() => void), deps: unknown[]) => { const index = cursor++, previous = hooks[index] as unknown[] | undefined; if (!previous || deps.some((value, n) => !Object.is(value, previous[n]))) { hooks[index] = deps; effects.push(() => { cleanups.get(index)?.(); const cleanup = fn(); if (cleanup) cleanups.set(index, cleanup); }); } },
    trpcReact: { manualStepExecutionReview: { preview: { useQuery: (input: Record<string, unknown>, options: { enabled: boolean }) => { requests.push({ input, options }); const scope = { projectId: "p", organizationId: query.wrong === "org" ? "foreign" : "o", actorId: query.wrong === "native" ? "replacement" : "n", actorClerkUserId: query.wrong === "Clerk" ? "other" : "cl" }; return { ...query, data: { projectId: "p", testRunId: "r", testCaseId: "c", stepIndex: input.stepIndex, readRequestId: query.wrong === "nonce" ? "00000000-0000-4000-8000-000000000000" : input.readRequestId, scope, canRecover: true, canRecord: query.supported, supported: query.supported, blockedReason: null, frozenDefinition: query.supported ? { testCaseId: "c", steps: [{ order: 0, action: "First" }, { order: 1, action: "Next" }] } : null, current: null, rawCurrent: null, procedureHash: query.supported ? "a".repeat(64) : null, currentFingerprint: query.supported ? "b".repeat(64) : null, provenance: "CURRENT_AUTHORITY_LEGACY_ORIGINAL_TENANCY_UNRECORDED" } }; } } } } });
  vm.runInContext(code, context); const invokeAccess = (context as { access: (...args: unknown[]) => typeof reads }).access;
  function render() { for (let n = 0; n < 40; n++) { cursor = 0; dirty = false; reads = invokeAccess(params.projectId, params.testRunId, params.testCaseId, params.stepIndex, params.visible); beforeCommit?.(); beforeCommit = null; effects.splice(0).forEach(fn => fn()); if (!dirty) return reads; } throw Error("Reader failed to settle."); }
  render(); return { auth, sdk, params, query, requests, render, get reads() { return reads; }, beforeCommit: (fn: () => void) => { beforeCommit = fn; }, emit: (session: typeof sdk.session) => { sdk.session = session; Array.from(listeners).forEach(fn => fn()); } };
}
describe("actual step reader hook synthetic nonce/resource guards, no native acceptance", () => {
  it("bootstraps current native origin then pins all three identities; step selection does not rebind native case context", () => { const h = harness(), origin = h.reads.origin; expect(h.reads.fresh).not.toBeNull(); expect(h.requests.at(-1)?.input).toMatchObject({ originalOrganizationId: "o", expectedClerkActorId: "cl", expectedNativeActorId: "n" }); h.params.stepIndex = 1; h.render(); expect(h.reads.origin).toMatchObject({ ...origin, stepIndex: 1 }); expect(h.reads.fresh?.stepIndex).toBe(1); });
  it.each(["nonce", "native", "org", "Clerk"])("%s mismatch refuses cached body and never overwrites original native identity", wrong => { const h = harness(), origin = h.reads.origin; h.query.wrong = wrong; expect(h.render().fresh).toBeNull(); expect(h.reads.origin).toBe(origin); });
  it("fetch/error/paused/incomplete states are not freshly admitted native reads", () => { for (const key of ["isFetching", "error", "isPaused", "isFetchedAfterMount"]) { const h = harness(); Object.assign(h.query, { [key]: key === "error" ? Error("private") : key !== "isFetchedAfterMount" }); expect(h.render().fresh).toBeNull(); } });
  it("close/reopen and explicit refresh rotate native read UUID while retaining origin", () => { const h = harness(), origin = h.reads.origin, first = h.reads.activation; h.params.visible = false; expect(h.render().fresh).toBeNull(); h.params.visible = true; expect(h.render().activation).not.toBe(first); const prior = h.reads.activation; h.reads.refresh(); expect(h.render().activation).not.toBe(prior); expect(h.reads.origin).toBe(origin); });
  it("SDK-only listener A-B-A rotates activation before auth hook changes; old refresh cannot revive cache", () => { const h = harness(), first = h.reads.activation, refresh = h.reads.refresh; h.emit({ id: "B", user: { id: "cl" } }); h.emit({ id: "A", user: { id: "cl" } }); refresh(); expect(h.auth.sessionId).toBe("A"); expect(h.render().activation).not.toBe(first); expect(h.reads.fresh).not.toBeNull(); });
  it("movement between render and layout commit is caught by immediate installed-listener emission", () => { const h = harness(); h.reads.refresh(); h.beforeCommit(() => { h.sdk.session = { id: "B", user: { id: "cl" } }; }); expect(h.render().fresh).toBeNull(); expect(h.requests.at(-1)?.options.enabled).toBe(false); });
  it("refused or malformed preview can explicitly request a new nonce without using old body as permission", () => { for (const refused of ["query-error", "nonce", "native"]) { const h = harness(), origin = h.reads.origin; if (refused === "query-error") h.query.error = Error("private"); else h.query.wrong = refused; h.render(); expect(h.reads.fresh).toBeNull(); const old = h.reads.activation; h.reads.refresh(); expect(h.render().activation).not.toBe(old); expect(h.reads.fresh).toBeNull(); expect(h.reads.origin).toBe(origin); h.query.error = null; h.query.wrong = ""; expect(h.render().fresh?.readRequestId).toBe(h.reads.activation); } });
  it("SDK restoration permits only current intent to request another nonce, never an old activation or another actor", () => { const h = harness(), oldRefresh = h.reads.refresh, old = h.reads.activation; h.query.error = Error("private"); h.emit({ id: "B", user: { id: "cl" } }); h.render(); h.emit({ id: "A", user: { id: "cl" } }); h.render(); const restored = h.reads.activation; expect(restored).not.toBe(old); oldRefresh(); expect(h.render().activation).toBe(restored); h.reads.refresh(); expect(h.render().activation).not.toBe(restored); expect(h.reads.fresh).toBeNull(); const beforeForeign = h.reads.activation; h.emit({ id: "A", user: { id: "other" } }); h.render(); const foreign = h.reads.activation; expect(foreign).not.toBe(beforeForeign); h.reads.refresh(); expect(h.render().activation).toBe(foreign); expect(h.requests.at(-1)?.options.enabled).toBe(false); });
  it("unsupported preview carries genuine recovery scope but no fabricated body; another case cannot adopt", () => { const h = harness(); h.query.supported = false; expect(h.render().fresh).toMatchObject({ supported: false, canRecover: true, frozenDefinition: null }); h.params.testCaseId = "other"; expect(h.render().fresh).toBeNull(); expect(h.requests.at(-1)?.options.enabled).toBe(false); });
});
