import { readFileSync } from "node:fs";
import vm from "node:vm";
import ts from "typescript";
import { describe,expect,it } from "vitest";
import { sameReviewReader } from "./case-review-decision-draft";
const source=readFileSync(new URL("./use-case-review-access.ts",import.meta.url),"utf8"),ast=ts.createSourceFile("access.ts",source,ts.ScriptTarget.Latest,true),declaration=ast.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==="useCaseReviewAccess")!;
const code=ts.transpileModule(`${ts.createPrinter().printNode(ts.EmitHint.Unspecified,declaration,ast).replace(/\bexport\s+/,"")}\nthis.access=useCaseReviewAccess;`,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
function harness(){const hooks:unknown[]=[],auth={isLoaded:true,isSignedIn:true,userId:"cl",sessionId:"A"},params={projectId:"p",caseId:"c",active:true},queryState={error:null as unknown,isFetching:false,isPaused:false,isFetchedAfterMount:true,wrong:null as string|null},requests:any[]=[];let cursor=0,dirty=false,uuid=0,reads:any;
  const context=vm.createContext({sameReviewReader,crypto:{randomUUID:()=>`6ee2ec04-4d34-40bf-b0e9-${String(++uuid).padStart(12,"0")}`},useAuth:()=>auth,useState:(initial:unknown)=>{const at=cursor++;if(!Object.hasOwn(hooks,at))hooks[at]=initial;return[hooks[at],(value:unknown)=>{const next=typeof value==="function"?value(hooks[at]):value;if(!Object.is(next,hooks[at])){hooks[at]=next;dirty=true;}}];},trpcReact:{caseReview:{preview:{useQuery:(input:any,options:any)=>{requests.push({input,options});const data={projectId:input.projectId,caseId:input.caseId,requestId:input.requestId,readScope:{projectId:input.projectId,organizationId:"o",actorId:"n",actorClerkUserId:"cl"},snapshot:{},contentHash:"a".repeat(64),reviewStateHash:"b".repeat(64),canRecover:true,canDecide:true};if(queryState.wrong==="nonce")data.requestId="stale";if(queryState.wrong==="native")data.readScope.actorId="replacement";if(queryState.wrong==="org")data.readScope.organizationId="foreign";return{...queryState,data};}}}}});vm.runInContext(code,context);const fn=(context as any).access;
  function render(){for(let n=0;n<30;n++){cursor=0;dirty=false;reads=fn(params.projectId,params.caseId,params.active);if(!dirty)return reads;}throw Error("Access did not settle");}render();return{auth,params,queryState,requests,render,get reads(){return reads;}};
}
describe("actual review access hook synthetic current nonce/native reader",()=>{
  it("completes original native discovery then pinned second read without custom-field schema",()=>{const h=harness();expect(h.reads.fresh).not.toBeNull();expect(h.requests.at(-1).input).toMatchObject({originalOrganizationId:"o",expectedClerkActorId:"cl",expectedNativeActorId:"n"});expect(h.reads.origin).toMatchObject({projectId:"p",caseId:"c",nativeActorId:"n"});});
  it.each(["nonce","native","org"])("%s echo mismatch withholds snapshot and never rebinds origin",wrong=>{const h=harness(),origin=h.reads.origin;h.queryState.wrong=wrong;expect(h.render().fresh).toBeNull();expect(h.reads.origin).toBe(origin);});
  it("error/fetch/paused/incomplete cached rows are not current private reads",()=>{for(const key of["error","isFetching","isPaused","isFetchedAfterMount"]){const h=harness();(h.queryState as any)[key]=key==="error"?Error("revoked"):key!=="isFetchedAfterMount";expect(h.render().fresh).toBeNull();}});
  it("session/activation A-B-A rotates request UUID and retains native scope; other account/project/case cannot adopt",()=>{const h=harness(),first=h.reads.activation,origin=h.reads.origin;h.auth.sessionId="B";const b=h.render().activation;h.auth.sessionId="A";expect(h.render().activation).not.toBe(first);expect(b).not.toBe(first);h.auth.userId="other";expect(h.render().fresh).toBeNull();expect(h.requests.at(-1).options.enabled).toBe(false);h.auth.userId="cl";h.params.projectId="other";expect(h.render().fresh).toBeNull();h.params.projectId="p";h.params.caseId="other";expect(h.render().fresh).toBeNull();expect(h.reads.origin).toBe(origin);});
  it("close/reopen and explicit refresh invalidate previous native activation, not origin",()=>{const h=harness(),first=h.reads.activation,origin=h.reads.origin;h.params.active=false;expect(h.render().fresh).toBeNull();h.params.active=true;expect(h.render().activation).not.toBe(first);const before=h.reads.activation;h.reads.refresh();expect(h.render().activation).not.toBe(before);expect(h.reads.origin).toBe(origin);});
});
