import { randomUUID } from "node:crypto";
import { describe,expect,it } from "vitest";
import { reviewDecisionInput,reviewPageInput,reviewRequestHash,reviewSnapshotHashes } from "./caseReviewSchema.js";
const snapshot = () => ({ kind: "CaseReviewSnapshot/v1" as const,case: { title: " Exact\n title ",customFields: { future: [null,false,0,""] } },authoredSteps: [],effectiveSteps: [],sharedProcedure: null,prerequisites: [],context: { schema: null },source: null,aiBaseline: null,state: { status: "PENDING_REVIEW" as const,archived: false,reviewedById: null,reviewedAt: null,note: "",origin: "AI_APP_SCAN",confidence: null } });
describe("explicit review-local schema/hash; no global revision or defaults", () => {
  it("metadata/context/provenance changes invalidate content; trust changes separately invalidate state", () => {
    const first = snapshot(), before = reviewSnapshotHashes(first); first.case.customFields.future.push("new"); const metadata = reviewSnapshotHashes(first); expect(metadata.contentHash).not.toBe(before.contentHash); expect(metadata.reviewStateHash).toBe(before.reviewStateHash);
    first.state.note = " retained "; const note = reviewSnapshotHashes(first); expect(note.contentHash).toBe(metadata.contentHash); expect(note.reviewStateHash).not.toBe(metadata.reviewStateHash);
  });
  it("NULL, empty, whitespace, false, zero and array ordering stay distinct", () => { const hashes = [null,""," ",false,0,["a","b"],["b","a"]].map(value => reviewSnapshotHashes({ ...snapshot(),case: { value } }).contentHash); expect(new Set(hashes).size).toBe(hashes.length); });
  it("explicit KEEP/CLEAR/empty SET notes are separate requests, no trimming or omitted default", () => { const base = { projectId: "p",caseId: "c",originalOrganizationId: "o",expectedClerkActorId: "cl",expectedNativeActorId: "n",expectedContentHash: "a".repeat(64),expectedReviewStateHash: "b".repeat(64),decision: "APPROVED" as const,requestId: randomUUID(),confirmed: true as const }; const notes = [{operation:"KEEP" as const},{operation:"CLEAR" as const},{operation:"SET" as const,value:""},{operation:"SET" as const,value:" \n "}]; expect(new Set(notes.map(note => reviewRequestHash(reviewDecisionInput.parse({...base,note})))).size).toBe(4); expect(reviewDecisionInput.safeParse(base).success).toBe(false); });
  it("later queue page requires explicit population binding", () => { const input = { projectId:"p",requestId:randomUUID(),search:"",sort:"title",offset:25 }; expect(reviewPageInput.safeParse(input).success).toBe(false); expect(reviewPageInput.safeParse({...input,populationHash:"a".repeat(64)}).success).toBe(true); });
  it("complete snapshot byte/depth admission refuses instead of truncating", () => { expect(() => reviewSnapshotHashes({...snapshot(),case:{text:"x".repeat(524289)}})).toThrow(); let value:unknown=null; for(let n=0;n<70;n++)value={value}; expect(()=>reviewSnapshotHashes({...snapshot(),case:value})).toThrow(); });
  it("complete project quality context and unknown siblings bind human review without normalization",()=>{const first={...snapshot(),context:{projectQualityProfile:{objective:" Original ",future:{retained:[null,false,0,""]}},fieldSchema:{fields:[]}}},before=reviewSnapshotHashes(first);first.context.projectQualityProfile.future.retained.push("changed");expect(reviewSnapshotHashes(first).contentHash).not.toBe(before.contentHash);expect(first.context.projectQualityProfile.objective).toBe(" Original ");});
});
