import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { TRPCError } from "@trpc/server";
import { beforeEach,describe,expect,it,vi } from "vitest";
const locks=vi.hoisted(()=>({project:vi.fn(),actor:vi.fn(),read:vi.fn()}));
vi.mock("./caseFields.js",async original=>({...await original<typeof import("./caseFields.js")>(),lockCaseFieldProject:locks.project}));
vi.mock("./caseFieldReadScope.js",async original=>({...await original<typeof import("./caseFieldReadScope.js")>(),lockCurrentCaseFieldActor:locks.actor,lockCaseFieldReadScope:locks.read}));
import { decideCaseReview,previewCaseReview,pageCaseReviewQueue,countCaseReviewQueue } from "./caseReview.js";
import { reviewRequestHash,reviewSnapshotHashes } from "./caseReviewSchema.js";
const scope={projectId:"p",organizationId:"o",actorId:"n",actorClerkUserId:"cl"};
function fixture(){
  const snapshot={kind:"CaseReviewSnapshot/v1" as const,case:{id:"c",title:" Exact\n text ",customFields:{retained:[null,false,0,""]},priority:"MEDIUM",testType:"FUNCTIONAL",validationDomain:"SOFTWARE"},authoredSteps:[{order:0,action:" Click ",expectedActionOrData:" GET /api ",expectedResult:"",expectedResponse:null,mediaAttachmentIds:[]}],effectiveSteps:[{order:0,action:" Click ",expectedActionOrData:" GET /api ",expectedResult:"",expectedResponse:null,mediaAttachmentIds:[]}],sharedProcedure:null,prerequisites:[],context:{fieldSchema:{version:1,fields:[]}},source:null,aiBaseline:{value:null,sqlNull:true},state:{status:"PENDING_REVIEW" as "PENDING_REVIEW"|"APPROVED",archived:false,reviewedById:null,reviewedAt:null,note:" retained ",origin:"AI_APP_SCAN",confidence:null}};
  const input={projectId:"p",caseId:"c",originalOrganizationId:"o",expectedClerkActorId:"cl",expectedNativeActorId:"n",expectedContentHash:reviewSnapshotHashes(snapshot).contentHash,expectedReviewStateHash:reviewSnapshotHashes(snapshot).reviewStateHash,decision:"APPROVED" as const,note:{operation:"KEEP" as const},requestId:randomUUID(),confirmed:true as const};
  const events:string[]=[],state={role:"EDITOR",seatType:"FULL",org:"o",prior:[] as Array<{organizationId:string;requestHash:string;decision:string}>,foreign:false,unsupported:false,missing:false,bytes:1000n,customBytes:20n,definitionBytes:30n,steps:1n,prerequisites:0n,sharedSteps:1,exact:true,changed:1,population:30n,populationBytes:2000n,populationUnsupported:false,digest:"a".repeat(32),rows:Array.from({length:25},(_,index)=>({id:`c${index}`,displayId:`TC-${index+1}`,title:"Current",confidence:null,sourceFilePath:null as string|null}))};
  const tx={
    $executeRaw:vi.fn(async()=>0),$queryRaw:vi.fn(async(raw:{sql:string}|readonly string[])=>{const sql=Array.isArray(raw)?raw.join("?"):(raw as {sql:string}).sql;
      if(sql.includes("'CaseReviewDecision/v1'")){events.push("receipt");return state.prior;}
      if(sql.includes('FOR UPDATE')){events.push("case-lock");return[{id:"c"}];}
      if(sql.includes(" AS foreign")){events.push("relationships");return[{foreign:state.foreign,unsupported:state.unsupported,missing:state.missing}];}
      if(sql.includes('AS "customBytes"')){events.push("complete-admission");return[{bytes:state.bytes,customBytes:state.customBytes,definitionBytes:state.definitionBytes,steps:state.steps,prerequisites:state.prerequisites,sharedSteps:state.sharedSteps}];}
      if(sql.includes(' AS "sharedSteps"')&&!sql.includes(' AS snapshot')){events.push("raw-admission");return[{bytes:state.bytes,steps:state.steps,prerequisites:state.prerequisites,sharedSteps:state.sharedSteps}];}
      if(sql.includes(' AS exact,')){events.push("exact-roundtrip");return[{exact:state.exact,bytes:state.bytes}];}
      if(sql.includes('FOR SHARE')){events.push("relation-lock");return[{count:1n}];}
      if(sql.includes(' AS snapshot')){events.push("private-snapshot");return[{snapshot}];}
      if(sql.includes(' AS unsupported')){events.push("metadata-admission");return[{count:state.population,bytes:state.populationBytes,unsupported:state.populationUnsupported}];}
      if(sql.includes(' AS digest')){events.push("native-digest");return[{digest:state.digest,count:state.population}];}
      if(sql.includes('AS "sourceFilePath"')){events.push("metadata-page");return state.rows;}
      throw Error("Unexpected mocked review SQL");}),
    membership:{findUniqueOrThrow:vi.fn(async()=>({role:state.role,seatType:state.seatType}))},project:{findUniqueOrThrow:vi.fn(async()=>({organizationId:state.org}))},
    testCase:{updateMany:vi.fn(async()=>{events.push("review-only-update");return{count:state.changed};})},auditLog:{create:vi.fn(async()=>{events.push("atomic-audit");return{};})}
  };
  const db={$transaction:vi.fn(async(fn:(arg:typeof tx)=>unknown,opts:unknown)=>{expect(opts).toMatchObject({isolationLevel:"RepeatableRead",timeout:10000,maxWait:5000});return fn(tx);})};
  locks.project.mockImplementation(async()=>{events.push("full-current-auth");});locks.actor.mockImplementation(async()=>{events.push("native-current-actor");return"cl";});locks.read.mockImplementation(async()=>{events.push("current-read-auth");return scope;});
  return{snapshot,input,state,events,tx,db:db as never};
}
beforeEach(()=>{Object.values(locks).forEach(lock=>lock.mockReset());});
describe("single-case review native SQL contracts MOCKED only; actual SQL/fixtures NOT RUN",()=>{
  it("source promotes first raw scalar byte length before additions; oversized mocked bigint admission refuses before bodies",async()=>{const source=readFileSync(new URL("./caseReview.ts",import.meta.url),"utf8");expect(source).toContain('c.origin,c.confidence))::bigint+coalesce(octet_length(p."caseFieldSchema"::text),0)');const h=fixture();h.state.bytes=3000000000n;await expect(decideCaseReview(h.db,"n",h.input,{clerkActorId:"cl"})).rejects.toMatchObject({code:"PRECONDITION_FAILED"});expect(h.events).not.toContain("complete-admission");expect(h.events).not.toContain("private-snapshot");expect(h.tx.testCase.updateMany).not.toHaveBeenCalled();});
  it("writes only pending review columns, KEEP never resends note/content, atomically audits exact UUID hashes",async()=>{const h=fixture(),ack=await decideCaseReview(h.db,"n",h.input,{clerkActorId:"cl"});expect(ack).toMatchObject({requestHash:reviewRequestHash(h.input),readScope:scope,replayed:false,decision:"APPROVED"});expect(h.tx.testCase.updateMany.mock.calls[0]![0]).toMatchObject({where:{id:"c",projectId:"p",archived:false,reviewStatus:"PENDING_REVIEW"},data:{reviewStatus:"APPROVED",reviewedById:"n",updatedById:"n"}});expect(h.tx.testCase.updateMany.mock.calls[0]![0].data).not.toHaveProperty("reviewNote");expect(h.events.indexOf("complete-admission")).toBeLessThan(h.events.indexOf("private-snapshot"));expect(h.events.indexOf("exact-roundtrip")).toBeLessThan(h.events.indexOf("review-only-update"));expect(h.events.slice(-2)).toEqual(["review-only-update","atomic-audit"]);});
  it.each(["org","native","Clerk","FULL"])("current %s refusal precedes private receipt/body",async reason=>{const h=fixture();if(reason==="org")h.state.org="other";if(reason==="native")h.input.expectedNativeActorId="other";if(reason==="Clerk")h.input.expectedClerkActorId="other";if(reason==="FULL")locks.project.mockRejectedValue(new TRPCError({code:"FORBIDDEN"}));await expect(decideCaseReview(h.db,"n",h.input,{clerkActorId:"cl"})).rejects.toMatchObject({code:"FORBIDDEN"});expect(h.events).not.toContain("receipt");expect(h.events).not.toContain("private-snapshot");});
  it("exact accepted UUID recovers before later unsupported/oversize/approved snapshot",async()=>{const h=fixture();h.state.prior=[{organizationId:"o",requestHash:reviewRequestHash(h.input),decision:"APPROVED"}];h.state.unsupported=true;h.state.bytes=99999999n;h.snapshot.state.status="APPROVED";expect((await decideCaseReview(h.db,"n",h.input,{clerkActorId:"cl"})).replayed).toBe(true);expect(h.events).toEqual(["full-current-auth","native-current-actor","receipt"]);expect(h.tx.testCase.updateMany).not.toHaveBeenCalled();});
  it.each(["hash","decision","org","duplicate"])("receipt %s disagreement never starts another write",async kind=>{const h=fixture();h.state.prior=[{organizationId:kind==="org"?"foreign":"o",requestHash:kind==="hash"?"b".repeat(64):reviewRequestHash(h.input),decision:kind==="decision"?"REJECTED":"APPROVED"}];if(kind==="duplicate")h.state.prior.push(h.state.prior[0]!);await expect(decideCaseReview(h.db,"n",h.input,{clerkActorId:"cl"})).rejects.toBeInstanceOf(TRPCError);expect(h.tx.testCase.updateMany).not.toHaveBeenCalled();expect(h.events).not.toContain("relationships");});
  it.each([{bytes:524289n},{bytes:3000000000n},{bytes:-1n},{steps:501n},{prerequisites:51n},{sharedSteps:501},{customBytes:65537n},{definitionBytes:32769n}])("native whole snapshot bounds refuse before private body",async patch=>{const h=fixture();Object.assign(h.state,patch);await expect(decideCaseReview(h.db,"n",h.input,{clerkActorId:"cl"})).rejects.toMatchObject({code:"PRECONDITION_FAILED"});expect(h.events).not.toContain("private-snapshot");expect(h.tx.testCase.updateMany).not.toHaveBeenCalled();});
  it("foreign relationships refuse before any foreign sizes/body; unsupported cases remain honestly unreviewable",async()=>{for(const flag of["foreign","unsupported","missing"] as const){const h=fixture();h.state[flag]=true;await expect(decideCaseReview(h.db,"n",h.input,{clerkActorId:"cl"})).rejects.toMatchObject({code:flag==="foreign"?"FORBIDDEN":"PRECONDITION_FAILED"});expect(h.events).not.toContain("raw-admission");expect(h.tx.testCase.updateMany).not.toHaveBeenCalled();}});
  it("precision or complete content/state CAS change refuses; no custom metadata substitution",async()=>{for(const kind of["precision","content","state"]){const h=fixture();if(kind==="precision")h.state.exact=false;if(kind==="content")h.input.expectedContentHash="b".repeat(64);if(kind==="state")h.input.expectedReviewStateHash="b".repeat(64);await expect(decideCaseReview(h.db,"n",h.input,{clerkActorId:"cl"})).rejects.toMatchObject({code:kind==="precision"?"PRECONDITION_FAILED":"CONFLICT"});expect(h.tx.testCase.updateMany).not.toHaveBeenCalled();}});
  it("deep retained JSON refuses before stringify/roundtrip",async()=>{const h=fixture();let value:unknown=null;for(let n=0;n<70;n++)value={value};h.snapshot.case.customFields=value as never;await expect(decideCaseReview(h.db,"n",h.input,{clerkActorId:"cl"})).rejects.toMatchObject({code:"PRECONDITION_FAILED"});expect(h.events).not.toContain("exact-roundtrip");});
  it("explicit CLEAR and SET preserve NULL/empty/whitespace note distinctions without whole case replacement",async()=>{for(const note of[{operation:"CLEAR" as const},{operation:"SET" as const,value:""},{operation:"SET" as const,value:" \n "}]){const h=fixture();await decideCaseReview(h.db,"n",{...h.input,note},{clerkActorId:"cl"});expect(h.tx.testCase.updateMany.mock.calls[0]![0].data).toMatchObject({reviewNote:note.operation==="CLEAR"?null:note.value});expect(Object.keys(h.tx.testCase.updateMany.mock.calls[0]![0].data).sort()).toEqual(["reviewNote","reviewStatus","reviewedAt","reviewedById","updatedById"].sort());}});
  it("approved/archived current state refuses even with exact new hashes; zero updated rows does not create receipt",async()=>{for(const kind of["approved","archived","zero"]){const h=fixture();if(kind==="approved")h.snapshot.state.status="APPROVED";if(kind==="archived")h.snapshot.state.archived=true;if(kind==="zero")h.state.changed=0;const hashes=reviewSnapshotHashes(h.snapshot);await expect(decideCaseReview(h.db,"n",{...h.input,expectedContentHash:hashes.contentHash,expectedReviewStateHash:hashes.reviewStateHash},{clerkActorId:"cl"})).rejects.toMatchObject({code:kind==="zero"?"CONFLICT":"PRECONDITION_FAILED"});expect(h.tx.auditLog.create).not.toHaveBeenCalled();}});
  it("READ_ONLY can inspect bounded snapshot but not decide; unsupported snapshot preserves exact recovery capability",async()=>{const h=fixture();h.state.seatType="READ_ONLY";const input={projectId:"p",caseId:"c",requestId:randomUUID()};expect(await previewCaseReview(h.db,"n",input,{clerkActorId:"cl"})).toMatchObject({supported:true,canDecide:false,canRecover:false});h.state.seatType="FULL";h.state.unsupported=true;expect(await previewCaseReview(h.db,"n",input,{clerkActorId:"cl"})).toMatchObject({supported:false,canDecide:false,canRecover:true,snapshot:null,contentHash:null});});
  it("metadata population admission/count precedes digest/materialization and pages never include full procedure",async()=>{const h=fixture(),input={projectId:"p",requestId:randomUUID(),search:"",sort:"confidence" as const,offset:0};const page=await pageCaseReviewQueue(h.db,"n",input,{clerkActorId:"cl"});expect(page.totalPending).toBe(30);expect(page.nextOffset).toBe(25);expect(h.events).toEqual(["current-read-auth","metadata-admission","native-digest","metadata-page"]);expect(page.items[0]).not.toHaveProperty("steps");expect(await countCaseReviewQueue(h.db,"n",{projectId:"p",requestId:randomUUID()},{clerkActorId:"cl"})).toMatchObject({totalPending:30});});
  it("metadata UTF16 mismatch refuses whole page generically, no clipped/empty page",async()=>{const h=fixture();h.state.rows[0]!.title="😀".repeat(2001);await expect(pageCaseReviewQueue(h.db,"n",{projectId:"p",requestId:randomUUID(),search:"",sort:"title",offset:0},{clerkActorId:"cl"})).rejects.toMatchObject({code:"PRECONDITION_FAILED"});});
  it("stale queue population and oversized native cohort refuse before rows",async()=>{const h=fixture();await expect(pageCaseReviewQueue(h.db,"n",{projectId:"p",requestId:randomUUID(),search:"",sort:"title",offset:25,populationHash:"b".repeat(64)},{clerkActorId:"cl"})).rejects.toMatchObject({code:"CONFLICT"});expect(h.events).not.toContain("metadata-page");h.state.populationBytes=16777217n;await expect(countCaseReviewQueue(h.db,"n",{projectId:"p",requestId:randomUUID()},{clerkActorId:"cl"})).rejects.toMatchObject({code:"PRECONDITION_FAILED"});});
});
