import { randomUUID } from "node:crypto";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { TRPCError } from "@trpc/server";
const lock=vi.hoisted(()=>vi.fn());
vi.mock("./manualRetestScope.js",()=>({lockManualRetestAccess:lock}));
import { previewReviewedStep, recordReviewedStep, reviewedStepRequestHash } from "./manualStepExecutionReview.js";
import { qualityProfileHash } from "./qualityExperienceProfile.js";
const actor={id:"n",clerkUserId:"cl"},scope={projectId:"p",organizationId:"o",actorId:"n",actorClerkUserId:"cl"};
function fixture(){
  const steps=[0,1].map(order=>({order,action:` Step ${order} `,expectedActionOrData:" GET /synthetic ",expectedResult:"",expectedResponse:null,mediaAttachmentIds:[]}));
  const definition={testCaseId:"c",title:" Frozen ",validationDomain:"SOFTWARE",reviewStatus:"APPROVED",background:null,given:[],when:[],then:[],verificationProfile:{setup:"",safety:"",instruments:"",acceptanceCriteria:""},steps};
  const run={id:"r",projectId:"p",manualTestCaseIds:["c"],manualPrerequisites:{c:[]},executionContext:{version:1,caseDefinitions:[definition]}};
  const input={projectId:"p",testRunId:"r",testCaseId:"c",stepIndex:0,originalOrganizationId:"o",expectedClerkActorId:"cl",expectedNativeActorId:"n",expectedProcedureHash:qualityProfileHash({definition,graph:run.manualPrerequisites,orderedCaseIds:run.manualTestCaseIds}),expectedCurrentFingerprint:qualityProfileHash({head:null,revision:null}),expectedRevisionId:null,status:"PASS" as const,note:" exact ",observations:{specimen:"",hardwareRevision:"",firmwareVersion:"",environment:"",measurements:[]},evidenceAttachmentIds:[],correctionReason:null,idempotencyKey:randomUUID(),confirmed:true as const};
  const events:string[]=[],flags={exact:true,revisionExact:true,foreign:false,cases:1,steps:2n,runBytes:1000n,headInvalid:false,legacy:false,receipt:null as unknown,receiptCount:0n,missing:false,status:"RUNNING",heads:[] as any[],results:0n,projectionNote:"Derived from 2 recorded step outcomes. Per-step measurements and evidence remain on their immutable revisions.",projectionObservations:{} as unknown,files:[] as any[],filesCount:1n,filesBytes:300n};
  const tx={
    $queryRaw:vi.fn(async(raw:readonly string[]|{sql:string})=>{const sql=Array.isArray(raw)?raw.join("?"):(raw as {sql:string}).sql;
      if(sql.includes('status::text AS status,left')){events.push("run-identity");return[{projectId:"p",status:flags.status,provider:"manual"}];}
      if(sql.includes('pg_advisory_xact_lock')){events.push("actor-uuid-lock");return[];}
      if(sql.includes("FROM \"AuditLog\"")){events.push("receipt-bound");return[{count:flags.receiptCount,bytes:100n}];}
      if(sql.includes('AS "runBytes"')){events.push("native-preflight");return[{runBytes:flags.runBytes,executionBytes:500n,scopeBytes:50n,graphBytes:50n,graphKeys:BigInt(flags.cases),graphEdges:0n,invalidGraph:false,cases:flags.cases,uniqueCases:BigInt(flags.cases),definitions:flags.cases,steps:flags.steps,maxSteps:2,invalid:false,foreign:flags.foreign}];}
      if(sql.includes(' AS present')){events.push("native-case");return[{present:!flags.missing}];}
      if(sql.includes('AS "selectedBytes"')){events.push("native-head-preflight");return[{count:BigInt(flags.heads.length),caseHeads:BigInt(flags.heads.length),bytes:0n,maxBytes:0n,selectedBytes:0n,invalid:flags.headInvalid}];}
      if(sql.includes('"executionContext" IS NOT DISTINCT')){events.push("native-json-proof");return[{exact:flags.exact}];}
      if(sql.includes('observations IS NOT DISTINCT'))return[{exact:flags.revisionExact}];
      if(sql.includes('"uploadVerification" IS NOT DISTINCT'))return[{exact:flags.revisionExact}];
      if(sql.includes(' AS whole')){events.push("mode-proof");return[{whole:0n,results:flags.results,bytes:50n,unsupported:false}];}
      if(sql.includes('FROM "TestCaseAttachment" a JOIN')){events.push("file-native-admission");return[{count:flags.filesCount,bytes:flags.filesBytes,maxBytes:flags.filesBytes,invalid:false}];}
      if(sql.includes('CASE WHEN octet_length(name)'))return[{name:"Synthetic author"}];
      if(sql.includes(' AS bytes')){events.push("incoming-native-bytes");return[{bytes:2300n}];}
      if(sql.includes('set_config')){events.push("derived-selector");return[];}
      throw Error("Unexpected mocked SQL");
    }),
    membership:{findUniqueOrThrow:vi.fn(async()=>({role:"EDITOR",seatType:"FULL"}))},
    auditLog:{findFirst:vi.fn(async()=>flags.receipt),create:vi.fn(async()=>{events.push("atomic-audit");return{};})},
    testRun:{findUniqueOrThrow:vi.fn(async()=>{events.push("private-run");return run;})},
    manualStepResultRevision:{count:vi.fn(async()=>flags.legacy?1:0),findFirst:vi.fn(async()=>({id:"rev"})),create:vi.fn(async(argument:{data:{revisionNumber:number}})=>{events.push("revision-write");return{id:"rev",revisionNumber:argument.data.revisionNumber};})},
    manualStepResultHead:{findMany:vi.fn(async()=>flags.heads),create:vi.fn(async()=>{events.push("head-write");return{};}),update:vi.fn(async()=>({}))},
    testResult:{findMany:vi.fn(async()=>[]),findFirst:vi.fn(async()=>flags.results?{id:"derived",status:"PASS",note:flags.projectionNote,observations:flags.projectionObservations}:null),count:vi.fn(async()=>0),create:vi.fn(async()=>{events.push("derived-write");return{};}),update:vi.fn(async()=>({}))},
    testCaseAttachment:{findMany:vi.fn(async()=>{events.push("private-files");return flags.files;})},
  };
  const db={$transaction:vi.fn(async(fn:(tx:typeof tx)=>unknown,options:unknown)=>{
    const budget=options as {timeout:number;maxWait:number};
    if(budget.timeout===20000) { expect(options).toMatchObject({isolationLevel:"RepeatableRead"}); expect(budget.maxWait).toBe(5000); } // Existing preview contract, unchanged.
    else {
      expect(options).toMatchObject({isolationLevel:"ReadCommitted"});
      expect(Number.isInteger(budget.timeout)&&budget.timeout>0).toBe(true);
      expect(Number.isInteger(budget.maxWait)&&budget.maxWait>0&&budget.maxWait<=5000).toBe(true);
      expect(budget.timeout+budget.maxWait).toBeLessThanOrEqual(20000);
    }
    return fn(tx);
  })};
  lock.mockImplementation(async()=>{events.push("locked-current-scope");return{projectId:"p",organizationId:"o",actorId:"n",clerkActorId:"cl"};});
  return{input,run,flags,events,tx,db:db as never};
}
beforeEach(()=>{lock.mockReset();});
function oldHead(index:number){return{testRunId:"r",testCaseId:"c",stepIndex:index,currentRevisionId:`old${index}`,revisionCount:1,currentPayloadBytes:2500,currentRevision:{id:`old${index}`,testRunId:"r",testCaseId:"c",stepIndex:index,revisionNumber:1,status:"PASS",caseStatusAtRecord:null,note:" exact old ",observations:{specimen:"",hardwareRevision:"",firmwareVersion:"",environment:"",measurements:[]},evidenceAttachmentIds:[],evidenceAttachments:[],actorId:"n",actorName:"Synthetic",recordedAt:new Date("2026-10-05T20:00:00.123Z"),correctionReason:null,previousRevisionId:null,idempotencyKey:randomUUID(),requestHash:"a".repeat(64)}};}
describe("reviewed step service native contracts MOCKED only; SQL/runtime NOT RUN",()=>{
  it("writes exact prose and atomic outer audit; first of two steps does not invent case Pass",async()=>{const h=fixture(),ack=await recordReviewedStep(h.db,actor,h.input);expect(ack).toMatchObject({scope,requestHash:reviewedStepRequestHash(h.input),revisionId:"rev",caseStatus:null,recovered:false});expect(h.tx.manualStepResultRevision.create.mock.calls[0]![0]).toMatchObject({data:{note:" exact ",correctionReason:null}});expect(h.tx.testResult.create).not.toHaveBeenCalled();expect(h.events.indexOf("native-preflight")).toBeLessThan(h.events.indexOf("private-run"));expect(h.events.slice(-3)).toEqual(["revision-write","head-write","atomic-audit"]);});
  it("current native identity is pinned before private receipt or body",async()=>{const h=fixture();await expect(recordReviewedStep(h.db,actor,{...h.input,expectedNativeActorId:"other"})).rejects.toMatchObject({code:"FORBIDDEN"});expect(h.events).toEqual(["locked-current-scope"]);});
  it("authorization refusal precedes receipt lookup",async()=>{const h=fixture();lock.mockRejectedValue(new TRPCError({code:"FORBIDDEN",message:"Synthetic permission refusal"}));await expect(recordReviewedStep(h.db,actor,h.input)).rejects.toMatchObject({code:"FORBIDDEN"});expect(h.events).toEqual([]);expect(h.tx.auditLog.findFirst).not.toHaveBeenCalled();});
  it("accepted reviewed UUID recovers before completion/oversized later bodies",async()=>{const h=fixture();h.flags.receiptCount=1n;h.flags.status="PASSED";h.flags.runBytes=99999999n;h.flags.receipt={organizationId:"o",projectId:"p",entityId:"r",metadata:{projectId:"p",testRunId:"r",testCaseId:"c",stepIndex:0,scope,idempotencyKey:h.input.idempotencyKey,requestHash:reviewedStepRequestHash(h.input),revisionId:"rev",caseStatus:null,recovered:false,provenance:"REVIEWED_REQUEST_BOUND_AT_WRITE"}};expect((await recordReviewedStep(h.db,actor,h.input)).recovered).toBe(true);expect(h.events).toEqual(["locked-current-scope","run-identity","actor-uuid-lock","receipt-bound"]);expect(h.tx.testRun.findUniqueOrThrow).not.toHaveBeenCalled();expect(h.tx.manualStepResultRevision.create).not.toHaveBeenCalled();});
  it("legacy UUID cannot be retroactively labelled a reviewed native receipt",async()=>{const h=fixture();h.flags.legacy=true;await expect(recordReviewedStep(h.db,actor,h.input)).rejects.toMatchObject({code:"CONFLICT"});expect(h.events).not.toContain("native-preflight");expect(h.tx.auditLog.create).not.toHaveBeenCalled();});
  it.each([{runBytes:4194305n},{cases:1001},{steps:25001n},{foreign:true},{headInvalid:true},{missing:true}])("native size/relationship admission refuses before private run %#",async patch=>{const h=fixture();Object.assign(h.flags,patch);await expect(recordReviewedStep(h.db,actor,h.input)).rejects.toMatchObject({code:"PRECONDITION_FAILED"});expect(h.events).not.toContain("private-run");expect(h.tx.manualStepResultRevision.create).not.toHaveBeenCalled();});
  it("native JSON precision mismatch refuses before any revision write",async()=>{const h=fixture();h.flags.exact=false;await expect(recordReviewedStep(h.db,actor,h.input)).rejects.toMatchObject({code:"PRECONDITION_FAILED"});expect(h.tx.manualStepResultRevision.create).not.toHaveBeenCalled();});
  it("procedure/head fingerprint changes refuse without new receipt",async()=>{for(const key of["expectedProcedureHash","expectedCurrentFingerprint"]){const h=fixture();await expect(recordReviewedStep(h.db,actor,{...h.input,[key]:"f".repeat(64)})).rejects.toMatchObject({code:"CONFLICT"});expect(h.tx.auditLog.create).not.toHaveBeenCalled();}});
  it("invalid stored extra index cannot count toward completion",async()=>{const h=fixture();h.flags.heads=[{stepIndex:2,currentRevisionId:"old",revisionCount:1,currentRevision:{testRunId:"r",testCaseId:"c",stepIndex:2,revisionNumber:1,status:"PASS"}}];await expect(recordReviewedStep(h.db,actor,h.input)).rejects.toMatchObject({code:"PRECONDITION_FAILED"});expect(h.tx.testResult.create).not.toHaveBeenCalled();});
  it("unsupported fresh snapshot still returns current recovery authority, not empty substituted fields",async()=>{const h=fixture();h.flags.exact=false;const value=await previewReviewedStep(h.db,actor,{projectId:"p",testRunId:"r",testCaseId:"c",stepIndex:0,readRequestId:randomUUID()});expect(value).toMatchObject({canRecover:true,canRecord:false,supported:false,frozenDefinition:null,current:null,procedureHash:null});});
  it("a real Prisma Date is explicitly projected, not passed to the plain JSON helper",async()=>{const h=fixture();const revision={id:"old",testRunId:"r",testCaseId:"c",stepIndex:0,revisionNumber:1,status:"PASS",caseStatusAtRecord:null,note:" exact old ",observations:{specimen:"",hardwareRevision:"",firmwareVersion:"",environment:"",measurements:[]},evidenceAttachmentIds:[],evidenceAttachments:[],actorId:"n",actorName:"Synthetic",recordedAt:new Date("2026-10-05T20:00:00.123Z"),correctionReason:null,previousRevisionId:null,idempotencyKey:randomUUID(),requestHash:"a".repeat(64)};h.flags.heads=[{testRunId:"r",testCaseId:"c",stepIndex:0,currentRevisionId:"old",revisionCount:1,currentPayloadBytes:2500,currentRevision:revision}];const value=await previewReviewedStep(h.db,actor,{projectId:"p",testRunId:"r",testCaseId:"c",stepIndex:0,readRequestId:randomUUID()});expect(value.supported).toBe(true);expect(value.current?.recordedAt).toEqual(revision.recordedAt);expect(h.tx.$queryRaw.mock.calls.some(call=>String(call[0]).includes('"recordedAt" IS NOT DISTINCT'))).toBe(true);});
  it("missing graph keys and malformed head counters refuse without implicit empty dependencies",async()=>{for(const kind of["graph","counter"]){const h=fixture();if(kind==="graph")h.run.manualPrerequisites={} as typeof h.run.manualPrerequisites;else h.flags.heads=[{stepIndex:0,currentRevisionId:"old",revisionCount:1,currentPayloadBytes:-1,currentRevision:{testRunId:"r",testCaseId:"c",stepIndex:0,revisionNumber:1,status:"PASS"}}];await expect(recordReviewedStep(h.db,actor,h.input)).rejects.toMatchObject({code:"PRECONDITION_FAILED"});expect(h.tx.manualStepResultRevision.create).not.toHaveBeenCalled();}});
  it("corrects a real-Date stored revision with null/prose unchanged and no current-case replacement",async()=>{const h=fixture();h.flags.heads=[oldHead(0)];const preview=await previewReviewedStep(h.db,actor,{projectId:"p",testRunId:"r",testCaseId:"c",stepIndex:0,readRequestId:randomUUID()});await recordReviewedStep(h.db,actor,{...h.input,expectedRevisionId:"old0",expectedCurrentFingerprint:preview.currentFingerprint!,note:null,correctionReason:"  correction reason  "});expect(h.tx.manualStepResultRevision.create.mock.calls[0]![0]).toMatchObject({data:{revisionNumber:2,note:null,correctionReason:"  correction reason  ",previousRevisionId:"old0"}});expect(h.tx.testResult.update).not.toHaveBeenCalled();});
  it("native timestamp/JSON roundtrip refusal keeps old data and receipt untouched",async()=>{const h=fixture();h.flags.heads=[oldHead(0)];h.flags.revisionExact=false;await expect(recordReviewedStep(h.db,actor,h.input)).rejects.toMatchObject({code:"PRECONDITION_FAILED"});expect(h.tx.manualStepResultRevision.create).not.toHaveBeenCalled();expect(h.tx.auditLog.create).not.toHaveBeenCalled();});
  it.each(["note","observations"])("unexplained derived projection %s divergence refuses before overwrite",async kind=>{const h=fixture();h.flags.heads=[oldHead(0),oldHead(1)];h.flags.results=1n;if(kind==="note")h.flags.projectionNote="Extra human note that must not be erased";else h.flags.projectionObservations={retained:"must not be erased"};await expect(recordReviewedStep(h.db,actor,h.input)).rejects.toMatchObject({code:"PRECONDITION_FAILED"});expect(h.tx.testResult.update).not.toHaveBeenCalled();expect(h.tx.manualStepResultRevision.create).not.toHaveBeenCalled();});
  it.each(["oversized","foreign"])("%s evidence metadata refuses before fetching file bodies",async kind=>{const h=fixture();if(kind==="oversized")h.flags.filesBytes=163841n;else h.flags.filesCount=0n;await expect(recordReviewedStep(h.db,actor,{...h.input,evidenceAttachmentIds:["file"]})).rejects.toMatchObject({code:kind==="foreign"?"BAD_REQUEST":"PRECONDITION_FAILED"});expect(h.events).not.toContain("private-files");expect(h.tx.manualStepResultRevision.create).not.toHaveBeenCalled();});
  it("confirmed file metadata is snapshotted only after bounded same-project proof; unknown verification siblings refuse",async()=>{for(const unknown of[false,true]){const h=fixture();h.flags.files=[{id:"file",fileName:"Synthetic.txt",contentType:"text/plain",sizeBytes:10,uploadVerification:{etag:"etag",versionId:null,verifiedAt:"2026-10-05T20:00:00Z",...(unknown?{unknown:"retain"}:{})}}];const promise=recordReviewedStep(h.db,actor,{...h.input,evidenceAttachmentIds:["file"]});if(unknown){await expect(promise).rejects.toMatchObject({code:"PRECONDITION_FAILED"});expect(h.tx.auditLog.create).not.toHaveBeenCalled();}else{await promise;expect(h.events.indexOf("file-native-admission")).toBeLessThan(h.events.indexOf("private-files"));expect(h.tx.manualStepResultRevision.create.mock.calls[0]![0]).toMatchObject({data:{evidenceAttachments:[{id:"file",fileName:"Synthetic.txt",sizeBytes:10,verification:{etag:"etag",versionId:null,verifiedAt:"2026-10-05T20:00:00Z"}}]}});}}});
});
