import { randomUUID } from "node:crypto";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { Prisma, type PrismaClient } from "@vaettir/db";
import { TRPCError } from "@trpc/server";
const lock = vi.hoisted(() => vi.fn());
vi.mock("./manualRetestScope.js", () => ({ lockManualRetestAccess: lock }));
import { readStepResourceHistory, readStepResourceEvidence, stepResourceRequestKey } from "./manualStepExecutionResources.js";
import { stepResourceHistoryInput, stepResourceEvidenceInput, stepResourceHistoryOutput, stepResourceEvidenceOutput } from "./manualStepExecutionResourcesSchema.js";
const actor = { id: "n", clerkUserId: "cl" }, scope = { projectId: "p", organizationId: "o", actorId: "n", actorClerkUserId: "cl" };
function revision(index = 1) {
  return { id: `rev${index}`, testRunId: "r", testCaseId: "c", stepIndex: 0, revisionNumber: index, status: "PASS" as const, caseStatusAtRecord: null,
    note: " exact\n note ", observations: { unknown: [null, "", 0, false], preserved: " raw " }, evidenceAttachmentIds: ["file"], evidenceAttachments: [{ id: "file", fileName: " stored label ", verification: { versionId: "version-1", unknown: "retained" } }],
    actorId: "historical-native-author", actorName: " Stored name ", recordedAt: new Date("2026-10-05T20:00:00.123Z"), correctionReason: null, previousRevisionId: null, idempotencyKey: randomUUID(), requestHash: "a".repeat(64) };
}
function file(id = "file") {
  return { id, testCaseId: "c", fileName: " exact file name .txt ", contentType: "text/plain", sizeBytes: 42,
    uploadCompletedAt: new Date("2026-10-05T20:00:00.123Z"), uploadVerification: { etag: "etag", versionId: null as string | null, verifiedAt: "2026-10-05T20:00:00Z" } as unknown };
}
function fixture() {
  const input = { projectId: "p", testRunId: "r", testCaseId: "c", stepIndex: 0, originalOrganizationId: "o", expectedClerkActorId: "cl", expectedNativeActorId: "n", readRequestId: randomUUID(), cursor: null as string | null, limit: 10 };
  const steps = [{ order: 0, action: " Frozen action ", expectedActionOrData: " API GET ", expectedResult: "", expectedResponse: null, mediaAttachmentIds: ["file"], unknown: "preserved" }];
  const run = { id: "r", projectId: "p", manualTestCaseIds: ["c"], manualPrerequisites: { c: [] } as Record<string, string[]>, executionContext: { version: 1, caseDefinitions: [{ testCaseId: "c", steps }] } };
  const events: string[] = [], flags = { runBytes: 1000n, contextBytes: 500n, cases: 1, steps: 1n, maxSteps: 1, graphKeys: 1n, graphEdges: 0n, invalid: false, exact: true, revisionExact: true, fileExact: true, manual: true,
    revisionCount: null as bigint | null, historyMax: null as bigint | null, historyInvalid: false, historyBytes: null as bigint | null,
    metadata: [1, 2, 3].reverse().map(index => ({ id: `rev${index}`, revisionNumber: index, bytes: 1000n, fingerprint: String(index).repeat(64) })), revisions: [revision(3), revision(2), revision(1)],
    files: [file()], fileCount: 1n, identityBytes: 100n, fileBytes: 1000n, fileMax: 1000n, fileInvalid: false, pageBytes: 1000n, cohort: "e".repeat(64), cursorPresent: true, foreignNative: false };
  const tx = {
    $queryRaw: vi.fn(async (raw: TemplateStringsArray | Prisma.Sql, ...values: unknown[]) => {
      const sql = Array.isArray(raw) ? raw.join("?") : (raw as Prisma.Sql).sql, params = Array.isArray(raw) ? values : (raw as Prisma.Sql).values;
      if (sql.includes('AS manual FROM "TestRun"')) { events.push("run-identity"); return [{ projectId: "p", manual: flags.manual }]; }
      if (sql.includes('AS "runBytes"')) { events.push("native-frozen-admission"); return [{ runBytes: flags.runBytes, contextBytes: flags.contextBytes, scopeBytes: 20n, graphBytes: 20n, cases: flags.cases, uniqueCases: BigInt(flags.cases), definitions: flags.cases, steps: flags.steps, maxSteps: flags.maxSteps, graphKeys: flags.graphKeys, graphEdges: flags.graphEdges, invalid: flags.invalid }]; }
      if (sql.includes('"executionContext" IS NOT DISTINCT')) { events.push("frozen-native-equality"); return [{ exact: flags.exact }]; }
      if (sql.includes('count(*) AS count') && sql.includes('FROM "ManualStepResultRevision"')) { events.push("native-history-admission"); return [{ count: flags.revisionCount ?? BigInt(flags.metadata.length), bytes: flags.historyBytes ?? flags.metadata.reduce((sum, entry) => sum + entry.bytes, 0n), maxBytes: flags.historyMax ?? flags.metadata.reduce((max, entry) => entry.bytes > max ? entry.bytes : max, 0n), invalid: flags.historyInvalid }]; }
      if (sql.includes('SELECT v.id,v."revisionNumber"')) { events.push("native-history-population"); return flags.metadata; }
      if (sql.includes('observations IS NOT DISTINCT')) { events.push("history-native-equality"); return [{ exact: flags.revisionExact }]; }
      if (sql.includes('AS "identityBytes"')) { events.push("native-file-admission"); return [{ count: flags.fileCount, identityBytes: flags.identityBytes, bytes: flags.fileBytes, maxBytes: flags.fileMax, invalid: flags.fileInvalid }]; }
      if (sql.includes('string_agg')) { events.push("native-file-population"); return [{ fingerprint: flags.cohort }]; }
      if (sql.includes('SELECT EXISTS') && sql.includes('"TestCaseAttachment"')) { events.push("cursor-presence"); return [{ present: flags.cursorPresent }]; }
      if (sql.includes('SELECT a.id,a."testCaseId"')) { events.push("native-file-page"); const after = sql.includes('a.id COLLATE "C">') ? params.at(-2) as string : null; return flags.files.filter(entry => after === null || entry.id > after).slice(0, Number(params.at(-1))).map(entry => ({ id: entry.id, testCaseId: flags.foreignNative ? "foreign-case" : entry.testCaseId, bytes: flags.pageBytes })); }
      if (sql.includes('jsonb_build_object') && sql.includes('IS NOT DISTINCT')) { events.push("file-native-equality"); return [{ exact: flags.fileExact }]; }
      throw Error("Unexpected synthetic resource SQL branch");
    }),
    testRun: { findUniqueOrThrow: vi.fn(async () => { events.push("private-frozen-run"); return run; }) },
    manualStepResultRevision: { findMany: vi.fn(async (argument: { where: { id: { in: string[] } } }) => { events.push("private-history-page"); return flags.revisions.filter(entry => argument.where.id.in.includes(entry.id)); }) },
    testCaseAttachment: { findMany: vi.fn(async (argument: { where: { id: { in: string[] } } }) => { events.push("private-evidence-page"); return flags.files.filter(entry => argument.where.id.in.includes(entry.id)); }) },
  };
  const db = { $transaction: vi.fn(async (fn: (transaction: typeof tx) => unknown, config: unknown) => { expect(config).toMatchObject({ isolationLevel: "RepeatableRead", timeout: 20000, maxWait: 5000 }); return fn(tx); }) };
  lock.mockImplementation(async () => { events.push("locked-original-reader"); return { projectId: "p", organizationId: "o", actorId: "n", clerkActorId: "cl" }; });
  return { input, run, flags, events, tx, db: db as unknown as PrismaClient };
}
beforeEach(() => { lock.mockReset(); });

describe("step resource read source/mocks only; native SQL and files NOT RUN", () => {
  it("requires all original pins, explicit search/limit/cursor and no loose extra inputs", () => { const h = fixture(); expect(stepResourceHistoryInput.parse(h.input)).toEqual(h.input); for (const key of ["expectedNativeActorId", "expectedClerkActorId", "originalOrganizationId", "cursor", "limit"]) expect(stepResourceHistoryInput.safeParse({ ...h.input, [key]: undefined }).success).toBe(false); expect(stepResourceEvidenceInput.safeParse(h.input).success).toBe(false); expect(stepResourceEvidenceInput.safeParse({ ...h.input, search: "", url: "https://example.invalid" }).success).toBe(false); });
  it("locked current reader authorization is read-only-readable and precedes all private metadata", async () => { const h = fixture(), result = await readStepResourceHistory(h.db, actor, h.input); expect(lock.mock.calls[0]?.slice(3)).toEqual([false, "cl", false]); expect(h.events[0]).toBe("locked-original-reader"); expect(result.scope).toEqual(scope); expect(result.readRequestId).toBe(h.input.readRequestId); expect(result.requestKey).toBe(stepResourceRequestKey("HISTORY", h.input)); expect(result.provenance).toContain("HISTORICAL_ORIGINAL_TENANCY_UNRECORDED"); });
  it.each(["permission", "native", "Clerk", "org"])("%s refusal reads no private run, history or file rows", async kind => { const h = fixture(); if (kind === "permission") lock.mockRejectedValue(new TRPCError({ code: "FORBIDDEN" })); const input = { ...h.input, ...(kind === "native" ? { expectedNativeActorId: "other" } : kind === "Clerk" ? { expectedClerkActorId: "other" } : kind === "org" ? { originalOrganizationId: "other" } : {}) }; await expect(readStepResourceHistory(h.db, actor, input)).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(h.tx.testRun.findUniqueOrThrow).not.toHaveBeenCalled(); expect(h.tx.manualStepResultRevision.findMany).not.toHaveBeenCalled(); expect(h.tx.testCaseAttachment.findMany).not.toHaveBeenCalled(); });
  it.each([{ cases: 1001 }, { contextBytes: 2097153n }, { steps: 25001n }, { graphKeys: 0n }, { invalid: true }])("native frozen bound %# refuses before private run projection", async patch => { const h = fixture(); Object.assign(h.flags, patch); await expect(readStepResourceHistory(h.db, actor, h.input)).rejects.toMatchObject({ code: "PRECONDITION_FAILED" }); expect(h.tx.testRun.findUniqueOrThrow).not.toHaveBeenCalled(); });
  it.each([851, 1000])("admits %i synthetic frozen root cases without native/runtime acceptance", async count => { const h = fixture(); h.run.manualTestCaseIds = ["c", ...Array.from({ length: count - 1 }, (_, index) => `c${index}`)]; h.run.manualPrerequisites = Object.fromEntries(h.run.manualTestCaseIds.map(id => [id, []])); h.run.executionContext.caseDefinitions = h.run.manualTestCaseIds.map(id => ({ testCaseId: id, steps: h.run.executionContext.caseDefinitions[0]!.steps })); h.flags.cases = count; h.flags.graphKeys = BigInt(count); h.flags.steps = BigInt(count); expect((await readStepResourceHistory(h.db, actor, h.input)).totalRevisions).toBe(3); });
  it("retains exact NULL/empty/prose, unknown raw observations/evidence and every frozen column", async () => { const h = fixture(); h.flags.revisions[0]!.note = null as unknown as string; h.flags.revisions[1]!.note = ""; const result = await readStepResourceHistory(h.db, actor, h.input); expect(result.revisions.map(entry => entry.note)).toEqual([null, "", " exact\n note "]); expect(result.revisions[0]?.observations).toEqual(h.flags.revisions[0]!.observations); expect(result.revisions[0]?.evidenceAttachments).toEqual(h.flags.revisions[0]!.evidenceAttachments); expect(result.frozenStep).toEqual(h.run.executionContext.caseDefinitions[0]!.steps[0]); expect(result.revisions[0]?.recordedAt).toBe("2026-10-05T20:00:00.123Z"); expect(stepResourceHistoryOutput.parse(result)).toEqual(result); });
  it("history count/bytes and selected-page sums are checked before bodies, never silently sliced to fit", async () => { for (const patch of [{ revisionCount: 101n }, { historyMax: 262145n }, { historyInvalid: true }, { historyBytes: 3001n }]) { const h = fixture(); Object.assign(h.flags, patch); await expect(readStepResourceHistory(h.db, actor, h.input)).rejects.toMatchObject({ code: "PRECONDITION_FAILED" }); expect(h.tx.manualStepResultRevision.findMany).not.toHaveBeenCalled(); } const h = fixture(); h.flags.metadata = Array.from({ length: 20 }, (_, index) => ({ id: `rev${20 - index}`, revisionNumber: 20 - index, bytes: 262144n, fingerprint: "a".repeat(64) })); await expect(readStepResourceHistory(h.db, actor, { ...h.input, limit: 20 })).rejects.toMatchObject({ code: "PRECONDITION_FAILED" }); expect(h.tx.manualStepResultRevision.findMany).not.toHaveBeenCalled(); });
  it("history cursor pins exact coordinates, size, original actor and full native population", async () => { const h = fixture(), first = await readStepResourceHistory(h.db, actor, { ...h.input, limit: 1 }); expect(first.revisions[0]?.id).toBe("rev3"); const next = { ...h.input, limit: 1, cursor: first.nextCursor, readRequestId: randomUUID() }; expect((await readStepResourceHistory(h.db, actor, next)).revisions[0]?.id).toBe("rev2"); h.flags.metadata[0]!.fingerprint = "f".repeat(64); h.tx.manualStepResultRevision.findMany.mockClear(); await expect(readStepResourceHistory(h.db, actor, next)).rejects.toMatchObject({ code: "CONFLICT" }); expect(h.tx.manualStepResultRevision.findMany).not.toHaveBeenCalled(); });
  it("copied/changed history cursor cannot switch page size or query coordinate", async () => { const h = fixture(), first = await readStepResourceHistory(h.db, actor, { ...h.input, limit: 1 }); await expect(readStepResourceHistory(h.db, actor, { ...h.input, limit: 2, cursor: first.nextCursor })).rejects.toMatchObject({ code: "CONFLICT" }); await expect(readStepResourceHistory(h.db, actor, { ...h.input, cursor: "not-canonical" })).rejects.toMatchObject({ code: "CONFLICT" }); });
  it.each(["time", "number", "Unicode", "scope", "graph"])("unsupported %s yields generic whole-view refusal, no normalized replacement", async kind => { const h = fixture(); if (kind === "time") h.flags.revisionExact = false; if (kind === "number") h.flags.revisions[0]!.observations = { unknown: [9007199254740992], preserved: "raw" } as unknown as typeof h.flags.revisions[0]["observations"]; if (kind === "Unicode") h.flags.revisions[0]!.actorName = "😀".repeat(101); if (kind === "scope") h.flags.revisions[0]!.testCaseId = "foreign"; if (kind === "graph") h.run.manualPrerequisites = { c: ["outside"] }; await expect(readStepResourceHistory(h.db, actor, h.input)).rejects.toMatchObject({ code: "PRECONDITION_FAILED", message: expect.not.stringContaining("Stored name") }); });
  it("picker is confirmed/same-project scoped; exact labels/version disclosure include no storage locator or file read", async () => { const h = fixture(), result = await readStepResourceEvidence(h.db, actor, { ...h.input, search: " name " }); expect(result.attachments[0]).toMatchObject({ fileName: " exact file name .txt ", uploadVerification: h.flags.files[0]!.uploadVerification, versionId: null, selectable: true, versionProvenance: "UNVERSIONED_NOT_IMMUTABLE" }); expect(result.search).toBe(" name "); expect(result.scope).toEqual(scope); expect(result.requestKey).toBe(stepResourceRequestKey("EVIDENCE", { ...h.input, search: " name " })); expect(h.events.indexOf("native-file-admission")).toBeLessThan(h.events.indexOf("native-file-population")); expect(h.events.indexOf("native-file-page")).toBeLessThan(h.events.indexOf("private-evidence-page")); expect(h.tx.testCaseAttachment.findMany.mock.calls[0]?.[0]).toMatchObject({ where: { testCase: { projectId: "p" }, uploadCompletedAt: { not: null } } }); expect(JSON.stringify(result)).not.toContain("storageUrl"); expect(JSON.stringify(result)).not.toContain("viewUrl"); expect(stepResourceEvidenceOutput.parse(result)).toEqual(result); });
  it("known version and unknown verification remain distinguishable, never fabricated as an unversioned record", async () => { const h = fixture(); h.flags.files[0]!.uploadVerification = { etag: "e", versionId: "version-1", verifiedAt: "2026-10-05T20:00:00Z" }; expect((await readStepResourceEvidence(h.db, actor, { ...h.input, search: "" })).attachments[0]).toMatchObject({ versionId: "version-1", versionProvenance: "VERSION_ID_RECORDED_NOT_FETCHED" }); h.flags.files[0]!.uploadVerification = { unknown: [0, false, null], versionId: 42 }; const unsupported = (await readStepResourceEvidence(h.db, actor, { ...h.input, search: "" })).attachments[0]!; expect(unsupported.uploadVerification).toEqual(h.flags.files[0]!.uploadVerification); expect(unsupported.selectable).toBe(false); expect(unsupported.versionProvenance).toBe("UNSUPPORTED_VERIFICATION_RETAINED_READ_ONLY"); expect(Object.hasOwn(unsupported, "versionId")).toBe(false); });
  it.each([{ fileCount: 10001n }, { identityBytes: 2097153n }, { fileBytes: 8388609n }, { fileMax: 8193n }, { fileInvalid: true }, { pageBytes: 8193n }])("picker native bound %# refuses before private file rows", async patch => { const h = fixture(); Object.assign(h.flags, patch); await expect(readStepResourceEvidence(h.db, actor, { ...h.input, search: "" })).rejects.toMatchObject({ code: "PRECONDITION_FAILED" }); expect(h.tx.testCaseAttachment.findMany).not.toHaveBeenCalled(); });
  it("picker cursor detects native label/verification population changes and refuses missing/cross-search cursors", async () => { const h = fixture(); h.flags.files = [file("a"), file("b")]; h.flags.fileCount = 2n; const first = await readStepResourceEvidence(h.db, actor, { ...h.input, limit: 1, search: "" }); expect(first.attachments[0]?.id).toBe("a"); const next = { ...h.input, limit: 1, search: "", cursor: first.nextCursor, readRequestId: randomUUID() }; expect((await readStepResourceEvidence(h.db, actor, next)).attachments[0]?.id).toBe("b"); await expect(readStepResourceEvidence(h.db, actor, { ...next, search: "new search" })).rejects.toMatchObject({ code: "CONFLICT" }); h.flags.cursorPresent = false; await expect(readStepResourceEvidence(h.db, actor, next)).rejects.toMatchObject({ code: "CONFLICT" }); h.flags.cursorPresent = true; h.flags.cohort = "d".repeat(64); h.tx.testCaseAttachment.findMany.mockClear(); await expect(readStepResourceEvidence(h.db, actor, next)).rejects.toMatchObject({ code: "CONFLICT" }); expect(h.tx.testCaseAttachment.findMany).not.toHaveBeenCalled(); });
  it.each(["precision", "foreign", "Unicode"])("picker %s refusal preserves native metadata instead of fixing/clipping it", async kind => { const h = fixture(); if (kind === "precision") h.flags.fileExact = false; if (kind === "foreign") h.flags.foreignNative = true; if (kind === "Unicode") h.flags.files[0]!.fileName = "😀".repeat(128); await expect(readStepResourceEvidence(h.db, actor, { ...h.input, search: "" })).rejects.toMatchObject({ code: "PRECONDITION_FAILED" }); expect(h.flags.files[0]!.fileName).toBe(kind === "Unicode" ? "😀".repeat(128) : " exact file name .txt "); });
  it("no recorded revision is treated as native readiness, a fix verification, or media immutability", async () => { const h = fixture(), history = await readStepResourceHistory(h.db, actor, h.input); expect(history.revisions[0]?.actorId).toBe("historical-native-author"); expect(history.revisions[0]?.versionProvenance).toBe("STORED_REVISION_METADATA_NOT_FILE_IMMUTABILITY_PROOF"); expect(history.provenance).not.toBe("HISTORICAL_ORIGINAL_ACTOR_VERIFIED"); });
});
