import {randomUUID} from "node:crypto";
import {afterEach,beforeEach,describe,it,expect,vi} from "vitest";
import {prisma} from "@vaettir/db";
import {repositoryConnectionsRouter} from "./routers/repositoryConnections.js";
import {verifyGithubAppRepositoryAuthorization,listGithubAppInstallations,listGithubAppInstallationRepositories} from "./services/githubAppRepositoryConnection.js";
import {revokeGithubAuthorization} from "./services/githubRepositoryOAuth.js";
import {decryptToken,type EncryptedToken} from "./services/tokenEncryption.js";
import type {Context} from "./trpc.js";

vi.mock("./services/githubAppRepositoryConnection.js",async original=>({...await original<typeof import("./services/githubAppRepositoryConnection.js")>(),verifyGithubAppRepositoryAuthorization:vi.fn(),listGithubAppInstallations:vi.fn(),listGithubAppInstallationRepositories:vi.fn()}));
vi.mock("./services/githubRepositoryOAuth.js",async original=>({...await original<typeof import("./services/githubRepositoryOAuth.js")>(),revokeGithubAuthorization:vi.fn().mockResolvedValue(undefined)}));
const database=process.env.DATABASE_URL?new URL(process.env.DATABASE_URL):null;
const isolated=database&&["localhost","127.0.0.1"].includes(database.hostname)&&/test/i.test(database.pathname)&&!database.searchParams.has("host");
const application={kind:"github-app/v1",clientSecret:"synthetic-app-secret-not-live",appId:"123",slug:"synthetic-readonly-app"};

describe.skipIf(!isolated)("GitHub App router tenant integrity (isolated synthetic DB)",()=>{
  const organizations:string[]=[],actors:string[]=[];
  let organizationId:string,projectId:string;
  async function organization(){const key=randomUUID(),tier=await prisma.planTier.findUniqueOrThrow({where:{key:"free"}});const org=await prisma.organization.create({data:{name:key,slug:`app-${key}`,planTierId:tier.id}});organizations.push(org.id);const project=await prisma.project.create({data:{organizationId:org.id,name:"Synthetic App repositories",slug:"app",caseKey:`app-${organizations.length}`}});return{organizationId:org.id,projectId:project.id};}
  async function actor(){const key=randomUUID();const user=await prisma.user.create({data:{clerkUserId:key,email:`app-${key}@example.com`,memberships:{create:{organizationId,role:"OWNER",seatType:"FULL"}}},include:{memberships:true}});actors.push(user.id);const ctx:Context&{user:typeof user}={prisma,user,authenticatedClerkSubject:key,staff:null,securityLogger:undefined,staffAttempt:{tokenConfigured:false,tokenPresented:false,actorHeaderPresented:false}};return{user,caller:repositoryConnectionsRouter.createCaller(ctx)};}
  let owner:Awaited<ReturnType<typeof actor>>;
  const request=()=>({projectId,configurationId:"platform:github-app",approveMetadataAccess:true as const});
  async function verified(){const begun=await owner.caller.begin(request());await owner.caller.finish({state:new URL(begun.url).searchParams.get("state")!,code:"synthetic-code"});expect(verifyGithubAppRepositoryAuthorization).toHaveBeenCalledWith(expect.objectContaining({clientId:"synthetic-app-client",clientSecret:application.clientSecret}));return begun;}
  const repository=(id:string,installationId:string)=>({id,name:`synthetic/repo-${id}`,url:`https://github.com/synthetic/repo-${id}`,defaultBranch:"main",scopeKey:JSON.stringify(["github-installation/v1",installationId])});
  beforeEach(async()=>{
    vi.clearAllMocks();vi.stubEnv("GITHUB_REPOSITORY_APP_CLIENT_ID","synthetic-app-client");vi.stubEnv("GITHUB_REPOSITORY_APP_CLIENT_SECRET",application.clientSecret);vi.stubEnv("GITHUB_REPOSITORY_APP_ID",application.appId);vi.stubEnv("GITHUB_REPOSITORY_APP_SLUG",application.slug);vi.stubEnv("WEB_APP_URL","https://vaettir.synthetic.example");vi.stubEnv("PRODUCTION_SIGNAL_ENCRYPTION_KEY",Buffer.alloc(32,8).toString("base64"));
    ({organizationId,projectId}=await organization());owner=await actor();
    vi.mocked(verifyGithubAppRepositoryAuthorization).mockResolvedValue({token:"synthetic-user-token-not-live",expiresAt:new Date(Date.now()+3600000),accountLabel:"synthetic"});
    vi.mocked(revokeGithubAuthorization).mockResolvedValue(undefined);
    vi.mocked(listGithubAppInstallations).mockResolvedValue({installations:[{id:"456",accountLabel:"synthetic",repositorySelection:"selected",page:1}],hasMore:false,limitReached:false});
    vi.mocked(listGithubAppInstallationRepositories).mockImplementation(async(_token,_app,id)=>({repositories:[repository("101",id)],hasMore:false,limitReached:false,scopeKey:JSON.stringify(["github-installation/v1",id])}));
  });
  afterEach(async()=>{
    await prisma.projectRepository.deleteMany({where:{projectId:{in:(await prisma.project.findMany({where:{organizationId:{in:organizations}},select:{id:true}})).map(p=>p.id)}}});
    await prisma.repositoryConnection.deleteMany({where:{organizationId:{in:organizations}}});await prisma.repositoryProviderConfiguration.deleteMany({where:{organizationId:{in:organizations}}});await prisma.project.deleteMany({where:{organizationId:{in:organizations}}});await prisma.membership.deleteMany({where:{organizationId:{in:organizations}}});await prisma.organization.deleteMany({where:{id:{in:organizations}}});await prisma.user.deleteMany({where:{id:{in:actors}}});organizations.length=0;actors.length=0;vi.unstubAllEnvs();
  });
  it("snapshots tagged encrypted App credentials and begins without broad OAuth scope",async()=>{
    const before=await owner.caller.configurations({projectId});expect(before.configurations).toContainEqual(expect.objectContaining({id:"platform:github-app",authorizationKind:"github-app",installationUrl:"https://github.com/apps/synthetic-readonly-app/installations/new"}));expect(await prisma.repositoryProviderConfiguration.count({where:{organizationId}})).toBe(0);
    const begun=await owner.caller.begin(request());expect(new URL(begun.url).searchParams.has("scope")).toBe(false);
    const connection=await prisma.repositoryConnection.findUniqueOrThrow({where:{id:begun.id}});expect(connection.provider).toBe("github");const config=await prisma.repositoryProviderConfiguration.findUniqueOrThrow({where:{id:connection.configurationId!}});expect(config.provider).toBe("github-app");expect(JSON.stringify(config.encryptedSecret)).not.toContain(application.clientSecret);expect(JSON.parse(decryptToken(config.encryptedSecret as unknown as EncryptedToken))).toEqual(application);
  });
  it("retains verified App descriptors and revokes using original actual clientSecret after rotation",async()=>{
    const begun=await verified();expect(await owner.caller.status({id:begun.id})).toMatchObject({status:"VERIFIED",authorizationKind:"github-app",installationUrl:"https://github.com/apps/synthetic-readonly-app/installations/new"});expect((await owner.caller.mine({projectId})).find(r=>r.id===begun.id)).toMatchObject({authorizationKind:"github-app"});vi.stubEnv("GITHUB_REPOSITORY_APP_CLIENT_SECRET","rotated-secret");await owner.caller.disconnect({id:begun.id});expect(revokeGithubAuthorization).toHaveBeenCalledWith(expect.objectContaining({clientId:"synthetic-app-client",clientSecret:application.clientSecret,token:"synthetic-user-token-not-live"}));
  });
  it("requires an installation and binds catalogue CAS to its native identity",async()=>{
    const begun=await verified();expect(await owner.caller.installations({id:begun.id})).toMatchObject({installations:[{id:"456"}]});expect(await owner.caller.list({id:begun.id})).toMatchObject({repositories:[],githubInstallationRequired:true});expect(listGithubAppInstallationRepositories).not.toHaveBeenCalled();
    const first=await owner.caller.list({id:begun.id,githubInstallationId:"456"});expect(first.scopeKey).toBe(JSON.stringify(["github-installation/v1","456"]));const second=await owner.caller.list({id:begun.id,githubInstallationId:"789"});expect(second.catalogVersion).not.toBe(first.catalogVersion);await expect(owner.caller.connectSelected({id:begun.id,repositoryIds:["101"],catalogVersion:first.catalogVersion,approved:true})).rejects.toMatchObject({code:"CONFLICT"});expect(await owner.caller.connectSelected({id:begun.id,repositoryIds:["101"],catalogVersion:second.catalogVersion,approved:true})).toEqual({connected:1});
  });
  for(const operation of ["finish","installations","list"] as const)it(`rejects project reparent during ${operation} provider IO`,async()=>{
    const begun=operation==="finish"?await owner.caller.begin(request()):await verified();const other=await organization();await prisma.membership.create({data:{organizationId:other.organizationId,userId:owner.user.id,role:"OWNER",seatType:"FULL"}});const reparent=()=>prisma.project.update({where:{id:projectId},data:{organizationId:other.organizationId,slug:"moved"}});
    if(operation==="finish")vi.mocked(verifyGithubAppRepositoryAuthorization).mockImplementationOnce(async()=>{await reparent();return{token:"synthetic-race-token",expiresAt:new Date(Date.now()+3600000),accountLabel:"synthetic"};});
    else if(operation==="installations")vi.mocked(listGithubAppInstallations).mockImplementationOnce(async()=>{await reparent();return{installations:[],hasMore:false,limitReached:false};});
    else vi.mocked(listGithubAppInstallationRepositories).mockImplementationOnce(async()=>{await reparent();return{repositories:[repository("101","456")],scopeKey:JSON.stringify(["github-installation/v1","456"]),hasMore:false,limitReached:false};});
    const pending=operation==="finish"?owner.caller.finish({state:new URL(begun.url).searchParams.get("state")!,code:"synthetic-code"}):operation==="installations"?owner.caller.installations({id:begun.id}):owner.caller.list({id:begun.id,githubInstallationId:"456"});await expect(pending).rejects.toMatchObject({code:operation==="finish"?"BAD_REQUEST":"FORBIDDEN"});expect(await prisma.projectRepository.count({where:{projectId}})).toBe(0);if(operation==="finish"){expect((await prisma.repositoryConnection.findUniqueOrThrow({where:{id:begun.id}})).status).not.toBe("VERIFIED");expect(revokeGithubAuthorization).toHaveBeenCalledWith(expect.objectContaining({clientSecret:application.clientSecret,token:"synthetic-race-token"}));}
  });
  it("refuses reviewed selection after project reparent",async()=>{
    const begun=await verified(),listed=await owner.caller.list({id:begun.id,githubInstallationId:"456"}),other=await organization();await prisma.membership.create({data:{organizationId:other.organizationId,userId:owner.user.id,role:"OWNER",seatType:"FULL"}});await prisma.project.update({where:{id:projectId},data:{organizationId:other.organizationId,slug:"moved"}});await expect(owner.caller.connectSelected({id:begun.id,repositoryIds:["101"],catalogVersion:listed.catalogVersion,approved:true})).rejects.toMatchObject({code:"FORBIDDEN"});expect(await prisma.projectRepository.count({where:{projectId}})).toBe(0);
  });
  it("refuses native Clerk actor remap during provider IO",async()=>{
    const begun=await verified();vi.mocked(listGithubAppInstallationRepositories).mockImplementationOnce(async()=>{await prisma.user.update({where:{id:owner.user.id},data:{clerkUserId:randomUUID()}});return{repositories:[repository("101","456")],scopeKey:JSON.stringify(["github-installation/v1","456"]),hasMore:false,limitReached:false};});await expect(owner.caller.list({id:begun.id,githubInstallationId:"456"})).rejects.toMatchObject({code:"FORBIDDEN"});expect(await prisma.projectRepository.count({where:{projectId}})).toBe(0);
  });
  it("refuses reviewed selection after native Clerk remap",async()=>{
    const begun=await verified(),listed=await owner.caller.list({id:begun.id,githubInstallationId:"456"});await prisma.user.update({where:{id:owner.user.id},data:{clerkUserId:randomUUID()}});await expect(owner.caller.connectSelected({id:begun.id,repositoryIds:["101"],catalogVersion:listed.catalogVersion,approved:true})).rejects.toMatchObject({code:"FORBIDDEN"});expect(await prisma.projectRepository.count({where:{projectId}})).toBe(0);
  });
  it("resets an empty installation catalogue when changing native installation",async()=>{
    const begun=await verified();vi.mocked(listGithubAppInstallationRepositories).mockResolvedValueOnce({repositories:[],hasMore:false,limitReached:false,scopeKey:JSON.stringify(["github-installation/v1","456"])});const empty=await owner.caller.list({id:begun.id,githubInstallationId:"456"});const next=await owner.caller.list({id:begun.id,githubInstallationId:"789"});expect(next.catalogReset).toBe(true);expect(next.catalogVersion).not.toBe(empty.catalogVersion);expect(next.scopeKey).toBe(JSON.stringify(["github-installation/v1","789"]));
  });
  it("retains issued encrypted grant when reparent refusal cannot revoke upstream",async()=>{
    const begun=await owner.caller.begin(request()),other=await organization();await prisma.membership.create({data:{organizationId:other.organizationId,userId:owner.user.id,role:"OWNER",seatType:"FULL"}});vi.mocked(verifyGithubAppRepositoryAuthorization).mockImplementationOnce(async()=>{await prisma.project.update({where:{id:projectId},data:{organizationId:other.organizationId,slug:"moved"}});return{token:"synthetic-revocation-pending-token",expiresAt:new Date(Date.now()+3600000),accountLabel:"synthetic"};});vi.mocked(revokeGithubAuthorization).mockRejectedValueOnce(Error("synthetic provider uncertainty"));await expect(owner.caller.finish({state:new URL(begun.url).searchParams.get("state")!,code:"synthetic-code"})).rejects.toMatchObject({code:"PRECONDITION_FAILED"});const retained=await prisma.repositoryConnection.findUniqueOrThrow({where:{id:begun.id}});expect(retained.status).toBe("REVOCATION_PENDING");expect(JSON.stringify(retained.encryptedToken)).not.toContain("synthetic-revocation-pending-token");expect(decryptToken(retained.encryptedToken as unknown as EncryptedToken)).toBe("synthetic-revocation-pending-token");expect(revokeGithubAuthorization).toHaveBeenCalledWith(expect.objectContaining({clientSecret:application.clientSecret}));
  });
  it("refuses begin after native Clerk remap without creating snapshot",async()=>{
    await prisma.user.update({where:{id:owner.user.id},data:{clerkUserId:randomUUID()}});await expect(owner.caller.begin(request())).rejects.toMatchObject({code:"FORBIDDEN"});expect(await prisma.repositoryProviderConfiguration.count({where:{organizationId}})).toBe(0);expect(await prisma.repositoryConnection.count({where:{organizationId}})).toBe(0);
  });
  it("retains a grant after finish Clerk remap and explicitly disconnects with the original secret",async()=>{
    const begun=await owner.caller.begin(request());vi.mocked(verifyGithubAppRepositoryAuthorization).mockImplementationOnce(async()=>{await prisma.user.update({where:{id:owner.user.id},data:{clerkUserId:randomUUID()}});return{token:"synthetic-remap-pending-token",expiresAt:new Date(Date.now()+3600000),accountLabel:"synthetic"};});vi.mocked(revokeGithubAuthorization).mockRejectedValueOnce(Error("synthetic revoke uncertainty"));await expect(owner.caller.finish({state:new URL(begun.url).searchParams.get("state")!,code:"synthetic-code"})).rejects.toMatchObject({code:"PRECONDITION_FAILED"});const retained=await prisma.repositoryConnection.findUniqueOrThrow({where:{id:begun.id}});expect(retained.status).toBe("REVOCATION_PENDING");expect(decryptToken(retained.encryptedToken as unknown as EncryptedToken)).toBe("synthetic-remap-pending-token");
    await prisma.user.update({where:{id:owner.user.id},data:{clerkUserId:owner.user.clerkUserId}});vi.stubEnv("GITHUB_REPOSITORY_APP_CLIENT_SECRET","synthetic-rotated-secret");await owner.caller.disconnect({id:begun.id});expect(revokeGithubAuthorization).toHaveBeenLastCalledWith(expect.objectContaining({clientId:"synthetic-app-client",clientSecret:application.clientSecret,token:"synthetic-remap-pending-token"}));const disconnected=await prisma.repositoryConnection.findUniqueOrThrow({where:{id:begun.id}});expect(disconnected.status).toBe("DISCONNECTED");expect(disconnected.encryptedToken).toBeNull();
  });
  it("serializes actor-wide twentieth attempt across distinct projects",async()=>{
    await prisma.repositoryConnection.createMany({data:Array.from({length:19},()=>({projectId,organizationId,actorId:owner.user.id,provider:"github",origin:"https://github.com",stateHash:randomUUID(),status:"FAILED",authorizationExpiresAt:new Date(Date.now()-1000)}))});const otherProject=await prisma.project.create({data:{organizationId,name:"Synthetic parallel App",slug:"parallel",caseKey:"app-parallel"}});const outcomes=await Promise.allSettled([owner.caller.begin(request()),owner.caller.begin({...request(),projectId:otherProject.id})]);expect(outcomes.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect(outcomes.find(r=>r.status==="rejected")).toMatchObject({reason:{code:"TOO_MANY_REQUESTS"}});expect(await prisma.repositoryConnection.count({where:{actorId:owner.user.id}})).toBe(20);
  });
});
